### ISSUE TITLE
Versão 1 - Alterações na seção 5 - REALIZOU EXAME DE IMAGEM

### ISSUE THREAD

**Issue by FabioBezerra** [db1group/contra-covid19#105]
## Feature Request

**Descreva a solução que você gostaria**
-Ao marcar o sim na seção 5. REALIZOU EXAME DE IMAGEM, deve dizer q é obrigatorio selecionar algum tipo de Raio ou Tomografia
-Ao marcar o Raio X Normal, nao pode marcar outro tipo de Raio X
-Ao marcar o Raio X Outro, deve preencher a especificação
-Ao marcar o Tomografia Normal, nao pode marcar outro tipo de Tomografia
-Ao marcar o Tomografia Outro, deve preencher a especificação

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![pHLD6P9GLs](https://user-images.githubusercontent.com/15328510/80315021-6886d880-87cb-11ea-8053-525c43d29628.gif)
