### ISSUE TITLE
Versão 1 - Alterações na ordem das seções

### ISSUE THREAD

**Issue by FabioBezerra** [db1group/contra-covid19#106]
## Feature Request

**Descreva a solução que você gostaria**
-Alterar a ordem da seção 9. REALIZADO COLETA DE MATERIAL PARA DIAGNÓSTICO. Agora vai ser o 8. REALIZADO COLETA DE MATERIAL PARA DIAGNÓSTICO
-Criar uma seção para o Histórico de viagem? que atualmente está na seção 7. (seção 9. HISTÓRIO DE VIAGEM)
-Criar nova seção 10. Contato com suspeito ou confirmado. Dentro dessa seção vai ter os dados das seções 10 e 11 (olhar ficha) - 
	Campos: tp_ContatoSuspeito (Suspeito / Confirmado / Sem contato) ,tp_LocalSuspeito (Domicílio / Unidade de saúde/Local de trabalho ), ds_LocalSuspeito, Nome_Suspeito
-Criar nova seção 11. Outras informações e colocar a 'Recebeu vacina contra Gripe nos últimos doze meses?' que está dentro da seção 7.
-Alterar a seção 8. CONCLUSÃO DO ATENDIMENTO para 12. CONCLUSÃO DO ATENDIMENTO
-Alterar a seção 12. OBSERVAÇÕES para 13. OBSERVAÇÕES

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 https://qa-app.notificasaude.com.br/

![VxckeOKpcI](https://user-images.githubusercontent.com/15328510/80283801-d01c2580-86f0-11ea-9d30-3d18633c01a5.gif)
