### ISSUE TITLE
Mudanças na tela de evolução

### ISSUE THREAD

**Issue by FabioBezerra** [db1group/contra-covid19#111]
## Feature Request

**Descreva a solução que você gostaria**
Incluir botão "Voltar" na tela. Para que retorne para a tela de consulta
Mudar a descrição do botão "Atualizar Notificão" para "Incluir"
Ao abrir a tela posicionar no campo "Data e hora da notificação"
Mudar o segundo combo para "Condição atual do paciente" (está duplicado nos dois campos).

Tirar a palavra "alta com" da "alta com isolamento domiciliar". Vai ficar apenas "Isolamento Domiciliar".

**Comment by CristianeBorges05** [comment]
Bug com impedimento pois não estou conseguindo acessar a tela de evolução.

Request URL: https://qa-api.notificasaude.com.br/api/notificacoes/1a001fed-3811-4ae1-b981-37d1349d3422/evolucoes
Request Method: GET
Status Code: 400 
Remote Address: 52.205.247.211:443
Referrer Policy: no-referrer-when-downgrade

**Comment by maykon** [comment]
@CristianeBorges05 A notificação está ENCERRADA ou EXCLUÍDA não vai permitir evoluir.

**Comment by CristianeBorges05** [comment]
Validado ok
![Melhorias evolução 111](https://user-images.githubusercontent.com/63747448/80280985-4cf1d400-86de-11ea-81ea-8eba997da897.gif)
