### ISSUE TITLE
Liberar o campo Unidade Notificante no Cadastro de notificação

### ISSUE THREAD

**Issue by jef-araujo** [db1group/contra-covid19#114]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
o campo Unidade Notificante está com valor fixo.

**Descreva a solução que você gostaria**
O campo deve ser preenchido com o campo relativo do banco de dados, ou de alguma forma pela autenticação (deve exibir a unidade de saude do usuário logado)

**Descreva qualquer alternativa considerada**

**Documentação, Adoção, Estratégia de migração**
Deverá ser visível a Unidade Notificante referente ao usuário logado no sistema.
Mais detalhes verificar com Rogerio e @maykon que desenvolveu o sistema de segurança.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80282482-2df83f80-86e8-11ea-8f23-707f9368d7bd.png)
