### ISSUE TITLE
Não exibe o município do paciente no cadastro de Notificação

### ISSUE THREAD

**Issue by jef-araujo** [db1group/contra-covid19#116]
## Bug Report

**Comportamento atual**
Não exibe o município do paciente no cadastro de Notificação

**Comportamento/código esperado**
Exibir o valor "Maringá"

**Contexto adicional/Screenshots**
Verificado com o Rogério que o valor pode ser fixo.
No código está fixando o id **fcf83c0a-8de6-43a5-9845-907f597f56ce** relativo a Maringá, mas o valor não é exibido na tela.

![image](https://user-images.githubusercontent.com/12651527/79817705-76b49f00-835c-11ea-9cb1-40ab5765ea36.png)

**Possíveis soluções**

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 23/04/2020 no ambiente https://app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80161240-1dd84700-85a6-11ea-8812-2cde15b811a6.png)

**Comment by CristianeBorges05** [comment]
Acho que essa regra já foi atualizada. Precisamos atualizar caso de teste.
