### ISSUE TITLE
Para salvar a notificação, está sendo necessário preencher o campo Gestante

### ISSUE THREAD

**Issue by jef-araujo** [db1group/contra-covid19#118]
## Bug Report

**Comportamento atual**
No cadastro de notificação, para salvar a notificação, está sendo necessário preencher o campo Gestante

**Comportamento/código esperado**
O campo só deve ser obrigatório para paciente do sexo Feminino.

**Contexto adicional/Screenshots**

**Possíveis soluções**
Código no backend:

```
const obterGestante = (sexo, gestante) => {
  if (sexo === 'M') {
    return 'NAO_APLICADO';
  }
  if (gestante) {
    return 'SIM';
  }
  return 'NAO';
};
```

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/

![RjNDOc3sHo](https://user-images.githubusercontent.com/15328510/80283454-0b692500-86ee-11ea-9173-e5ee68bab0d1.gif)
