### ISSUE TITLE
Mudanças de layout

### ISSUE THREAD

**Issue by FabioBezerra** [db1group/contra-covid19#119]
## Feature Request
**Descreva a solução que você gostaria**
-Colocar no sentido horizontal as opções de 'Sexo' e 'Gestante'.
-Colocar na frente do 'Sintomático' a 'Data inicio do sintomas'.
-Alterar na seção 5. REALIZOU EXAME DE IMAGEM o 'Sim' e o 'Não' para ficar na horizontal

**Comment by wildeee** [comment]
A parte de Sexo e Gestante, já aproveitei e fiz em uma outra atividade de bug
