### ISSUE TITLE
Salvar em caixa altano banco campos do Paciente da notificação

### ISSUE THREAD

**Issue by jef-araujo** [db1group/contra-covid19#121]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Rogério solicitou para facilitar a busca.

**Descreva a solução que você gostaria**
Nome,  nome da mãe, logradouro - salvar no banco em caixa alta e remover acentos.

**Descreva qualquer alternativa considerada**
O código tratar isso na busca (sem precisar fazer essa alteração no valor salvo no banco).

**Documentação, Adoção, Estratégia de migração**
Mais detalhes verificar com o Rogério.

**Comment by CristianeBorges05** [comment]
Preciso de algum dev para alinhar  como pode ser validado esse bug a nível de banco

**Comment by CristianeBorges05** [comment]
Validado letras maiúsculas e acentos!
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/63747448/80232342-20c94b00-862b-11ea-9cb2-c7055c25dbc5.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso:

![image](https://user-images.githubusercontent.com/6394762/80269794-3a997b00-8689-11ea-95ad-efd8b2b68ff2.png)
