### ISSUE TITLE
Link na tela de evolução da notificação para abrir uma ficha de notificação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#124]
O usuário pode precisar consultar mais dados da notificação. Entretanto, colocar todas as informações da ficha na tela de evolução é inviável.

**Descreva a solução que você gostaria**
Colocar um link na tela de evolução. Quando o usuário clicar deverá abrir a notificação que esta visualizando em outra pasta do navegador.
O nome do link pode ser "Ver ficha completa".

**Comment by CristianeBorges05** [comment]
impedida pelo bug
![image](https://user-images.githubusercontent.com/63747448/80659920-b23c2100-8a60-11ea-941e-085c992ac469.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
