### ISSUE TITLE
Não está exibindo mensagem de erro ao Enviar uma notificação

### ISSUE THREAD

**Issue by jef-araujo** [db1group/contra-covid19#130]
## Bug Report

**Comportamento atual**
No cadastro de Notificação, não está exibindo mensagem de erro ao Enviar uma notificação.
O erro apenas fica visivel no console do navegador.

**Comportamento/código esperado**
Caso haja erros no cadastro sendo efetuado, ao Enviar, mostrar as mensagens de validação.

**Contexto adicional/Screenshots**
Exmplo de mensagem de erro:

```
{
    "error": ""userId" é obrigatório"
}

```
Havia um problema no backend tambem, que foi corrigido aqui: https://github.com/db1group/contra-covid19/pull/129

**Possíveis soluções**
Não faço idéia, o google deve saber.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020:

POST: https://qa-api.notificasaude.com.br/api/notificacoes

![image](https://user-images.githubusercontent.com/15328510/80318967-2e760080-87e4-11ea-8732-9edf399176cc.png)
