### ISSUE TITLE
Criar rota para POST /profissoes

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#136]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Os testers e os devs vão precisar interagir com o banco para gerar novas profissões

**Descreva a solução que você gostaria**
Criar uma rota POST, visando input de dados

**Documentação, Adoção, Estratégia de migração**
JSON para lançamento de dados

```js
{
      "nome": "Desenvolvedor de Sistemas",
}
```

**Comment by AndressaKarla** [comment]
estes concluídos com sucesso no dia 25/04/2020:

POST: https://qa-api.notificasaude.com.br/api/profissoes
Cadastro de Notificação: https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80288075-cb189f80-870b-11ea-8cfc-eb9ef7b6750f.png)
