### ISSUE TITLE
[BX][LT] Titulo da seção 11 está errado

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#142]
## Bug Report
**Ambiente**
https://covid19-db1-frontend.herokuapp.com/

**Reprodução**
Dado que eu acesse a tela de criação de notificação.
Quando ir até a seção 11

**Problema**
o titulo da seção está como *"HISTÓRICO DE VIAGEM"*
mas a seção é de vacina
![image](https://user-images.githubusercontent.com/6394762/79868155-e3a85300-83b5-11ea-8a9e-ce81a3218bd9.png)

**Resultado esperado**
O titulo deveria ser de seção de vacina.

Duvidas a disposição

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 23/04/2020 no ambiente https://app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80158814-d77fe980-859f-11ea-934a-1abc680e1621.png)
