### ISSUE TITLE
[BX][RN] - Definição de caso.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#145]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu acesse a tela de criação de notificação.
Quando eu criar uma notificação
E clicar em CASO SUSPEITO
OU clicar em CONTATO DE CASO SUSPEITO OU CONFIRMADO

Problemas
a) Deixar o "F" da palavra febre em maiúsculo.
b) Incluir a palavra febre no segundo tipo de caso.

Resultado esperado
Ajustes e inclusão do sintoma "Febre".

![exemplo ficha](https://user-images.githubusercontent.com/17462759/79879030-8c5daf00-83c4-11ea-8a56-f906b82e74d0.png)
![caso A](https://user-images.githubusercontent.com/17462759/79879036-8d8edc00-83c4-11ea-8035-e51e01368e91.png)
![caso B](https://user-images.githubusercontent.com/17462759/79879043-8e277280-83c4-11ea-8be1-d37f42cad8b6.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 23/04/2020 no ambiente app.notificasaude.com.b

![image](https://user-images.githubusercontent.com/15328510/80157957-bddda280-859d-11ea-8b48-46fc19c06fd6.png)
