### ISSUE TITLE
[MD][RN] - Máscara do tipo de documento.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#147]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu selecione CPF no campo Tipo de documento	
Quando eu informar mais de 11 caracteres no campo Número do documento
Então está sendo permitido.

Problema
Está sendo permitido informar mais de 11 caracteres no campo Número do documento, quando o tipo de documento selecionado é CPF.

Resultado esperado
Não permitir informar mais de 11 caracteres no campo Número do documento, quando for selecionado CPF como tipo de documento.

![img1](https://user-images.githubusercontent.com/17462759/79881209-4f46ec00-83c7-11ea-97be-7bb07128b40d.png)

**Comment by nasouza2** [comment]
OBS: Incluir a validação para os demais tipos de documentos também.

**Comment by AndressaKarla** [comment]
Testes para CPF concluídos com sucesso no dia 23/04/2020 no ambiente https://app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80160481-1fa10b00-85a4-11ea-99c9-bcd7b4cb1ca0.png)

> OBS: Incluir a validação para os demais tipos de documentos também.

Já para as outras opções, se eu não me engano, há a possibilidade de possuírem letras e números, então não teria um padrão para serem validados
