### ISSUE TITLE
[MD][RN] Está gravando a data errada da notificação GMT

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#149]
## Bug Report

**AMBIENTE**
https://covid19-db1-frontend.herokuapp.com/

**REPRODUÇÃO**
Dado que eu tenha criado uma notificação.
Quando visualizar ela na listagem
OU na tela de evolução.

**PROBLEMA**
A data/hora gravada está 3 horas a frente.
Provavelmente problema de GMT no Front

**RESULTADO ESPERADO**
Deveria salvar com a data/hora correta baseado no GMT correto.

**Comment by ftathiago** [comment]
A issue #152 corrige no back o tratamento do UTC. Por favor, @bobycachoeira , pode fazer uma revalidação para saber se houve impacto nesta issue?

**Comment by bobycachoeira** [comment]
@ftathiago aparentemente continua gravando errado.

Duvidas a disposição.

**Comment by bobycachoeira** [comment]
Essa notificação foi criada as 17:13

![image](https://user-images.githubusercontent.com/6394762/79910434-1b82bb00-83f5-11ea-8188-d2bfb28dd099.png)

**Comment by wildeee** [comment]
@ftathiago essa tarefa é de back, correto?
Mudei a label dela.

**Comment by ftathiago** [comment]
@wildeee já tinha corrigido antes no back. Essa tarefa é pro front conferir se tá tudo certo na exibição da data/hora

**Comment by wildeee** [comment]
Então vou verificar assim que tivermos nosso back de volta

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
