### ISSUE TITLE
[MD][RN] - Validação do telefone.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#150]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E não informe nenhum telefone
E clique no botão Enviar
Quando eu preencher um dos telefones
Então os outros campos continuarão apresentando a mensagem de que são obrigatórios.

Problema
Campos de telefones continuam sendo apresentados como obrigatórios, mesmo informado um deles.

Resultado esperado
Remover mensagem de obrigatoriedade, caso um dos telefones seja informado.

![img1](https://user-images.githubusercontent.com/17462759/79888555-3c3a1900-83d3-11ea-9502-23cbf15ee1ac.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
![image](https://user-images.githubusercontent.com/6394762/81354735-c7d5ca00-90a2-11ea-9653-a53ea22a1672.png)

**Comment by nasouza2** [comment]
Ok, aprovado.
