### ISSUE TITLE
[MD][RN] - Validação do nome do caso suspeito ou confirmado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#151]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu marcar o combobox CONTATO DE CASO SUSPEITO OU CONFIRMADO
E passar pelo campo Nome do caso suspeito ou confirmado que teve contato
Então não é apresentada a mensagem de que o campo é obrigatório.

Problema
Campo "Nome do caso suspeito ou confirmado que teve contato" não apresentando mensagem de obrigatório.

Resultado esperado
Caso o campo não tenha sido preenchido, apresentar mensagem de que o campo é obrigatório, assim que é tirado o foco dele (isso já acontece em outros campos do sistema).

OBS: Não consegui anexar o vídeo do processo; se tiver dúvida para reproduzir, favor me contatar.

**Comment by AndressaKarla** [comment]
Não existe mais o campo "Nome do caso suspeito ou confirmado que teve contato" na seção "2. DEFINIÇÃO DO CASO", devido a issue https://github.com/db1group/contra-covid19/issues/164
 
![image](https://user-images.githubusercontent.com/15328510/81026288-fc057c80-8e4f-11ea-9307-191b0fe25b7f.png)

Então essa issue foi fechada e movida para Done
