### ISSUE TITLE
[BX][LT] - Limpar o campo "Nome do caso suspeito ou confirmado que teve contato" caso troque de opção

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#153]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu marcar a opção CONTATO DE CASO SUSPEITO OU CONFIRMADO
E informar um valor no campo "Nome do caso suspeito ou confirmado que teve contato"
Quando eu troco de opção para CASO SUSPEITO
Então não está limpando o valor informado no campo "Nome do caso suspeito ou confirmado que teve contato"

Problema
Campo "Nome do caso suspeito ou confirmado que teve contato" não está limpando o valor quando há troca de opção.

Resultado esperado
Se o campo é preenchido e depois é escolhido outra opção que desabilita o campo, é interessante limpar as informações preenchidas.

**Comment by AndressaKarla** [comment]
Não existe mais o campo "Nome do caso suspeito ou confirmado que teve contato" na seção "2. DEFINIÇÃO DO CASO", devido a issue https://github.com/db1group/contra-covid19/issues/164
 
![image](https://user-images.githubusercontent.com/15328510/81026288-fc057c80-8e4f-11ea-9307-191b0fe25b7f.png)

Então essa issue foi fechada e movida para Done
