### ISSUE TITLE
[BX][RN]- Validação dos caracteres informados nos campos para "Nome"

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#154]
**Ambiente**
https://covid19-db1-frontend.herokuapp.com/

**Reprodução**
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu informar menos de 3 caracteres
E/OU informar caracteres especiais 
E/OU informar números 
nos campos: "Nome do Notificador", "Nome do Caso suspeito ou confirmado que teve contato", "Nome completo", "Nome da mãe", "Nome da pessoa suspeita"

**Problema**
Campos descritos estão permitindo informar **menos de 3 caracteres, números e caracteres especiais**.

**Resultado esperado**
Permitir somente letras e validar o número de caracteres mínimo a ser preenchido, assim que é tirado o foco dele (isso já acontece em outros campos do sistema).

OBS: Essa regra não está definida nos Requisitos, se tiver dúvida para reproduzir, favor me contatar.

**Comment by AndressaKarla** [comment]
Vou mover essa issue para "Done" pois o problema descrito será tratado na issue https://github.com/db1group/contra-covid19/issues/389
