### ISSUE TITLE
[MD][RN] - Não limpa os exames selecionados quando escolhido NÃO.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#156]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu marcar o radiobutton Sim da parte de REALIZOU EXAME DE IMAGEM
E selecionar alguns exames
E marcar o radiobutton Não
Então os exames selecionados anteriormente permanecem selecionados.

Problema
Não limpa os exames selecionados, quando há troca entre os radiobuttons REALIZOU EXAME DE IMAGEM.

Resultado esperado
Limpar os exames selecionados, quando marcar o radiobutton Não.

![img1](https://user-images.githubusercontent.com/17462759/79893806-f41ef480-83da-11ea-877a-68d83596f56d.png)

**Comment by AndressaKarla** [comment]
@nasouza2 parece que o PR associado a essa issue ainda não foi publicada no ambiente de QA. Talvez vc teria que pedir aos devs para resolverem o conflito primeiro, para depois então publicar no ambiente :)

![image](https://user-images.githubusercontent.com/15328510/81240080-d5288100-8fdc-11ea-9fc2-4129ab95a432.png)

**Comment by nasouza2** [comment]
Retornando o card para "Disponível para teste", visto que o PR não foi aprovado ainda.

**Comment by nasouza2** [comment]
Ok, ajustado.
