### ISSUE TITLE
[MD][RN] - Campo REALIZOU EXAME DE IMAGEM continua apresentado como não preenchido, mesmo já selecionado o exame.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#157]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu marcar o radiobutton Sim da parte de REALIZOU EXAME DE IMAGEM
E selecionar alguns exames
Então continua sendo apresentada a mensagem a seguir, mesmo já tendo selecionado o exame: "Pelo menos um Raio ou Tomografia do tórax deve ser selecionado".

Problema
Campo REALIZOU EXAME DE IMAGEM continua apresentado como não preenchido, mesmo já selecionando o exame.

Resultado esperado
Validar corretamente a seleção de exames, tirando a mensagem quando o exame já tiver selecionado.

![img1](https://user-images.githubusercontent.com/17462759/79894958-92f82080-83dc-11ea-986d-2432f9bdc90a.png)

**Comment by bobycachoeira** [comment]
@FabioBezerra  continua acontecendo.
Ao marcar a opção "Sim" de realizou exame e marcar uma opção abaixo continua vermelho.

Obs.: Marcar "Sim" marcar uma opção e marcar "Não" e depois "Sim" novamente, ele fica certo.

**Comment by nasouza2** [comment]
Ok, validado. Homologado no ambiente de produção.
