### ISSUE TITLE
[BX][RN] - Permite selecionar puérpera mesmo o sexo sendo masculino.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#158]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu selecionar o sexo masculino
Então está sendo permitido selecionar Puérpera até 45 dias de parto.

Problema
Permite selecionar Puérpera até 45 dias de parto mesmo o sexo sendo masculino.

Resultado esperado
Caso o sexo selecionado seja Masculino, bloquear a opção "Puérpera até 45 dias de parto.".
![img1](https://user-images.githubusercontent.com/17462759/79897528-4282c200-83e0-11ea-8f2c-19cbbc6712ab.png)
![img2](https://user-images.githubusercontent.com/17462759/79897533-431b5880-83e0-11ea-852a-09aaf1dd2cc1.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 09/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![XAQwFrqdVW](https://user-images.githubusercontent.com/15328510/81489477-3f932880-924c-11ea-97f4-7cef50d5bdfe.gif)
