### ISSUE TITLE
Colocar Hotjar no front

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#160]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
O seguinte script deve ser carregado apenas no ambiente de **PRODUÇÃO**

```
<!-- Hotjar Tracking Code for My site -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hjfunction(){(h.hj.q=h.hj.q[]).push(arguments)};
        h._hjSettings={hjid:1770246,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-%27,%27.js?sv=%27);
</script>
```

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020

![image](https://user-images.githubusercontent.com/15328510/80314749-ae42a180-87c9-11ea-8c80-d126ddc3e2c8.png)
