### ISSUE TITLE
[MD][RN] - Não traz o telefone informado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#161]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja tenha incluído uma notificação e informado o telefone
Quando acessar a tela de Consultar Notificação
Então não está sendo apresentado o telefone informado.

Problema
Não apresenta o telefone residencial informado na inclusão da notificação.

Resultado esperado
Apresentar o telefone informado no cadastro.
OBS: No anexo img3.png, o telefone do paciente Fernando Gustavo também não foi apresentado.

![img2](https://user-images.githubusercontent.com/17462759/79899436-2f252600-83e3-11ea-8c1e-c03a20a560d4.png)
![img3](https://user-images.githubusercontent.com/17462759/79899441-2fbdbc80-83e3-11ea-95d7-5eb793df605c.png)
![img1](https://user-images.githubusercontent.com/17462759/79899442-30565300-83e3-11ea-825d-e6c226b067ef.png)

**Comment by ftathiago** [comment]
api/notificacoes/consulta está devolvendo o json

```js
{
  "count": 3,
  "data": [
    {
      "id": "ded90e3e-eeb9-421c-a274-33e9bde59a31",
      "nome": "MACIA SILVANCAO FERREEIRA",
      "documento": "08918584903",
      "dataNotificacao": "2020-04-21T19:03:00.000Z",
      "telefone": "88888888888",
      "situacao": "Isolamento domiciliar"
    },
    {
      "id": "378a2578-4f21-48fc-9c75-939f5f1dc12d",
      "nome": "MACIA SILVANCAO FERREEIRA",
      "documento": "08918584903",
      "dataNotificacao": "2020-04-21T19:52:00.000Z",
      "telefone": "88888888888",
      "situacao": "Isolamento domiciliar"
    },
    {
      "id": "ef8b1a33-3999-480b-9e11-5514bd2e5beb",
      "nome": "MACIA SILVANCAO FERREEIRA",
      "documento": "08918584903",
      "dataNotificacao": "2020-04-21T18:52:00.000Z",
      "telefone": "88888888888",
      "situacao": "Isolamento domiciliar"
    }
  ]
}
```

**Comment by AndressaKarla** [comment]
Não existe mais a coluna "Telefone" na listagem de notificações
![image](https://user-images.githubusercontent.com/15328510/81022234-78de2980-8e43-11ea-98e7-e37c6e5172c9.png)
