### ISSUE TITLE
[GR][DC] - Campo para informar o nome do contato suspeito/confirmado duplicado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#164]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Então é apresentado o campo "Nome do caso suspeito ou confirmado que teve contato" na sessão 2. DEFINIÇÃO DO CASO
E também é apresentado o campo "Nome da pessoa suspeita" na sessão 10. CONTATO COM SUSPEITO OU CONFIRMADO.

Problema
Campo duplicado para informar o nome do contato suspeito/confirmado. 

Resultado esperado
Conforme alinhado com o Rogerio, remover o campo "Nome do caso suspeito ou confirmado que teve contato" da sessão 2. DEFINIÇÃO DO CASO.

![img1](https://user-images.githubusercontent.com/17462759/79900234-4fa1b000-83e4-11ea-8e38-bd20953c6d78.png)
![img2](https://user-images.githubusercontent.com/17462759/79900238-503a4680-83e4-11ea-9d91-efceb7f266f6.png)

**Comment by ftathiago** [comment]
@altitdb, acredito que isso vá impactar também na issue #89 tem como vc dar uma olhada?

**Comment by carloshabarbosa** [comment]
@rgsouzabr Qual campo devemos manter?

**Comment by CristianeBorges05** [comment]
Os dois campos ainda constam no sistema. 

Resultado esperado
Conforme alinhado com o Rogerio, remover o campo "Nome do caso suspeito ou confirmado que teve contato" da sessão 2. DEFINIÇÃO DO CASO.

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso:

![image](https://user-images.githubusercontent.com/6394762/80269991-f4451b80-868a-11ea-9bd9-05275bc95971.png)
