### ISSUE TITLE
[GR][RN] "404 - Not Found" ao atualizar a página de listagem, cadastro de notificações e evolução dos pacientes

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#165]
============================================
PROBLEMA 1

[AMBIENTE] 
https://covid19-db1-frontend.herokuapp.com/
 
[REPRODUÇÃO] 
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações” e de "Evolução dos Pacientes"
E eu clique na opção “CONSULTAR NOTIFICAÇÕES” 
Ou eu clique na opção "NOVA NOTIFICAÇÃO"

Quando eu clicar na opção do navegador para atualizar a página 
Ou eu clicar em F5

[PROBLEMA] 
Está sendo apresentado indevidamente "404 - Not Found" ao atualizar a página de listagem e cadastro de notificações

[RESULTADO ESPERADO]
Deveria atualizar a página normalmente
 
Evidência em anexo.
![ezgif-3-86bcbcb83452](https://user-images.githubusercontent.com/15328510/79901599-706b0500-83e6-11ea-9df3-ffc6456a04fb.gif)

============================================
PROBLEMA 2

[AMBIENTE] 
https://covid19-db1-frontend.herokuapp.com/
 
[REPRODUÇÃO] 
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações” e de "Evolução dos Pacientes"
E eu clique na opção “CONSULTAR NOTIFICAÇÕES” 
E eu clique na opção "EVOLUÇÃO"

Quando eu clicar na opção do navegador para atualizar a página 
Ou eu clicar em F5

[PROBLEMA] 
Está sendo apresentado indevidamente "404 - Not Found" ao atualizar a página de "Evolução dos Pacientes"

[RESULTADO ESPERADO]
Deveria atualizar a página normalmente
 
Evidência em anexo.
![ezgif-3-0a99b1dc3c5f](https://user-images.githubusercontent.com/15328510/79902396-d015e000-83e7-11ea-9566-ea8110e9cab6.gif)

============================================

**Comment by wildeee** [comment]
Isso é uma configuração de nginx. Conforme alinhado com @altitdb, vamos arrumar isso quando tivermos o ambiente de produção OK, para não corrermos o risco de precisar alterar uma vez a mais, sem necessidade.

**Comment by wildeee** [comment]
Aparentemente, já foi corrido há algum tempo, pelo @maykon

**Comment by CristianeBorges05** [comment]
VALIDADO QA OK
![NOT FOUND 404](https://user-images.githubusercontent.com/63747448/80552021-bce0b280-899b-11ea-8bcb-4bc552456d5c.gif)
