### ISSUE TITLE
[BX][RN] Seção 11, campo não está claro que é obrigatório

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#170]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E esteja na Seção "11.Outras informações"

Problema
A pergunta "Recebeu vacina contra Gripe nos últimos doze meses?" não está com asterisco de obrigatoriedade. Mas na hora de realizar o envio da notificação o sistema obriga escolher uma opção. Acho que dificulta para o usuário encontrar qual informação ficou faltando, pois só após o enviar é que aparece os campos como obrigatórios.

Resultado esperado
Exibir asterisco de obrigatoriedade na pergunta.

![image](https://user-images.githubusercontent.com/63747448/79908046-f7bd7600-83f0-11ea-9793-e74475198cc5.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 23/04/2020 no ambiente https://app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80156607-bd8fd800-859a-11ea-9acf-5ac0c2cd9f42.png)
