### ISSUE TITLE
[MD][RN] Back - Não está com tratamento de limite máximo de caracteres para os campos do Objeto "Suspeito" do JSON

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#174]
## Bug Report

**Comportamento atual**
 Back - Não está com tratamento de limite máximo de caracteres para os campos do Objeto "Suspeito" do JSON

**Comportamento/código esperado**
 Back - Ter tratamento de limite máximo de caracteres para os campos do Objeto "Suspeito" do JSON, semelhante ao documento de modelagem "[Notificacao.pdf](https://github.com/db1group/contra-covid19/files/4512392/Notificacao.pdf)" em anexo

**Tarefas**
* [ ] - Validar (criando/alterando schema) o objeto request
* [ ] - Alterar o mapeamento para que o respose retorne igual ao request
* [ ] - Conferir se as informações de tamanho/obrigatoriedade do campo estão iguais aos do modelo
* [ ] - Criar as migrations, se necessárias
* [ ] - Alterar o modelo, se necessário, aplicando validações se forem possíveis.

**Comment by AndressaKarla** [comment]
Essa issue precisa ser testada utilizando postman + base de dados
Quem for pegar para testar pode trocar uma ideia comigo @AndressaKarla ou com o @bobycachoeira

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
