### ISSUE TITLE
[CR][RN] Está permitindo criar mais de uma notificação com os mesmos dados (Falta definir resultado esperado desse requisito)

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#175]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E eu cadastrei uma Notificação com os dados da Maria
E acessei novamente o sistema e cadastrei outra notificação com os mesmos dados da Maria da notificação anterior
Quando eu acionar o botão "Enviar"
Então não deverá ser permitido realizar esta ação

Problema
Está permitindo criar mais de uma notificação para o mesmo paciente. Atualmente já existe uma consulta anterior, mas segundo o Rogério, os usuários vão direto no cadastro, sem executar consultas prévias.

Resultado esperado
Não permitir enviar uma notificação que já possua com (Tipo de documento + Número de documentos) iguais como status da notificação "ABERTA". Isto é, não pode lançar uma notificação para um paciente que possua uma aberta.

Chamar o Roger para pensarmos na solução técnica.

![image](https://user-images.githubusercontent.com/63747448/79909945-3274dd80-83f4-11ea-98c8-458d3a164910.png)

**Comment by nasouza2** [comment]
Aguardando retorno do Rogerio, sobre a evolução de óbito.

**Comment by nasouza2** [comment]
Ok, validado. Validação será feita considerando o tipo de documento + número do documento.
