### ISSUE TITLE
Campo Situação não atualiza quando alterado de UTI para leito comum.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#176]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E cadastre um paciente com tipo de hospitalização "Encaminhado para INTERNAMENTO EM LEITO DE UTI"
Quando eu lançar uma evolução alterando o local de isolamento para "Hospitalizado leito comum"
Então na tela de Consultar Notificação, a coluna Situação não é atualizada; continua mostrando "UTI" ao invés de apresentar "Hospitalização".

Problema
Campo situação não atualiza quando alterado de UTI para leito comum.

Resultado esperado
Quando o paciente tiver evolução de leito de UTI para leito comum, o campo Situação deve apresentar Hospitalização.
[dados.pdf](https://github.com/db1group/contra-covid19/files/4512544/dados.pdf)

**Comment by ftathiago** [comment]
@nasouza2 , eu verifiquei que a regra escrita no código consulta a situação no momento do cadastro da notificação covid NotificacaoCovid19.situacaoNoMomentoDaNotificacao. 

Quando eu incluo uma nova evolução, que dado deve ser atualizado?

**Comment by carloshabarbosa** [comment]
O campo situação da listagem de notificações foi removido, conforme a issue: [#223 ](https://github.com/db1group/contra-covid19/issues/223).
