### ISSUE TITLE
[BX][RN] - Corrigir palavra "comun".

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#177]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Consulta de Notificação
Quando eu possuir um paciente com internamento em leito comum
Então no campo Situação é apresentado "comun".

Problema
Correção ortográfica da palavra "comum".

Resultado esperado
Correção de "comun" para "comum".

![img1](https://user-images.githubusercontent.com/17462759/79912744-e4aea400-83f8-11ea-8f8b-7559d3c3dff1.png)

**Comment by AndressaKarla** [comment]
Não teria como validar esse caso, pois a coluna situação deixou de existir após ajuste nesse outro [bug](https://github.com/db1group/contra-covid19/issues/223)
