### ISSUE TITLE
[BX][RN] Campo "Raça/cor" não está apresentando comportamento adequado como campo de preenchimento obrigatório

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#178]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Cenário 1
Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu não preencher o campo Raça/cor

Problema
O sistema não está validando o campo Raça/Cor como obrigatório.

Resultado esperado
O campo Raça/cor deve vir vazio e ser validado como campo obrigatório conforme padrão dos outros campos obrigatórios.

Cenário 2
Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E preencha todas as informações obrigatórias
E clique no botão Enviar
Quando a notificação for enviada
E a tela de cadastro de notificações for atualizada para preencher um novo cadastro

Problema
O sistema não está validando o campo Raça/Cor como obrigatório.

Resultado esperado
O campo Raça/cor deve vir vazio e ser validado como campo obrigatório conforme padrão dos outros campos obrigatórios.

![Campo Raça](https://user-images.githubusercontent.com/63747448/79912656-bdf06d80-83f8-11ea-9ccf-b6263dea77ce.gif)
gnorado"

**Comment by brendaraylla** [comment]
Atualmente esse campo vem com default "Ignorado". Verificar se há necessidade de mudá-lo para vazio e ser validado como campo obrigatório

**Comment by nasouza2** [comment]
O Rogerio vai verificar qual é o comportamento no sistema do estado.

Aguardar retorno.

**Comment by AndressaKarla** [comment]
> O Rogerio vai verificar qual é o comportamento no sistema do estado.
> 
> Aguardar retorno.

@rgsouzabr vc poderia verificar depois o comentário feito pela @nasouza2 sobre qual seria o comportamento no sistema do estado do campo "Raça/cor" já vir preenchido com valor padrão ou ser obrigatório informar?

**Comment by rgsouzabr** [comment]
O sistema do estado inicia o cadastro com "selecione". Isto é, o usuário precisa informar mesmo que for "Ignorado".

**Comment by AndressaKarla** [comment]
> O sistema do estado inicia o cadastro com "selecione". Isto é, o usuário precisa informar mesmo que for "Ignorado".

@nasouza2 vc poderia verificar depois o comentário do @rgsouzabr ?

**Comment by nasouza2** [comment]
@brendaraylla Favor ajustar:
- Trazer o campo Raça/Cor com o default "em branco".
- Tornar o campo obrigatório.
- A opção "Ignorado" deve ser mantida entre as opções do campo.

Dúvidas, estou a disposição.
