### ISSUE TITLE
Está sendo apresentado indevidamente mensagem de "Profissão não encontrada" ao pesquisar sem acentuação (Ex.: "Medico") uma profissão que tenha acentuação (Ex.: "Médico")

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#180]
[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu esteja na tela de "Notificações Covid-19"
E eu clique na opção “NOVA NOTIFICAÇÃO”
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “1. IDENTIFICAÇÃO DO NOTIFICANTE” 

Quando eu pesquisar sem acentuação (Ex.: "Medico") no campo “Profissão do notificador” uma profissão que tenha acentuação (Ex.: "Médico")

[PROBLEMA]
Está sendo apresentado indevidamente mensagem de "Profissão não encontrada" ao pesquisar sem acentuação (Ex.: "Medico") uma profissão que tenha acentuação (Ex.: "Médico")

![image](https://user-images.githubusercontent.com/15328510/79914328-76b7ac00-83fb-11ea-994c-2e0a38cb32d6.png)

![image](https://user-images.githubusercontent.com/15328510/79914446-b2527600-83fb-11ea-93f5-53dd07391137.png)

[RESULTADO ESPERADO]
Ao pesquisar sem acentuação (Ex.: "Medico") no campo “Profissão do notificador” uma profissão que tenha acentuação (Ex.: "Médico"), deveria ser apresentado a profissão com acentuação (Ex.: "Médico") como sugestão no campo corretamente

**Comment by ftathiago** [comment]
Foi feito um pedido para retirar acentos e tornar maiúsculas as letras dos nome, nome suspeito. Isso deverá ser feito para todos os campos texto?

**Comment by wildeee** [comment]
@ftathiago alterei para o label Back, pois independente da resposta da @AndressaKarla, essa alteração não será no front

**Comment by AndressaKarla** [comment]
> Foi feito um pedido para retirar acentos e tornar maiúsculas as letras dos nome, nome suspeito. Isso deverá ser feito para todos os campos texto?
> 
> Se for o caso, por favor, altere esta issue com a TAG back @AndressaKarla

@ftathiago eu acho que para nome de profissão não faria sentido retirar a acentuação. Mas ao pesquisar sem acentuação (Ex.: "Medico") no campo “Profissão do notificador” uma profissão que tenha acentuação (Ex.: "Médico"), deveria ser apresentado a profissão com acentuação (Ex.: "Médico") como sugestão no campo corretamente

**Comment by ftathiago** [comment]
Hmmm não manjo desses paranauês. Talvez o @wildeee saiba se é possível

**Comment by wildeee** [comment]
AHHH, esse filtro é feito no front né?
Tinha esquecido completamente disso, vou voltar a atividade pro front. Quando pegar ela, analiso melhor se é viável fazer isso (possível sempre é, hahaha)
