### ISSUE TITLE
[MD] [RN] Data de início dos sintomas permitindo data futura

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#181]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E esteja na seção "4. Sinais e Sintomas"
Quando eu preencher o campo "Data de início dos sintomas" com uma Data maior que a data atual

Problema
Campo está permitindo informar data maior que a atual

Resultado esperado
Não permitir informar data maior que a atual e exibir mensagem abaixo do campo.
![Data futura Sintomas](https://user-images.githubusercontent.com/63747448/79914987-8b487400-83fc-11ea-9c23-847f3a858af9.gif)
.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 04/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/81021919-b2626500-8e42-11ea-95b7-15a3f5233fe6.png)
