### ISSUE TITLE
Deixa alterar caso confirmado para descartado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#182]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
E selecionar um paciente confirmando
Quando eu informar situação do paciente "DESCARTADO"
Então está sendo permitido.

Problema
Está sendo permitido lançar evolução DESCARTADO para paciente CONFIRMADO.

Resultado esperado
Não permitir lançar evolução DESCARTADO para casos confirmado.

OBS: Verificar também paciente IAN AUGUSTO DA PAZ, CPF 
![9iDS2o2jUZ](https://user-images.githubusercontent.com/17462759/79917643-3e1ad100-8401-11ea-91bf-2fabab63032d.gif)
503.193.859-57.

**Comment by jef-araujo** [comment]
@rgsouzabr 

**CONFIRMADO** não pode atualizar para **DESCARTADO**.
dúvida: **CONFIRMADO** pode atualizar para **SUSPEITO**?

**Comment by rgsouzabr** [comment]
Não pode retornar para SUSPEITO

**Comment by jef-araujo** [comment]
@rgsouzabr  **CONFIRMADO** não pode atualizar para **CONFIRMADO**  certo?

**Comment by jef-araujo** [comment]
implementado para não permitir evolução para: **DESCARTADO**, **SUSPEITO**, **CONFIRMADO**, quando a notificação já estiver com status **CONFIRMADO**.

**Comment by nasouza2** [comment]
Situação ainda ocorre; aguardando retorno do Jefferson.

**Comment by nasouza2** [comment]
Ok, validadas as seguintes condições:
- De CONFIRMADO retornando para SUSPEITO.
- De CONFIRMADO alterando para DESCARTADO.
- De CONFIRMADO alterando para CONFIRMADO.

Em todos, houve o bloqueio correto, porém ainda está sendo permitido alterar de CONFIRMADO para ENCERRADO; isso está sendo visto pela issue #291 .
