### ISSUE TITLE
Não está funcionando a ordenação na tela de consulta

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#184]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Consultar Notificações
Quando eu clicar em cima da label da coluna
Então o sistema deveria ordenar os registros

Problema
Não está ordenando os registros de notificação na tela de consulta.

Resultado esperado
Ordenar os registros.

**Comment by AndressaKarla** [comment]
@wildeee Aparentemente problema ainda ocorre


![ezgif-6-9b0984af5658](https://user-images.githubusercontent.com/15328510/80165550-0d2dce00-85b2-11ea-9155-a47f2f0fc388.gif)

**Comment by bobycachoeira** [comment]
@carloshabarbosa ao tenatr ordenar por UNIDADE NOTIFICADORA, ou por STATUS está dando erro.
Provavelmente de Back, o retorno do back é um 500 com:
"{"error":"Cannot read property 'startsWith' of undefined","stack":null}"

@ftathiago provavelmente isso é back.
