### ISSUE TITLE
Não avisa o usuário que o token expirou

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#185]
## Bug Report

**Ambiente**
https://covid19-db1-frontend.herokuapp.com/

**REPRODUÇÃO**
Dado que eu esteja logado a muito tempo(não sei o tempo que expira o token)
Quando for criar uma ficha.

**PROBLEMA**
Não salva porque campos obrigatórios não estão preenchidos, e estes vem da API.
Ex.:UF, e unidade.

**RESULTADO ESPERADO**
Deveria avisar o usuário do token expirado e encaminhar a tela de login.
OU então dar um refresh token.

Obs.: Isso acaba fazendo perder tempo de trabalho e é dificil de saber qual é o real erro.

**Comment by AndressaKarla** [comment]
Acessei o sistema em um outro navegador, e deixei parado por enquanto. Quando expirar o token (não sei o tempo que está configurado), eu acesso novamente para verificar. Enquanto isso esse card ficará "Em teste"

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 24/04/2020 no ambiente http://app.notificasaude.com.br/

![ezgif-6-c9c510c7fd12](https://user-images.githubusercontent.com/15328510/80213770-1057a700-8610-11ea-9dc6-667abedd6706.gif)
