### ISSUE TITLE
Mensagem de validação de data futura com termos tecnicos

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#186]
**Ambiente**
https://covid19-db1-frontend.herokuapp.com/

**REPRODUÇÃO**
Dado que eu esteja na tela de inserção de evolução.
Quando informar uma data e hora futura.
E Clicar para incluir/atualizar.

**PROBLEMA**
É apresentada a mensagem:

> Validation error: A evolução não pode possuir data futura Wed Apr 22 2020 22:22:00 GMT+0000 (Coordinated Universal Time)]
conforme imagem
![image](https://user-images.githubusercontent.com/6394762/79918848-9eab0d80-8403-11ea-932f-c6d4534471ed.png)

**RESULTADO ESPERADO**
Deveria apresentar uma mensagem mais amigável sem termos técnicos.
poderia ser apenas parte da mensagem:

> ex.: A evolução não pode possuir data futura.

Obs.: Essa mensagem é a retornada pelo Back.

**Comment by ftathiago** [comment]
Não consegui fazer com que o texto "Validation error" seja retirado ou traduzido.
@maykon  sabe como fazer isso?

Talvez o @wildeee possa retirar isso no front.
