### ISSUE TITLE
Campo CPF considerando caracteres especiais.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#188]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de notificação
Quando eu informar o CPF com os caracteres especiais
Então é apresentada a mensagem: "O campo deve possuir 11 caracteres.".

Problema
Campo Número do documento considerando os carateres especiais informados, quando o tipo de documento é CPF. Se tirar os caracteres, o campo é validado corretamente.

Resultado esperado
Desconsiderar os caracteres especiais informados.

![img1](https://user-images.githubusercontent.com/17462759/79919828-7f14e480-8405-11ea-9f93-a553a22f09ef.png)
![img2](https://user-images.githubusercontent.com/17462759/79919831-7fad7b00-8405-11ea-9889-42e471cc5fef.png)

**Comment by wildeee** [comment]
PR disponível pra merge.
Foi uma alteração relativamente grande, então peço que teste bem a parte de tipo de documento, número do documento, classificação da pessoa (indígena, outros, etc.), obrigatoriedade dos campos, e modo de visualização.

**Comment by CristianeBorges05** [comment]
@wildeee  @nasouza2 
Nati se vc quiser dar uma validada também. Pois acredito que a solução da máscara ficou ok, mas achei estranho o comportamento ao alterar o tipo de doc, onde não limpa o preenchimento do campo, para opções diferentes de CPF.
Acho interessante mais um parecer rs
![CPF](https://user-images.githubusercontent.com/63747448/81128637-1e62cd00-8f18-11ea-86c9-970af0d1dab6.gif)

**Comment by wildeee** [comment]
Como preferirem, mudar esse comportamento é fácil.

**Comment by nasouza2** [comment]
@CristianeBorges05 e @wildeee 
Oi pessoal, concordo com a Cris.
Quando alterar o tipo de documento, então limpa o campo "Número do documento", caso esse já foi informado. Isso vai evitar informar número de documento com a máscara incorreta.

@wildeee  dá para arrumar nesse card ou prefere que abra outro?

**Comment by wildeee** [comment]
@nasouza2 Posso ajustar nesse mesmo, sem problema.

**Comment by nasouza2** [comment]
Ok, validado.
