### ISSUE TITLE
[BX][LT] Limpar o campo  "Número do documento" caso troque a opção no "Tipo de Documento"

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#189]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E/OU esteja na Seção "3. IDENTIFICAÇÃO DO PACIENTE"
Quando eu  selecionar um "Tipo de documento" 
E preencher o campo "Número do documento"
Quando eu trocar o "Tipo de documento" por outra opção

Problema
Então não está limpando o valor informado no campo "Número do documento"

Resultado esperado
Se o campo é preenchido e depois é escolhido outra opção, é interessante limpar as informações preenchidas.
![Tipo de Documento_Limpar campo](https://user-images.githubusercontent.com/63747448/79920352-4f1a1100-8406-11ea-8ad9-5b3e894e6c54.gif)

**Comment by brendaraylla** [comment]
Aparentemente já está corrigido

**Comment by nasouza2** [comment]
Já foi corrigido, provavelmente pela issue https://github.com/db1group/contra-covid19/issues/188.
