### ISSUE TITLE
Centralizar mensagem.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#190]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Cadastro de notificação
Quando eu preencher os campos obrigatórios do cadastro
E clicar em Enviar
Então é apresentada a mensagem: "Notificação enviada com sucesso" alinhada a esquerda.

Problema
Mensagem "Notificação enviada com sucesso" alinhada a esquerda.

Resultado esperado
Centralizar a mensagem, assim não sobra um espaço grande a direita.
![img1](https://user-images.githubusercontent.com/17462759/79921406-81c50900-8408-11ea-9191-e5bd1b6a429c.png)

**Comment by nasouza2** [comment]
O mesmo vale para a mensagem: "Evolução cadastrada com sucesso.".
![img2](https://user-images.githubusercontent.com/17462759/79923635-53e1c380-840c-11ea-84d9-820db4e75251.png)

**Comment by nasouza2** [comment]
@brendaraylla Faltou centralizar a msg da evolução. Favor verificar.

**Comment by AndressaKarla** [comment]
@brendaraylla Aparentemente problema ainda ocorre na mensagem após salvar notificação e evolução também. Retornado issue para "todo dev".

![KtR6MXYkLL](https://user-images.githubusercontent.com/15328510/81520913-0924de80-931c-11ea-9a09-0fe4ec0baeb8.gif)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 12/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![vkOy9CvxU9](https://user-images.githubusercontent.com/15328510/81759437-1b795680-949b-11ea-84fa-caa503997d63.gif)

**Comment by nasouza2** [comment]
Casos de testes atualizados.
