### ISSUE TITLE
Campo Data e hora da notificação não apresentado por inteiro.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#193]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu visualizar o campo Data e hora da notificação
Então ele está sendo apresentado cortado, mesmo tendo espaço em tela.

Problema
Campo cortado mesmo tendo espaço em tela.

Resultado esperado
Ajustar o layout para que o campo "Data e hora da notificação" seja apresentado por inteiro.

![img1](https://user-images.githubusercontent.com/17462759/79923942-02860400-840d-11ea-90a1-6de347ed94c0.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 04/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/bf15f761-282b-4ffb-8605-600f6447153c/evolucoes

![image](https://user-images.githubusercontent.com/15328510/81023391-9660c280-8e46-11ea-9f55-ada6f7563675.png)

![image](https://user-images.githubusercontent.com/15328510/81023420-b2646400-8e46-11ea-8d84-d93fbf62339b.png)
