### ISSUE TITLE
Mensagem de validação de notificação de data futura com nome evolução e termos técnicos indevidamente

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#194]
**_OBS.: 2 PROBLEMAS DESCRITOS EM UMA MESMO "BUG REPORT"_**

============================================
**PROBLEMA 1**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações” 
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação” 
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE” 

Quando eu apagar a data e hora preenchidas automaticamente no campo “Data e hora da notificação” 
E eu informar no campo “Data e hora da notificação” uma data posterior a data atual  
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
No trecho da mensagem de validação de notificação de data futura apresentada "A **evolução**..." está com nome evolução indevidamente
![image](https://user-images.githubusercontent.com/15328510/79924157-8fc95880-840d-11ea-9805-4092e982c65f.png)

[RESULTADO ESPERADO]
No trecho da mensagem de validação de notificação de data futura deveria ser "A **notificação** não pode possuir data futura" 

============================================
**PROBLEMA 2**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações” 
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação” 
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE” 

Quando eu apagar a data e hora preenchidas automaticamente no campo “Data e hora da notificação” 
E eu informar no campo “Data e hora da notificação” uma data posterior a data atual  
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Mensagem de validação de notificação de data futura com termos técnicos:
"Validation error: A evolução não pode possuir data futura Wed Apr 22 2020 22:22:00 GMT+0000 (Coordinated Universal Time)]"
![image](https://user-images.githubusercontent.com/15328510/79924271-c606d800-840d-11ea-9908-4095b0cdbf6d.png)

[RESULTADO ESPERADO]
Deveria apresentar uma mensagem mais amigável sem termos técnicos: "A notificação não pode possuir data futura" 

============================================

**Comment by ftathiago** [comment]
Para fins de instrução: Esta mensagem de erro com o texto "Evolução" é porque a validação foi feita para a evolução e AINDA não foi feita para a data-hora da notificação. A correção correta é validar a data da hora de notificação

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80267475-8fcc9100-8677-11ea-95df-7cfa84578975.png)

Evidência de como será o retorno da api. A Stack estará disponível apenas para ambiente de desenvolvimento
