### ISSUE TITLE
Permitindo lançar evolução com data inferior a data da notificação.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#198]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu informar uma data de evolução inferior a data de lançamento da notificação  (dh_notificacao).
Então está sendo permitido.

Problema
Permitindo lançar evolução com data inferior a data da notificação (dh_notificacao).

Resultado esperado
Não permitir lançar evolução com data inferior a data da notificação  (dh_notificacao).

![xKaGjD3HIm](https://user-images.githubusercontent.com/17462759/79925389-a0c79900-8410-11ea-8159-26ade4ddb2d8.gif)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso:

![image](https://user-images.githubusercontent.com/6394762/80269110-31a5ab00-8683-11ea-8ce7-c660d2599786.png)
