### ISSUE TITLE
Não sendo apresentado mensagem de obrigatoriedade para o campo “CEP”

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#199]
[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”
 
Quando eu não informar o campo “CEP” 
E eu tirar o foco do campo “CEP” 
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Não sendo apresentado mensagem de obrigatoriedade para o campo “CEP”

[RESULTADO ESPERADO]
Deveria ser apresentado mensagem de obrigatoriedade para o campo “CEP”

**Comment by wildeee** [comment]
@AndressaKarla Deve mesmo ser obrigatório o CEP? Não coloquei esse campo como obrigatório porque pensei na eventualidade da pessoa não lembrar o CEP

**Comment by AndressaKarla** [comment]
@wildeee talvez poderia colocar uma opção para procurar por estado, cidade ou endereço, quando não soubesse o CEP, e não deixar o campo "CEP" como não obrigatório. Por exemplo, nesse sistema aqui, tem uma lupa com opção para procurar por outros campos quando não se sabe o CEP:

![image](https://user-images.githubusercontent.com/15328510/80049525-7eee1500-84e9-11ea-842f-a90d1486c772.png)

Ou ter um link "Não sei meu CEP" direcionando para o site de CEP dos Correios, etc

**Comment by wildeee** [comment]
Hmmm, legal.
No caso, acho que vamos adotar a segunda opção.
Mas sabe se o CEP vai ser usado pra alguma coisa, pra ser obrigatório? Porque eu achei que a ideia de ter ele ali era só preencher os campos de endereço automaticamente no futuro.

**Comment by AndressaKarla** [comment]
@wildeee é que nos sistemas em geral o "CEP" costuma ser obrigatório, me baseei nisso quando criei esse bug. Mas no caso desse sistema do Covid eu não saberia te dizer onde o "CEP" seria utilizado, qualquer coisa troca uma ideia também com o @rgsouzabr , talvez ele também possa te dar uma sugestão sobre isso :)

**Comment by ftathiago** [comment]
Como até o presente momento o CEP não terá uma importância maior, estou fechando essa issue

**Comment by AndressaKarla** [comment]
> Como até o presente momento o CEP não terá uma importância maior, estou fechando essa issue

Considerando o comentário feito anteriormente pelo @ftathiago essa issue foi movida para "Done"
