### ISSUE TITLE
Permitindo lançar evolução com data inferior a data notificação. 

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#200]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu informar uma data de evolução inferior a data de lançamento da notificação  (dh_notificacao).
Então está sendo permitido.

Problema
Permitindo lançar evolução com data inferior a data da notificação (dh_notificacao).

Resultado esperado
Não permitir lançar evolução com data inferior a data da notificação  (dh_notificacao).

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80171975-250d4e00-85c2-11ea-8c78-3481a4eaa015.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso:

![image](https://user-images.githubusercontent.com/6394762/80269570-513ed280-8687-11ea-9239-841a14b293ff.png)

![image](https://user-images.githubusercontent.com/6394762/80269573-53089600-8687-11ea-8855-2ec82d6e84c3.png)
