### ISSUE TITLE
Deixa alterar caso confirmado para descartado.

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#202]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
E selecionar um paciente confirmando
Quando eu informar situação do paciente "DESCARTADO"
Então está sendo permitido.

Problema
Está sendo permitido lançar evolução DESCARTADO para paciente CONFIRMADO.

Resultado esperado
Não permitir lançar evolução DESCARTADO para casos confirmado.

OBS: Verificar também paciente IAN AUGUSTO DA PAZ, CPF

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80291081-c6aab180-8720-11ea-921b-9afc20ba8c34.png)
Possivelmente corrigido em outra issue

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/a1a10cfb-ac1b-48fd-9b7f-d4733e918d6d/evolucoes

![Osla4QPq5r](https://user-images.githubusercontent.com/15328510/80298171-d7c6e300-875f-11ea-9193-9209c9030a57.gif)
