### ISSUE TITLE
Não sendo apresentado mensagem de "CEP" inválido

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#205]
[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “CEP” uma informação inválida (Ex.: 99999999) 
E eu tirar o foco do campo “CEP” 
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Não sendo apresentado mensagem de "CEP" inválido
![image](https://user-images.githubusercontent.com/15328510/79931105-88f81100-8420-11ea-91ca-fb4a88d3ad77.png)

[RESULTADO ESPERADO]
Deveria apresentar uma mensagem de "CEP" inválido

**Comment by wildeee** [comment]
@AndressaKarla existe alguma forma de validar um CEP? A única validação que me vem à cabeça fazer hoje, é a de quantidade de dígitos, mas dado um CEP com 8 dígitos, não sei dizer se ele é válido ou não.

**Comment by AndressaKarla** [comment]
@wildeee nesse sistema aqui, por exemplo, quando informa um CEP inválido (Ex.: 9999-999), ele retorna essa msg no print abaixo:

![image](https://user-images.githubusercontent.com/15328510/80049741-1a7f8580-84ea-11ea-90fe-6314f548da7c.png)

**Comment by ftathiago** [comment]
@rgsouzabr , a princípio nós não iríamos utilizar base de consulta para CEP. Essa info mudou?

**Comment by ftathiago** [comment]
@AndressaKarla , não existe uma regex ou qualquer outro algoritmo de validação de CEP. A única forma de validar é acessando a base dos correios ou validando a forma (cinco números - três números). Nesse caso, aconselho fechar essa issue

**Comment by AndressaKarla** [comment]
> @AndressaKarla , não existe uma regex ou qualquer outro algoritmo de validação de CEP. A única forma de validar é acessando a base dos correios ou validando a forma (cinco números - três números). Nesse caso, aconselho fechar essa issue

Considerando o comentário feito anteriormente pelo @ftathiago essa issue foi movida para "Done"
