### ISSUE TITLE
Ao informar CEP, campos não estão sendo preenchidos automaticamente

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#206]
**_OBS.:  3 PROBLEMAS DESCRITOS EM UM MESMO "BUG REPORT"_**

============================================
**PROBLEMA 1**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “CEP” um cep sem Endereço e sem Bairro (Ex.: 06900-000, 85670-000) 
E eu tirar o foco do campo “CEP” 

[PROBLEMA]
Ao informar CEP, campos não estão sendo preenchidos automaticamente

[RESULTADO ESPERADO]
Então os campos abaixo devem ser preenchidos automaticamente: 
- “UF” 
- “Município" 

============================================
**PROBLEMA 2**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “CEP” um cep sem Endereço e com Bairro (Ex.: 06930-000) 
E eu tirar o foco do campo “CEP” 

[PROBLEMA]
Ao informar CEP, campos não estão sendo preenchidos automaticamente

[RESULTADO ESPERADO]
Então os campos abaixo devem ser preenchidos automaticamente: 
- “Bairro” 
- “UF” 
- “Município" 

============================================
**PROBLEMA 3**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “CEP” um cep com Endereço e com Bairro (Ex.: 87020-260) 
E eu tirar o foco do campo “CEP” 

[PROBLEMA]
Ao informar CEP, campos não estão sendo preenchidos automaticamente

[RESULTADO ESPERADO]

Então os campos abaixo devem ser preenchidos automaticamente: 
- “Endereço”  
- “Bairro” 
- “UF” 
- “Município" 

============================================

**Comment by ftathiago** [comment]
@AndressaKarla , essa alteração será feita? 
ACHO que não dá pra apagar issue, mas tem um label "Wont fix".
Acho que daí pode tirar todos os labels e deixar só esse. :blush:
