### ISSUE TITLE
Não está sendo apresentado o nome do campo na mensagem ao salvar notificação com "Telefone residencial", "Telefone celular" e "Telefone contato" com menos dígitos que o permitido

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#207]
**_OBS.:  3 PROBLEMAS DESCRITOS EM UM MESMO "BUG REPORT"_**

============================================
**PROBLEMA 1**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “Telefone residencial” um telefone com menos de 10 dígitos (sem contar as máscaras) 
E eu tirar o foco do campo "Telefone residencial” 
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Não está sendo apresentado o nome do campo na mensagem ao salvar notificação com "Telefone residencial" com menos dígitos que o permitido:

"suspeito.telefoneResidencial" deve conter pelo menos 10 caracteres

![image](https://user-images.githubusercontent.com/15328510/81027488-4ee13300-8e54-11ea-978d-1ebc5de6d92f.png)

[RESULTADO ESPERADO]
Deveria ser apresentado o nome do campo na mensagem ao salvar notificação com "Telefone residencial" com menos dígitos que o permitido:

"Telefone residencial" deve conter pelo menos 10 caracteres

============================================
**PROBLEMA 2**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo “Telefone celular” com menos de 11 dígitos (sem contar as máscaras) 
E eu tirar o foco do campo “Telefone celular”
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Está sendo permitido salvar indevidamente "Telefone celular" com menos de 11 dígitos (sem contar as máscaras)

![image](https://user-images.githubusercontent.com/15328510/81027759-450bff80-8e55-11ea-95cc-ca10938ad2f0.png)

[RESULTADO ESPERADO]
Não deveria ser permitido salvar "Telefone celular" com menos de 11 dígitos (sem contar as máscaras)

============================================
**PROBLEMA 3**

[AMBIENTE]
https://covid19-db1-frontend.herokuapp.com/

[REPRODUÇÃO]
Dado que eu tenha realizado o login com um usuário com permissão a funcionalidade de “Notificações”
E eu clique na opção "NOVA NOTIFICAÇÃO"
E eu esteja na tela de “Cadastro de notificação”
E eu esteja na seção “3. IDENTIFICAÇÃO DO PACIENTE”

Quando eu informar no campo "Telefone contato" com menos de 10 ou 11 dígitos (sem contar as máscaras) 
E eu tirar o foco do campo "Telefone contato"  
E eu informar as demais informações obrigatórias 
E eu clicar no botão “ENVIAR” 

[PROBLEMA]
Não está sendo apresentado o nome do campo na mensagem ao salvar notificação com "Telefone contato" com menos dígitos que o permitido:

"suspeito.telefoneContato" deve conter pelo menos 10 caracteres

![image](https://user-images.githubusercontent.com/15328510/81028016-3114cd80-8e56-11ea-873c-a46160532494.png)

[RESULTADO ESPERADO]
Deveria ser apresentado o nome do campo na mensagem ao salvar notificação com "Telefone contato" com menos dígitos que o permitido:

"Telefone contato" deve conter pelo menos 10 caracteres

============================================

**Comment by CristianeBorges05** [comment]
VALIDADO QA - OK

![Resolvido_telefone](https://user-images.githubusercontent.com/63747448/81131827-d85f3680-8f22-11ea-9acd-f3acbc04bf99.gif)
