### ISSUE TITLE
Colocar todas as informações no tipo de notificação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#210]
Será necessário colocar todas as informações na tela:

2. DEFINIÇÃO DO CASO
(     ) Situação 1: [CASO SUSPEITO] Febre E pelo menos um sinal ou sintoma respiratório (tosse, dificuldade para respirar, batimento das asas nasais, dor de garganta, coriza e chiado no peito).

(     ) Situação 2: [CONTATO DE CASO SUSPEITO OU CONFIRMADO] Febre E/OU pelo menos um sinal ou sintoma respiratório (tosse, dificuldade para respirar, batimento das asas nasais, dor de garganta, coriza e chiado no peito) + contato com caso suspeito e/ou confirmado com início dos sintomas, nos últimos 14 dias.

**Comment by nasouza2** [comment]
Ok, ajustado.
![Card #210 aprovado](https://user-images.githubusercontent.com/17462759/80661020-d1887d80-8a63-11ea-9f3f-6703eecd5deb.png)
