### ISSUE TITLE
Incluir Municipio e Bairro na Pessoa

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#212]
Será necessário informar o município da pessoa. Pode ser atendido paciente de outro municipio.

Na notificação o usuário deverá informar o município e o sistema deve filtrar apenas os bairros do município informado.

Importar municípios
Importar os bairros para cada município.
![Modelo Municipio Pessoa](https://user-images.githubusercontent.com/64052760/79993634-58998c80-848b-11ea-9d58-ade462acb7ba.png)

**Comment by ftathiago** [comment]
## Dúvidas
### 1- Pesquisa por município
Nós já dispomos de um endpoint /municipios/:municipioId/bairros que devolve ao usuário todos os bairros daquele município. 
Seria interessante, portanto, fazer um esquema parecido com a pesquisa de municípios em que retorna apenas 10 municípios que atendam a pesquisa e conforme vai preenchendo, o município é selecionado. Acham isso viável, @wildeee , @carloshabarbosa @FabioBezerra , @maykon @altitdb e @rgsouzabr ?

### 2- Campo de município na pessoa
@rgsouzabr , a pessoa já possui a informação do Bairro (e cada bairro pertence a um município). Será realmente necessário adicionar este campo a tabela de pessoa?

### 3- Notificacao.municipioId
@rgsouzabr , ainda faz sentido a tabela de Notificação ter um campo municipioId, uma vez que a unidade de saúde já possui um municipioId também?

**Comment by wildeee** [comment]
A ideia já é remover o município Maringá fixo no front?
Se sim, acho mais interessante fazer a filtragem por UF e por nome (já que podem ter muitos municípios num estado)

**Comment by monitorcosta** [comment]
**1- Pesquisa por município**
@FabioBezerra fez dessa forma.

**2- Campo de município na pessoa** 
Alinhei com @rgsouzabr e essa alteração é para indicar que o município é da pessoa e outras melhorias. Uma dessas melhorias apontada na conversa foram pesquisas mais performáticas e o retorno para exibição em tela.

 **3- Notificacao.municipioId**
Alinhado com @rgsouzabr que este campo servirá para filtrar as notificações por município quando necessário. Atualmente está gravando o que veio do informado na tela da notificação e com esta alteração passará a gravar o município da unidade de saúde.

@wildeee 
A Issue #120 removerá este campo.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020

GET: https://qa-api.notificasaude.com.br/api/pessoas

![image](https://user-images.githubusercontent.com/15328510/80314282-f3190900-87c6-11ea-9ba0-051753927619.png)
