### ISSUE TITLE
Quando for laboratório rede privada abrir um campo para qual laboratório - Back

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#213]
Requisito esta anexo
[Requisito Laboratorio.docx](https://github.com/db1group/contra-covid19/files/4529740/Requisito.Laboratorio.docx)

**Comment by ftathiago** [comment]
* [ ] - Criar campo NotificacaoCovid19.laboratorioOficialNome: String(30)
* [ ] - Alterar mapeamento para considerar o campo em Request -> Model
* [ ] - Alterar mapeamento para considerar o campo em Model -> Response
* [ ] - Alterar squema de validação (se existir)

**Comment by monitorcosta** [comment]
Criado o campo NotificacaoCovid19.tipoLaboratorio como Enum para substituir os campos NotificacaoCovid19.laboratorioOficial e NotificacaoCovid19.laboratorioRedePrivada. Os enuns terão valores “OFICIAL” e “PRIVADO”.
Quando escolhido a opção de laboratório da rede provada abrirá o campo para digitar o nome do laboratório que será gravado no campo NotificacaoCovid19.nomeLaboratorioEnvioMaterial

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020

POST: https://qa-api.notificasaude.com.br/api/notificacoes

![image](https://user-images.githubusercontent.com/15328510/80314379-af72cf00-87c7-11ea-99cb-8a8766ca93c4.png)

![image](https://user-images.githubusercontent.com/15328510/80314391-c1547200-87c7-11ea-8936-86e5abd41703.png)
