### ISSUE TITLE
Abrir um PDF no botão "abrir orientações...."

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#214]
Permitir que seja aberto um pdf da secretaria de saúde ao pressionar o botão.

**Comment by wildeee** [comment]
@rgsouzabr Temos esse PDF?

**Comment by rgsouzabr** [comment]
Ainda não. Eles ficaram de enviar

**Comment by maykon** [comment]
@rgsouzabr Não enviaram o PDF ainda?

**Comment by maykon** [comment]
https://github.com/db1group/contra-covid19/issues/214

**Comment by 100198** [comment]
Link para o PDF: http://www2.maringa.pr.gov.br/sistema/arquivos/8fcc967791a9.pdf

**Comment by wildeee** [comment]
Abri o Pull Request pra possibilitar abrir o PDF, mas talvez isso só funcione de fato quando fizerem a atividade #472 
Entretanto, podem completar esse PR normalmente, fiz o tratamento para não estourar nenhum erro.

**Comment by 100198** [comment]
![image](https://user-images.githubusercontent.com/64612597/81437140-120d8880-9141-11ea-9051-92f1b5eca2ba.png)

Não está direcionando para as orientações e está abrindo essa tela em branco

**Comment by wildeee** [comment]
Estou fechando essa tarefa, pois o que fiz nela aparentemente está certo. O real problema está na variável de ambiente VUE_APP_ORIENTATIONS_PDF que não está vindo com o valor esperado, e isso pertence à issue #472, que estou reabrindo.
