### ISSUE TITLE
Incluir opções de uma tabela para informar a ocupação do paciente - Front

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#215]
[Requisito Ocupacao Paciente.docx](https://github.com/db1group/contra-covid19/files/4529773/Requisito.Ocupacao.Paciente.docx)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020:

GET: https://qa-api.notificasaude.com.br/api/ocupacoes
Cadastro de Notificação: https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80289458-e89e3700-8714-11ea-85ed-468ae9ce4f44.png)
