### ISSUE TITLE
Quando for rede privada abrir um campo para digitar o nome do laboratório - Front

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#220]
O requisito está anexo
[Requisito Laboratorio.docx](https://github.com/db1group/contra-covid19/files/4529737/Requisito.Laboratorio.docx)

**Comment by monitorcosta** [comment]
Criado o campo NotificacaoCovid19.tipoLaboratorio como Enum para substituir os campos NotificacaoCovid19.laboratorioOficial e NotificacaoCovid19.laboratorioRedePrivada. Os enuns terão valores “OFICIAL” e “PRIVADO”.
Quando escolhido a opção de "Laboratório da rede PRIVADA" no cadastro de notificação abrirá o campo para digitar o nome do laboratório que será gravado no campo NotificacaoCovid19.nomeLaboratorioEnvioMaterial

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80314666-455b2980-87c9-11ea-98f5-d890b8b042f7.png)
