### ISSUE TITLE
Preencher automaticamente o campo Unidade Notificante no Cadastro de notificação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#221]
Alimentar automaticamente a unidade de saúde na notificação.

Ao incluir a notificação informar o usuário. Através do usuário "logado" o sistema deverá identificar qual a unidade de saúde do usuário e alimentar a tela de notificação. 
1) Usuários da secretaria de saúde pode liberar o campo para digitar
2) Usuários que não são da secretaria de saúde não podem alterar a unidade de saúde.

**Comment by ftathiago** [comment]
Salvo melhor juízo, isso poderia ser feito no front, através do payload do keycloak. 
Confere, @altitdb @maykon ?

**Comment by maykon** [comment]
@rgsouzabr Precisa ver quais unidades cada usuário vão acessar para poder criar o script da tabela e as inserções.

OBS: Uma dúvida, apenas será permitido escolher as unidades vinculadas ao usuário, ou o mesmo pode selecionar todas?

@ftathiago Sim, isso tem q ser feito no front. Eu já deixei preparado o load do Id do usuário. Precisa  criar o vinculo com a unidade e realizar a consulta específica.
