### ISSUE TITLE
PERMITIR EDITAR A NOTIFICAÇÃO

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#230]
Permitir editar a Notificação.
A notificação somente poderá ser editada enquanto não estiver encerrada. 
Os usuários da Secretaria poderão alterar todas as fichas (qualquer unidade de saúde). Entretanto, usuários que não sejam da Secretaria poderão alterar apenas suas fichas digitadas (apenas o usuário da unidade de saúde.

**Comment by nasouza2** [comment]
Retornando o card para "Em teste", pois ele passará pela revisão de um QA.

**Comment by nasouza2** [comment]
Identificado bugs nessa funcionalidade, Sua aprovação depende das issues:
https://github.com/db1group/contra-covid19/issues/566
https://github.com/db1group/contra-covid19/issues/559
https://github.com/db1group/contra-covid19/issues/568

**Comment by AndressaKarla** [comment]
> Identificado bugs nessa funcionalidade, Sua aprovação depende das issues:
> #566
> #559
> #568

Dessas issues que a @nasouza2 mencionou no comentário anterior, o #559 e o #568 foram testados com sucesso e movido para "Done".

Ficou restando o #566 que no dia 14/05 ainda não estava disponível para testes.

**Comment by nasouza2** [comment]
Identificado mais um caso grave.

https://github.com/db1group/contra-covid19/issues/577

**Comment by AndressaKarla** [comment]
> Identificado mais um caso grave.
> 
> #577 - Homologado.
> #583

Aparentemente #583 ainda ocorre

**Comment by AndressaKarla** [comment]
> > Identificado mais um caso grave.
> > #577 - Homologado.
> > #583
> 
> Aparentemente #583 ainda ocorre

Após nova disponibilização de pullrequest revisado, e após novo merge no ambiente QA, aparentemnte #583 estaria ok e homologado

@nasouza2 se vc quiser dar mais uma revisada na parte de edição de notificação para verificar se não ficou mais nada pendente :)

**Comment by nasouza2** [comment]
Validado; casos de testes criados. Falta apenas o cenário da edição citado na issue #442 . Preciso entender as regras para poder criar o caso.
