### ISSUE TITLE
TELA PARA EXPORTAR DADOS EM EXCEL

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#231]
Já existe uma rotina no backend para exportar os dados da notificação para o Excel.

**Comment by neyricardo** [comment]
Será que precisa de uma tela ou um botão resolveria?
O que esta tela deveria mostrar?

**Comment by AndressaKarla** [comment]
Aguardando correção das issuesabaixo para dar continuidade aos testes:
- https://github.com/db1group/contra-covid19/issues/464
- https://github.com/db1group/contra-covid19/issues/453

**Comment by AndressaKarla** [comment]
> Aguardando correção das issues abaixo para dar continuidade aos testes:
> 
> * #464
> * #453

Aparentemente as issues #464 e #453 foram resolvidas, porém ainda seria necessário a correção da issue #498 para dar continuidade aos testes
