### ISSUE TITLE
Enviar Notificação via API para a secretaria estadual

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#234]
[Questões sobre a transmissão dos dados.docx](https://github.com/db1group/contra-covid19/files/4607011/Questoes.sobre.a.transmissao.dos.dados.docx)

Documentação da API
https://201.77.19.17//Manuais_sistemas/imprime_manual/imprime_manual.php?id_sistema=22&rash_manual=941e7ea97b8fd4f40b922fc8724e2760

A url que está na documentação é de homologação, após testes entrar em contato conosco para disponibilizarmos a url de produção e token de produção.

Como estamos em desenvolvimento da API ainda faremos mais ajustes e/ou alterações, 
manteremos a documentação atualizada. 

Segue token de homologação:
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1ODg3MTMxNjksInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImVkdWFyZG9yaWJlaXJvQG1hcmluZ2EucHIuZ292LmJyIn0.B2vI1omKUBHLW7kNuCaM8M7xl7c9zXLLOczLqjBNYZNsjX1Chbom7iMWhEElPM54bVlLSiw-1Jagv8iT0oBrekj-4K8gkiN45qXblbUS7nulEmrh5ic04zDenmZOmShSBraI4BLHFcOUsg-cfDkQiE1W5HWLDNDVwPk7jBf1oNGo3Jeg8a4H0cxeu167swZJnIWVooczmMyf2qOIwtY3hOFvTfN7k2Ev6U7W5j6SxDzfhlbXOX-PPVNFB51BVIjRWK4YAhOXofPz6UrQHDGgfhVMJ204iXFZR3kKozbh3VaC-rRyJmE2j8pHdhwmhO5FeyNSaESN8lBjbEWjK6nynZk6ERYt2t4h2NzMr-bb07Tun0aF1N4dYus-hV7wje4LDICv-KM5Ui3YLpLTM3ZSAXqL8qiXgM5ly8OlJmHnYQ71vCFua5v9c3UkHhJmJCLFY74wtiSfzIAN6rmSlOOuWTESXY4AA6a5MVO76wXydjzF6p9jVdQdm7iW9HEqCNIichM5wr4LAkeJRVONR2ANisSEwiFY513bVjQCw3lOHVX4wu3GhlNfEjSRvkG-rDqod10_P3N3NcfRbl2VioPWYbhg3fT8XZ29BHDZqsWf15hewzRiH7RPxW4UaHi1ZejZs19Y9TV0xcAx6iVO1t6Dtbgm0ZXt23Um9NFr1Cxi_40

**Comment by ftathiago** [comment]
[Questões sobre a transmissão dos dados.docx](https://github.com/db1group/contra-covid19/files/4604482/Questoes.sobre.a.transmissao.dos.dados.docx)
@rgsouzabr , por favor, considere o conteúdo desse arquivo.
