### ISSUE TITLE
Melhoria após salvar uma notificação

### ISSUE THREAD

**Issue by FabioBezerra** [db1group/contra-covid19#237]
## Feature Request

**Descreva a solução que você gostaria**
Após salvar uma notificação com sucesso, deve reposicionar a tela para o topo.

**Comment by CristianeBorges05** [comment]
Validado ok
![topo da tela](https://user-images.githubusercontent.com/63747448/80282317-1d939500-86e7-11ea-9a0e-0e52b566a352.gif)
