### ISSUE TITLE
Local de internamento incorreto no lançamento da evolução de óbito.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#243]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Reprodução
Dado que eu tenha incluído uma notificação com situação igual a "Evolução para ÓBITO"
Quando eu estiver na tela de Evolução dos pacientes
Então no campo Local é apresentado "EVOLUCAO_OBITO".

Problema
Local de internamento incorreto, quando a notificação é lançada com internamento "Evolução para ÓBITO".

Resultado esperado
Ajustar o local "EVOLUCAO_OBITO" para "Evolução para óbito".
![img1](https://user-images.githubusercontent.com/17462759/80043069-08e0b280-84d7-11ea-9b88-fcc88fba0bba.png)

**Comment by nasouza2** [comment]
ok, ajustado.

**Comment by jef-araujo** [comment]
@nasouza2 testei com a ultima versão do código e o erro não ocorre mais. Poderia verificar novamente pfv?

**Comment by nasouza2** [comment]
Situação ainda ocorre; aguardando retorno do Jefferson.

**Comment by jef-araujo** [comment]
@nasouza2 o problema ocorre se cadastrar uma nova notificação e nova evolução?
ou só com essa notificação/evolução ja existente

**Comment by nasouza2** [comment]
@jef-araujo problema ocorre quando lança uma nova notificação, direto como "Evolução para óbito".

![2020-04-23_20h38_42](https://user-images.githubusercontent.com/17462759/80218226-477d8680-8617-11ea-8347-fce70cc39386.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso:

![image](https://user-images.githubusercontent.com/6394762/80269675-3456cf00-8688-11ea-8082-9e392cfbc92c.png)
