### ISSUE TITLE
Mudanças nas colunas da tela de consulta

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#244]
Após apresentação para as enfermeiras da secretaria de saúde solicitaram a mudança das colunas que são apresentadas na tela de consulta.

![MudancasConsulta 22042020](https://user-images.githubusercontent.com/64052760/80047001-a2fa2800-84e2-11ea-9d12-319738607e78.png)

Retirar o link "excluir em lote"

**Comment by jgracino** [comment]
A ação de visualizar será feita futuramente
