### ISSUE TITLE
Criar um filtro de status da notificação na tela de consulta

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#246]
Será necessário pesquisar as notificações encerradas.

Sugestão: Criar três opções: ENCERRADAS / ABERTAS / TODAS
![Filtro Consulta 22042020](https://user-images.githubusercontent.com/64052760/80050496-20766600-84ec-11ea-8f5c-f00dddd0a42c.png)

**Comment by CristianeBorges05** [comment]
@maykon Olá, pode verificar esse fluxo por favor, qdo selecione todas as notificações e depois aciono o filtro de situação?

Vide evidência:
![filtro](https://user-images.githubusercontent.com/63747448/80552873-5e690380-899e-11ea-857b-ba3b7474a215.gif)

**Comment by maykon** [comment]
@nasouza2 Criado alteração para os problemas reportados https://github.com/db1group/contra-covid19/pull/398

**Comment by CristianeBorges05** [comment]
@nasouza2  como ele respondeu, a alteração está na 398. Mas ainda não está pronta. Vou esperar ela ficar pronta para liberar esta 246.

**Comment by maykon** [comment]
@CristianeBorges05 falta apenas alguém aprovar o merge e testar. https://github.com/db1group/contra-covid19/pull/398

**Comment by CristianeBorges05** [comment]
Solicitei lá no grupo a aprovação de alguém

**Comment by bobycachoeira** [comment]
Pendente de publicação.

**Comment by CristianeBorges05** [comment]
Validado QA

![filtro situação ok](https://user-images.githubusercontent.com/63747448/80829699-027cc580-8bbe-11ea-8c6b-625ef7408174.gif)
