### ISSUE TITLE
Importar todos os municípios do País

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#255]
Importar todos os municípios do País. Para cada município criar um bairro "GERAL"
[Localidades (Municípios).xlsx](https://github.com/db1group/contra-covid19/files/4523034/Localidades.Municipios.xlsx)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80313807-c1eb0980-87c3-11ea-99fd-2293d797db3f.png)

![image](https://user-images.githubusercontent.com/15328510/80313822-cf07f880-87c3-11ea-8d41-c3967b17ddfe.png)
