### ISSUE TITLE
Incluir novos tipos no método de exame da notificação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#256]
Incluir novos tipos no método de exame (tp_metodoExame) da notificação.

SOROLOGIA/OUTROS

Em outro momento criaremos uma tabela com os métodos.

**Comment by ftathiago** [comment]
* [ ] -Alterar modelo para suportar o novo tipo
* [ ] - Alterar migration para suportar 16 posições no campo string

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020
POST : https://qa-api.notificasaude.com.br/api/notificacoes
 "metodoDeExame": "SOROLOGIA_OUTROS"

![9JvwNvYWxE](https://user-images.githubusercontent.com/15328510/80313671-c19e3e80-87c2-11ea-8d63-fb3930893fde.gif)
