### ISSUE TITLE
Remover termo técnico da mensagem e incluir ponto final.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#262]
Ambiente
https://app.notificasaude.com.br/

Reprodução
Dado que eu tenha incluído uma evolução com data futura
Quando eu clicar em Atualizar notificação
Então é apresentada a mensagem: "Validation error: A evolução não pode possuir data futura".

Problemas
a) Remover "Validation error" da mensagem.
b) Inserir ponto final na mensagem.

Resultado esperado
Descritos junto com os problemas.
![img1](https://user-images.githubusercontent.com/17462759/80158870-08f8b500-85a0-11ea-83a3-6cef7c9ea94b.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/5b21e51b-149e-41da-b51f-a064f8634bcb/evolucoes

![j4Dti7aEpk](https://user-images.githubusercontent.com/15328510/80312769-91a06c80-87bd-11ea-947b-dd651073344b.gif)
