### ISSUE TITLE
Não traz o telefone residencial na evolução.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#264]
Ambiente
https://app.notificasaude.com.br/

Reprodução
Dado que eu tenha incluído uma notificação informando telefone residencial
Quando eu clicar em Evoluir
Então o telefone informado não é apresentado na tela de Evolução dos pacientes.

Problema
Não traz o telefone residencial na evolução.

Resultado esperado
Trazer os 3 (três) telefones informados na notificação. Pode ser concatenados tel1 | tel2 | tel3

![img1](https://user-images.githubusercontent.com/17462759/80160998-70653380-85a5-11ea-9c6f-d8b6c28340b2.png)
![img2](https://user-images.githubusercontent.com/17462759/80161002-71966080-85a5-11ea-81f3-10b2ada6565c.png)

**Comment by maykon** [comment]
@nasouza2 Eu estou trazendo o telefone de contato. Não tinha especificação de qual colocar, se achar necessário posso alterar.

**Comment by nasouza2** [comment]
@rgsouzabr Bom dia, hoje é obrigatório informar somente **um** dos telefones na inclusão da notificação. 
Se eu informo o telefone residencial, esse dado não é listado na tela de evoluções, porque lá é apresentado o telefone informado no campo "Telefone contato".

Favor rever essa regra. O importante é não deixar o campo "Telefone" em branco na tela de Evolução dos pacientes, visto que esse campo é de preenchimento obrigatório.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/

![ihHev5NkKm](https://user-images.githubusercontent.com/15328510/80297416-186f2e00-8759-11ea-86d1-d315df69e518.gif)
