### ISSUE TITLE
Erro no console ao enviar notificação (alterações no campo sexo)

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#267]
Ambiente
https://app.notificasaude.com.br/notificacoes/cadastro

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
E esteja na sessão "3. IDENTIFICAÇÃO DO PACIENTE"
E esteja no radio "sexo" 
Quando eu marcar a opção feminino
E marcar a opção gestante
E alterar o radio para masculino
E preencher todos os campos obrigatórios
E acionar o botão Enviar

Problema
Está ocorrendo um erro

Resultado esperado
Salvar a notificação corretamente.

EVIDÊNCIAS

![image](https://user-images.githubusercontent.com/63747448/80164179-a35ff500-85ae-11ea-9a47-ddbea6d1b2e6.png)

**Comment by CristianeBorges05** [comment]
Não consegui carregar o gif com a evidência. Mas quem assumir a correção pode me procurar que mostro a evidência do caso.

**Comment by AndressaKarla** [comment]
Aparentemente esse problema deixou de ocorrer
