### ISSUE TITLE
Criar um campo de complemento do endereço

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#276]
Quando o bairro for "Geral" obrigar a informar o complemento do endereço.

**Comment by jgracino** [comment]
@maykon Quando clica no botão de "Enviar"
Então o sistema não está obrigando o preenchimento do campo "Complemento" quando eu informo o valor "Geral" no campo "Bairro".

**Comment by jgracino** [comment]
![image](https://user-images.githubusercontent.com/16705663/80280546-12d30300-86db-11ea-8258-3142bede46cf.png)

**Comment by AndressaKarla** [comment]
@maykon Aparentemente problema ainda ocorre, retornado issue para "To do Dev"

![image](https://user-images.githubusercontent.com/15328510/80314002-f7dcbd80-87c4-11ea-92e7-2a88ec5edee2.png)

**Comment by CristianeBorges05** [comment]
Erro ainda persiste, por favor verificar
@mkacunha 

![image](https://user-images.githubusercontent.com/63747448/80553166-39c15b80-899f-11ea-9deb-c60bc7e60cca.png)

**Comment by CristianeBorges05** [comment]
ok, conforme solicitado regra ainda não está aplicada. Então estou movendo para To do

**Comment by maykon** [comment]
@CristianeBorges05 realizado merge na PR https://github.com/db1group/contra-covid19/pull/388
