### ISSUE TITLE
Incluir opções de uma tabela para informar a ocupação do paciente - Back

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#278]
[Requisito Ocupacao Paciente.docx](https://github.com/db1group/contra-covid19/files/4529792/Requisito.Ocupacao.Paciente.docx)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020:

POST: https://qa-api.notificasaude.com.br/api/notificacoes

![image](https://user-images.githubusercontent.com/15328510/80314570-b6e6a800-87c8-11ea-9488-a4e8f1cb4ed1.png)
