### ISSUE TITLE
Incluir as ocupações do notificador

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#279]
MEDICO
ENFERMEIRO
TECNICO/AUXILIAR DE ENFERMAGEM
TECNICO/AUXILIAR ADMINISTRATIVO
OUTRO PROFISSIONAL DA SAUDE

**Comment by maykon** [comment]
Obs: Profissões do notificador.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020

GET: https://qa-api.notificasaude.com.br/api/profissoes

![image](https://user-images.githubusercontent.com/15328510/80313891-535a7b80-87c4-11ea-8434-d0caca622d97.png)
