### ISSUE TITLE
Erro 400 ao tentar evoluir notificação encerrada.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#290]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu tenha incluído uma notificação
E a tenha encerrado
Quando eu clicar em EVOLUÇÃO
Então será gerado erro no console.

Problema
Gera erro no console ao clicar em EVOLUÇÃO de notificação encerrada.

Resultado esperado
Desabilitar botão de EVOLUÇÃO caso a notificação esteja encerrada.

[log.txt](https://github.com/db1group/contra-covid19/files/4532238/log.txt)

![img1](https://user-images.githubusercontent.com/17462759/80269435-49326300-8686-11ea-981e-60ee2f980536.png)
![img2](https://user-images.githubusercontent.com/17462759/80269436-4afc2680-8686-11ea-9eef-33a4d95e5415.png)

**Comment by nasouza2** [comment]
Baixando a criticidade; alteração não é para a entrega de amanhã.

**Comment by AndressaKarla** [comment]
Esse bug foi corrigido nessa melhoria https://github.com/db1group/contra-covid19/issues/78
