### ISSUE TITLE
Permitindo encerrar notificação confirmada.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#291]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu tenha incluído uma notificação
E tenha confirmado o caso
Quando eu lançar uma evolução de com condição atual "ENCERRADO"
Então está sendo permitido.

Problema
Permitindo encerrar notificação confirmada.

Resultado esperado
Não permitir encerrar notificação confirmada. Caso confirmado só pode ser receber status de curado ou óbito.

OBS: O print da primeira imagem ficou incorreto; a situação selecionada foi ENCERRADA.

![img2](https://user-images.githubusercontent.com/17462759/80269494-9ca4b100-8686-11ea-814d-a14620d042a1.png)

![img1](https://user-images.githubusercontent.com/17462759/80269493-9b738400-8686-11ea-9bda-14362fefde65.png)

**Comment by ftathiago** [comment]
@nasouza2 , apenas para confirmar: Eu não posso passar para os seguintes status após a notificacao estar confirmada
- Suspeito
- Descartado
- Confirmado
- Encerrado.

Confere?

**Comment by nasouza2** [comment]
@ftathiago Confere.

Na issue #182 já foi feito uma parte; faltou apenas a situação ENCERRADO.

"implementado para não permitir evolução para: DESCARTADO, SUSPEITO, CONFIRMADO, quando a notificação já estiver com status CONFIRMADO."

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80270893-3faef800-8692-11ea-837f-c418e8cb56cc.png)

**Comment by nasouza2** [comment]
Ok, ajustado.
