### ISSUE TITLE
Validação do campo Bairro.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#294]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Cadastro de notificação
Quando eu selecionar o município
Então será apresentada a mensagem de que o bairro é obrigatório.

Problema
Apresenta a mensagem de que o bairro é obrigatório mesmo o campo não recebendo o foco.

Resultado esperado
Validar preenchimento do bairro quando passar pelo campo ou quando ele efetivamente não for preenchido.

![oEyyR9vH1f](https://user-images.githubusercontent.com/17462759/80269871-de832680-8689-11ea-8ee6-b59dba825f36.gif)

**Comment by wildeee** [comment]
Comportamento corrigido. O único caso que isso vai continuar acontecendo, e quando o bairro já estiver preenchido, e o município for alterado. Nesse caso, o bairro vai ficar em vermelho como feedback do usuário, para que ele preencha novamente.

Alterei também o campo bairro para ficar desabilitado até que se selecione o município, pois não faz sentido preencher bairro antes do município.

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![w10ULEycS2](https://user-images.githubusercontent.com/15328510/80317894-dbe51600-87dc-11ea-9592-5d95139b8847.gif)
