### ISSUE TITLE
Seção 12 de Conclusão do atendimento não está sendo obrigatório.

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#296]
## Bug Report

**AMBIENTE**
QA

**REPRODUÇÃO**
Dado que eu acesse a tela de criação de notificação.
E informe todos os dados.
E deixe tudo na seção 12. CONCLUSÃO DO ATENDIMENTO em branco.
Quando clicar em Salvar.

**PROBLEMA**
Está salvando normalmente.

**RESULTADO ESPERADO**
Deveria validar campo obrigatório a seção 12.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![TPR7iZhfHf](https://user-images.githubusercontent.com/15328510/80296223-74cd5000-874f-11ea-9f25-b499bc29a11f.gif)
