### ISSUE TITLE
Redirecionamento após logoff.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#303]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu fazer o logoff
E acessar novamente o sistema
Então o redirecionamento é para a página que estava antes do logoff.

Problema
Após sair do sistema e acessar novamente, o redirecionamento é para a página que estava antes do logoff e não para a página home.

Resultado esperado
Após logoff e novo acesso ao sistema, redirecionar para a Home.

![jeHxBcS4ws](https://user-images.githubusercontent.com/17462759/80271958-d6cc7d80-869b-11ea-8851-f43a47631b0b.gif)

**Comment by wildeee** [comment]
Ajustado provisoriamente, enquanto o #356 não é feito

**Comment by CristianeBorges05** [comment]
Validado QA

![bug logoff](https://user-images.githubusercontent.com/63747448/80546212-71bea380-898b-11ea-8501-7ae0f8a983d4.gif)
