### ISSUE TITLE
Ao fazer logoff dispara mensagem de obrigatoriedade no campo "Data e hora notificação".

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#305]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu clicar em SAIR
Então no campo "Data e hora notificação" será apresentada a mensagem: "O campo é obrigatório.".

Problema
Ao fazer logoff dispara mensagem de obrigatoriedade no campo "Data e hora notificação".

Resultado esperado
Não apresentar mensagem de obrigatoriedade de preenchimento do campo "Data e hora notificação" ao fazer o logoff.
![Zhws3sq4NY](https://user-images.githubusercontent.com/17462759/80272463-08dfde80-86a0-11ea-81ed-45a0b38b082e.gif)

**Comment by wildeee** [comment]
O problema era o autofocus. Ao sair de um campo obrigatório, o comportamento esperado é que ele fique vermelho mesmo. O problema era que ao entrar na tela, o sistema colocava seu foco automaticamente no campo, daí não tem pra onde fugir.

Removi o autofocus.
Disponível para merge.

**Comment by wildeee** [comment]
Atualizando a solução

Agora a validação "required" do campo será habilitada somente ao tentar submeter

**Comment by nasouza2** [comment]
Ok, ajustado.
