### ISSUE TITLE
Inserir label para informar nome do laboratório privado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#308]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Cadastro de notificação
Quando eu clicar em Laboratório da rede PRIVADA
Então é habilitada apenas uma linha, sem o nome do campo.

Problema
Não tem label para informar o nome do laboratório privado.

Resultado esperado
Inserir label para informar nome do laboratório privado.

![img1](https://user-images.githubusercontent.com/17462759/80273241-e8ffe900-86a6-11ea-96c0-457b2a370ade.png)
![img2](https://user-images.githubusercontent.com/17462759/80273242-ea311600-86a6-11ea-87e0-0cdfbaa46ae7.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80295462-2fa61f80-8749-11ea-940e-6bd90a74e175.png)
