### ISSUE TITLE
Campos que somente apresentam dados se digito com todas as letras maiúsculas

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#310]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes/cadastro

REPRODUÇÃO
Dado que eu esteja na tela de criação de notificação.
E esteja na seção "1. IDENTIFICAÇÃO DO NOTIFICANTE"
Quando eu digitar uma informação com letras minúsculas no campo Unidade Notificante
E houver uma unidade correspondente para os dados digitados

PROBLEMA
Só está exibindo o nome das unidades quando digito com letras maiúsculas
OBS.: O mesmo ocorre para município e bairro.

RESULTADO ESPERADO
Deveria ser exibido resultado correspondente ou ao digitar, o campo já preencher com letras maiúsculas. Vide evidência:
![Unidade Notificante_letras maiúsculas](https://user-images.githubusercontent.com/63747448/80279483-5d04b600-86d4-11ea-8fbb-2052124688ee.gif)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![9wlYZKwJKV](https://user-images.githubusercontent.com/15328510/80297877-9f260a00-875d-11ea-950c-cbdf1f918773.gif)
