### ISSUE TITLE
Não consigo acessar a tela de evolução

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#311]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes

Quando estou na tela de listagem de notificações e clico em "evolução" não está redirecionando para a tela de evolução.

Vide evidência

Request URL: https://qa-api.notificasaude.com.br/api/notificacoes/1a001fed-3811-4ae1-b981-37d1349d3422/evolucoes
Request Method: GET
Status Code: 400 
Remote Address: 52.205.247.211:443
Referrer Policy: no-referrer-when-downgrade

![sem acesso a evolução](https://user-images.githubusercontent.com/63747448/80280206-15345d80-86d9-11ea-8882-f3b0ba20937e.gif)

**Comment by maykon** [comment]
@CristianeBorges05 https://github.com/db1group/contra-covid19/issues/290
Estou tratando isso nessa issue

**Comment by AndressaKarla** [comment]
Esse bug foi corrigido nessa melhoria https://github.com/db1group/contra-covid19/issues/78
