### ISSUE TITLE
Bug no campo Data de nascimento ao acessar pelo firefox

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#314]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes/cadastro

REPRODUÇÃO
Dado que estou na tela de criação de notificação.
E preencho o campo "Data de nascimento"

PROBLEMA
Está exibindo a mensagem "Informe uma data igual ou anterior ao dia de hoje"

RESULTADO ESPERADO
Deveria permitir informar uma data menor ou igual a atual, no formato válido dd/mm/aaaa.

Vide evidência:
![Data de nascimento firefox](https://user-images.githubusercontent.com/63747448/80281308-917e6f00-86e0-11ea-97f5-4ceae31579cd.gif)

**Comment by wildeee** [comment]
Eu e o Ney não conseguimos reproduzir o bug, então estou fechando ele.
Talvez tenha sido corrigido como e efeito colateral de alguma outra alteração que fizemos.
Se ainda estiver acontecendo aí, por favor, reabra a issue e nos diga qual é a versão do firefox que está usando;

**Comment by CristianeBorges05** [comment]
VALIDADO QA OK

![data de nascimento](https://user-images.githubusercontent.com/63747448/80551698-bdc51480-899a-11ea-93fa-05fc86de1b79.gif)
