### ISSUE TITLE
Adequar ficha nova sistema do estado - Front

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#326]
Várias alterações foram realizadas no sistema do estado. Segue anexo o requisito.
[RequisitoAdequarFichaNovaSistemaEstadoPR.docx](https://github.com/db1group/contra-covid19/files/4534004/RequisitoAdequarFichaNovaSistemaEstadoPR.docx)

**Comment by ftathiago** [comment]
# Dependência
[Depende dessa ISSUE para funcionar.](https://github.com/db1group/contra-covid19/issues/327)

**Comment by AndressaKarla** [comment]
Aguardando ser ajustado essa outra atividade https://github.com/db1group/contra-covid19/issues/327 para dar continuidade aos testes
