### ISSUE TITLE
Adequar ficha nova sistema do estado

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#327]
Várias alterações foram realizadas no sistema do estado. Segue anexo o requisito.
[RequisitoAdequarFichaNovaSistemaEstadoPR.docx](https://github.com/db1group/contra-covid19/files/4539497/RequisitoAdequarFichaNovaSistemaEstadoPR.docx)

**Comment by ftathiago** [comment]
### Criar no banco de dados
* [X] - tosseSeca
* [X] - tosseProdutiva 
* [X] - dispneia
* [X] - desconfortoRespiratorio
* [X] - nausea
* [ ] - tamiflu, boolean, not null (copiar conteúdo de medicacaoAntinflamatorio)
* [ ] - hidroxicloroquina, boolean, not null (copiar conteúdo de medicacaoAntiviral)
* [ ] - nomeMedicamentoAntiviral, string (ver o padrão dos campos de descrição) 
* [ ] - contatoComConfirmado, boolean, not null, default false
* [ ] - localDoContatoComSuspeito,  DataTypes.ENUM('DOMICILIO', 'UNIDADE_SAUDE', 'LOCAL_TRABALHO', 'OUTRO'),

### Alterar tipo
* [ ] - contatoComSuspeito ENUM -> Boolean
* [ ] - localDoContatoComSuspeito: Adicionar Enum "OUTRO"

### Apagar do banco
* [ ] - medicacaoAnalgesica, nomeMedicacaoAnalgesica
* [ ] - medicacaoAntitermica, nomeMedicacaoAntitermica

## DÚVIDAS
@rgsouzabr , você diz no requisito que devem ser alterados os campos medicacaoAntinflamatorio e medicacaoViral. Você dese que os valores atuais desses campos sejam repassados para os novos campos?
Caso afirmativo 
- Fazer uma migration que cria os novos campos
- Fazer uma migration que copia os valores para os campos
- Fazer uma migration que apaga os campos anteriores
*ATENÇÂO: utilizar transaction para garantir atomicidade.

**Comment by rgsouzabr** [comment]
Adequei o requisito para ficar mais fácil o entendimento posteriormente

**Comment by ftathiago** [comment]
Reaberta para corrigir migrate: erro no postgres detectado

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 01/05/2020, no front e back (banco de dados) no ambiente https://qa-app.notificasaude.com.br/notificacoes/c924a8f9-2a6c-4eca-8299-76628c38a1d7

![image](https://user-images.githubusercontent.com/15328510/80779526-4500bc80-8b42-11ea-9ce3-040cc1e30fa9.png)

![image](https://user-images.githubusercontent.com/15328510/80779619-8ee9a280-8b42-11ea-9f5e-5141868618f0.png)

**Comment by ftathiago** [comment]
@AndressaKarla essa issue pode ser fechada?

**Comment by CristianeBorges05** [comment]
Validado com a Andressa, vou mover para Done.
