### ISSUE TITLE
Não salva notificação sem ter informado a seção 8(não obrigatória).

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#331]
## Bug Report

**Ambiente**
https://qa-app.notificasaude.com.br/

**Reprodução**
Dado que eu acesse a tela de criar notificação.
E informe todos os dados obrigatórios.
E deixe a seção 8. REALIZADO COLETA DE MATERIAL PARA DIAGNÓSTICO sem marcar nada
Quando clicar em ENVIAR.

**Problema**
Está retornando do back a seguinte mensagem:

> {"error":"null value in column \"tipoLaboratorio\" violates not-null constraint","stack":null}

**Resultado Esperado**
Deveria salvar normalmente porque esta seção não é obrigatória na notificação.
Visto que não marquei que havia feito coleta.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![ezgif-6-bd0a580a3eef](https://user-images.githubusercontent.com/15328510/80295056-bb1db180-8745-11ea-9e24-fb697eefd5c0.gif)
