### ISSUE TITLE
Não retorna alguns campos da notificação

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#335]
## Bug Report

**Ambiente**
https://qa-app.notificasaude.com.br/

**Reprodução**
Dado que eu insira uma notificação.
Quando validar o retorno da API.
OU chamar a API de GET por id

**Problema**
No objeto de retorno não estão retornando alguns campos.
Abaixo ex. que envio:
```
    "conclusaoAtendimento": {
        "situacaoNoMomentoDaNotificacao": "ALTA_ISOLAMENTO_DOMICILIAR",
        "coletaMaterialParaDiagnostico": false,
        "tipoLaboratorio": "PRIVADO",
        "nomeLaboratorioEnvioMaterial": "Teste do cachoeira",
        "dataDaColeta": "2020-04-10",
        "metodoDeExame": "RT-PCR"
    }
```

e no retorno da notificação criada está:

```
        "conclusaoAtendimento": {
            "isolamentoDomiciliar": null,
            "leitoComum": null,
            "leitoUti": null,
            "prontoSocorroOuAtendimento": null,
            "coletaMaterialParaDiagnostico": false
        }
```

**Resultado Esperado**
Deveria retornar o objeto corretamente.
Aparentemente conforme novos campos foram inseridos, isso não foi refletido no retorno.

1. Obs.: Cuidar para se alterações nesses retornos não gerem problemas nas telas de listagem por exemplo. Visto que usam os GETs e usam campos do objeto de retorno para mostrar na tela.

Duvidas a disposição.

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80294929-64fc3e80-8744-11ea-8d73-eac595c2f77e.png)

Os campos abaixo não são utilizados no sistema e por isso foram retirados
 - isolamentoDomiciliar
 - leitoComum
 - leitoUti
 - prontoSocorroOuAtendimento
