### ISSUE TITLE
Criando visualização da Notificação

### ISSUE THREAD

**Issue by maykon** [db1group/contra-covid19#339]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Uma descrição clara e concisa de qual problema é: Ex.: Eu tenho um problema quando [...]

**Descreva a solução que você gostaria**
Uma descrição clara e concisa de como você gostaria que as coisas acontecessem. Considere as desvantagens também.

**Descreva qualquer alternativa considerada**
Existe uma outra forma de fazer a mesma coisa no sistema? Existe outro sistema que faz essa tarefa? Descreva.

**Documentação, Adoção, Estratégia de migração**
Se você puder, explique como os usuários poderão utilizar a sua feature e se possível, adicione documentação.
Protótipos, screenshots e requisitos e etc.

**Comment by CristianeBorges05** [comment]
Ao Cadastrar uma notificação dia **28/04/2020 ás 22:37**, ao selecionar a mesma notificação para **visualizá-la**, a data e hora apareceram diferentes da cadastrada. aparecendo na exibição como 29/04/2020 ás 01:37.

@maykon

**Comment by CristianeBorges05** [comment]
Não está exibindo a hora da notificação e a máscara para telefone com os parênteses separando o código.

![image](https://user-images.githubusercontent.com/63747448/80764244-a1e67d80-8b16-11ea-879c-11f2d8527592.png)

**Comment by wildeee** [comment]
Corrigido, PR aguardando revisão e merge

**Comment by wildeee** [comment]
Observação: Os outros campos de telefone e o CPF também estavam vindo sem máscara. Todos foram corrigidos nesse PR

**Comment by nasouza2** [comment]
Ok, aprovado.
