### ISSUE TITLE
Update na versão do keycloak

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#356]
## Feature Request

Hoje usamos a versão 7.0.1 do keycloak. Estamos umas boas versões atrás da mais recente. Isso engessa mudanças na conexão do front com o keycloak, pois o conector de versões mais novas pode ter mudado, e se mexermos nisso na versão antiga, podemos ter retrabalho.

**Descreva a solução que você gostaria**
Alterar a versão do keycloak para a mais recente

**Comment by maykon** [comment]
@altitdb @wildeee Atualizado para a versãop 10.0.0
