### ISSUE TITLE
Data preenchida equivocadamente após sair do campo obriga cadastrar

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#359]
Alguém pode simular por favor ?

Mesmo voltando e removendo um telefone que foi informado equivocadamente o sistema obriga a cadastrá-lo.

Ex: Informar o telefone residencial e sair do campo
     Remover o telefone residencial.
    Salvar
    O sistema vai pedir o telefone residencial.

**Comment by wildeee** [comment]
@rgsouzabr esse bug está duplicado com o #150 ?

**Comment by wildeee** [comment]
Eu creio que isso aqui já tenha sido resolvido. Estou mandando para o teste confirmar

**Comment by AndressaKarla** [comment]
A situação descrita nessa issue já havia sido descrita em outra issue https://github.com/db1group/contra-covid19/issues/150

Testes concluídos com sucesso no dia 10/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![mBXET5SGI9](https://user-images.githubusercontent.com/15328510/81490173-2773d700-9255-11ea-9ca3-b3836b846e53.gif)
