### ISSUE TITLE
Criar um tipo de classificação para a pessoa

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#360]
O sistema do estado pede a classificação da pessoa

Seque o requisito anexo.

[Requisitos Tipo Classificacao Pessoa.docx](https://github.com/db1group/contra-covid19/files/4541425/Requisitos.Tipo.Classificacao.Pessoa.docx)

**Comment by AndressaKarla** [comment]
@rgsouzabr @carloshabarbosa eu gostaria de verificar com vcs quando possível, como deveria ser o comportamento do campo ao lado do campo "Tipo de documento" quando seleciona as opções "Criança até 12 anos", "Em situação de rua", "Estrangeiro", "Indígena"?

Pois ao selecionar qualquer uma dessas opções, informar os demais campos obrigatórios, e clicar para salvar a notificação, o campo ao lado do campo "Tipo de documento" fica como obrigatório.

Segue evidência "[Uploading hlvu673u8H.zip…](hlvu673u8H.zip)" em anexo

**Comment by carloshabarbosa** [comment]
Reaberto para corrigir obrigatoriedade de documento
