### ISSUE TITLE
bug ao visualizar uma notificação

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#376]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes/cadastro

REPRODUÇÃO
Dado que estou na tela de notificações
E acione o botão "visualizar" de alguma notificação da listagem

PROBLEMA
Está exibindo a mensagem:
![image](https://user-images.githubusercontent.com/63747448/80546541-48524780-898c-11ea-802c-33d547909e17.png)

RESULTADO ESPERADO
Deveria permitir visualizar sem erros

**Vide evidência:**
Request URL: https://qa-api.notificasaude.com.br/api/notificacoes/157b6ca3-d4a9-4eea-ac04-793df5efb963
Request Method: GET
Status Code: 500 
Remote Address: 52.1.134.16:443
Referrer Policy: no-referrer-when-downgrade

![bug visualizar](https://user-images.githubusercontent.com/63747448/80546557-556f3680-898c-11ea-9c5d-0f3a129e7720.gif)

**Comment by maykon** [comment]
@CristianeBorges05  Era problema de uma migration q não permitiu rodar a criação dos novos campos, tente novamente agora.

**Comment by CristianeBorges05** [comment]
Validado QA- OK
