### ISSUE TITLE
erro no console ao acessar notificação de não sintomatico

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#381]
## Bug Report

**AMBIENTE**
https://qa-app.notificasaude.com.br/

**REPRODUÇÃO**
Dado que eu acesse a tela de listagem notificações.
E tenha uma notificação de alguém sem sintomas.
Quando clicar para visualizar essa notificação.

**PROBLEMA**
Está carregando os dados corretamente porém no console do navegador apresenta esse erro:
![image](https://user-images.githubusercontent.com/6394762/80552319-aa1aad80-899c-11ea-8464-c1d38416c25c.png)

**Possíveis soluções**
Não deveria apresentar erro, visto que não sendo sintomatico, no retorno esse campo vem como "null".

Obs.: Quando é sintomático nenhum erro é apresentao no console.

**Comment by maykon** [comment]
@bobycachoeira Realizado a correção.

**Comment by bobycachoeira** [comment]
testes concluídos com sucesso.
