### ISSUE TITLE
Utilizar o usuário logado no cadastro de notificação

### ISSUE THREAD

**Issue by maykon** [db1group/contra-covid19#384]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Uma descrição clara e concisa de qual problema é: Ex.: Eu tenho um problema quando [...]

**Descreva a solução que você gostaria**
Uma descrição clara e concisa de como você gostaria que as coisas acontecessem. Considere as desvantagens também.

**Descreva qualquer alternativa considerada**
Existe uma outra forma de fazer a mesma coisa no sistema? Existe outro sistema que faz essa tarefa? Descreva.

**Documentação, Adoção, Estratégia de migração**
Se você puder, explique como os usuários poderão utilizar a sua feature e se possível, adicione documentação.
Protótipos, screenshots e requisitos e etc.

**Comment by CristianeBorges05** [comment]
VALIDADO QA OK

![image](https://user-images.githubusercontent.com/63747448/81124653-58c66d00-8f0c-11ea-9cf7-09d7c9038d6a.png)
