### ISSUE TITLE
Validação dos caracteres informados nos campos para "Nome", "Endereço" e "Telefone"

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#389]
Ambiente
https://covid19-db1-frontend.herokuapp.com/

Problema
Campos descritos estão permitindo informar menos de 3 caracteres, números e caracteres especiais.
**Nome do Notificador, Nome completo, Nome da mãe, Nome da pessoa.
Validar Endereço, Telefone** também, pois este conjunto de campos já foram contemplados o back
Na issue 168: https://github.com/db1group/contra-covid19/issues/168

Resultado esperado
Permitir somente caracteres válidos conforme máscara e validar o número de caracteres mínimo a ser preenchido, assim que é tirado o foco dele (isso já acontece em outros campos do sistema).

OBS: Essa regra não está definida nos Requisitos, se tiver dúvida para reproduzir, favor contatar @CristianeBorges05 .

**Comment by bobycachoeira** [comment]
@brendaraylla estou voltando esse card, pois ficaram alguns campos pra traz ainda.

1. **No endereço** faltou essa validação no campo complemento.
Ele não é obrigatório mas se informado no back tem validação para no minimo 3.

2. **Os campos de telefone:**
Residencial e Contato no minimo 10 caracteres.
Celular no minimo 11 caracteres.
Obs.: apenas os números sem considerar a  mascara.

3. **Descrição** da ocupação do suspeito deve validar no minimo 3 caracteres.


Duvidas a disposição.

**Comment by jgracino** [comment]
Validado nos navegadores Chrome e Firefox. Ok para todos os campos citados na issue
