### ISSUE TITLE
Mensagem inválida sobre o campo gestante aparecendo ao clicar no enviar

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#392]
**Comportamento atual**
Ao clicar no botão enviar, aparece a seguinte mensagem:

![image](https://user-images.githubusercontent.com/16705663/80659976-d13ab300-8a60-11ea-9a0c-f50feeb31a98.png)

Conversando com o @ftathiago, vimos que o front não está enviando o valor correto

**Comment by CristianeBorges05** [comment]
E ao selecionar sexo "Masculino" ocorre esse erro:
![image](https://user-images.githubusercontent.com/63747448/80660169-50c88200-8a61-11ea-8fdb-4ef60a78c4b0.png)
