### ISSUE TITLE
Erro no console ao consultar notificação sem data de início dos sintomas.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#394]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Consulta de notificação
Quando eu clicar em Visualizar de alguma notificação
Então a notificação é apresentada, porém no console é gerado o erro: "[Vue warn]: Invalid prop: type check failed for prop "dataInicioDosSintomas". Expected String with value "null", got Null"

Problema
Erro no console ao consultar notificação sem data de início dos sintomas.

[log.txt](https://github.com/db1group/contra-covid19/files/4555529/log.txt)

![4TaSagD3Oa](https://user-images.githubusercontent.com/17462759/80660708-dac51a80-8a62-11ea-904f-3039c32978cf.gif)

**Comment by maykon** [comment]
@nasouza2 @bobycachoeira Já havia aberto esse erro https://github.com/db1group/contra-covid19/issues/381 . O mesmo já foi corrigido apenas aguardando merge e aprovação.

**Comment by bobycachoeira** [comment]
Testes conluídos e efetuados no card #381.

**Comment by bobycachoeira** [comment]
Teste concluídos com sucesso.
