### ISSUE TITLE
Validar CPF da notificação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#399]
Atualmente o sistema permite informar um CPF inválido.
Ex: 
012.365.784-12
258.877.432-54
562.893.214-71
148.690.710-54
999.999.999-99

Permitir informar apenas CPF válido.
729.402.400-60
219.722.430-12
774.594.000-17
037.408.740-74
148.690.710-53

**Comment by CristianeBorges05** [comment]
VALIDADO QA - OK
![RESOLVIDO_Cpf válido](https://user-images.githubusercontent.com/63747448/81132504-09406b00-8f25-11ea-9d76-eb950bdff949.gif)
