### ISSUE TITLE
Validação de obrigatoriedade do campo Tipo de Documento e Número do Documento

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#401]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes/cadastro

SEÇÃO 3 IDENTIFICAÇÂO DO PACIENTE

Deverá ser **obrigatório informar o campo Tipo de Documento e o Número do documento** _somente quando o usuário_ selecionar a **opção "Outro".**

Sempre que o usuário selecionar a opção "Outro" então o campo tipo documento deverá vir desabilitado e preenchido com o tipo "CPF" , obrigando o usuário a informar o "Número de documento".

Quando o usuário selecionar qualquer umas das outras opções (Criança até 12 anos, Em situação de Rua, Estrangeiro, Indígena) então o tipo de documento deve vir pré-selecionado com a opção CPF, porém habilitado para que o usuário possa selecionar outro tipo de doc. Nesse caso os campos **Tipo de Documento** e o **Número do documento** serão de preenchimento **opcional**.

**Comment by ftathiago** [comment]
Feito na issue: https://github.com/db1group/contra-covid19/issues/409
