### ISSUE TITLE
Ao enviar notificação está obrigando informar COMORBIDADES

### ISSUE THREAD

**Issue by CristianeBorges05** [db1group/contra-covid19#402]
Ambiente
https://qa-app.notificasaude.com.br/notificacoes/cadastro

Dado que eu esteja cadastrando uma nova notificação 
Quando eu não seleciono nenhum item da seção 6. COMORBIDADES PRÉVIAS / FATORES DE RISCO
E aciono o botão "Enviar"

Problema
Então o sistema está obrigando informar uma comorbidade, validando o campo "Outros"

VIDA EVIDÊNCIA
![comorbidades](https://user-images.githubusercontent.com/63747448/80766202-3b179300-8b1b-11ea-800b-cf273782a532.gif)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
