### ISSUE TITLE
Campo "Nome da pessoa" liberado para digitação, mesmo quando selecionado "Sem contato".

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#404]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de cadastrar notificação
Quando no campo "Tipo de contato" eu selecionar "Sem contato"
Então o campo "Nome da pessoa" fica desabilitado para digitação.

Problema
Campo "Nome da pessoa" liberado para digitação mesmo quando selecionado "Sem contato".

Resultado esperado
Desabilitar o campo "Nome pessoa", caso no campo "Tipo de contato" tenha sido selecionado "Sem contato".

![xoXS6mcaUH](https://user-images.githubusercontent.com/17462759/80769808-cfd2be80-8b24-11ea-9fd7-8418e7882d88.gif)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 10/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![Mk03Bt5eDW](https://user-images.githubusercontent.com/15328510/81520255-2d7fbb80-931a-11ea-8271-51bcb928c9e0.gif)
