### ISSUE TITLE
Busca de profissão do notificador incorreta após apagar a pesquisa.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#406]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de cadastrar notificação
Quando no campo "Profissão do notificador" eu informar uma profissão e depois apagar
Então o filtro não "zera"; continua trazendo apenas as profissões que se encaixam no filtro que foi apagado.

Problema
Campo "Profissão do notificador" não "zera" depois que a pesquisa foi apagada; continua trazendo somente as profissões que se encaixam no filtro que foi informado e apagado.

Resultado esperado
Trazer todas as profissões sempre que o filtro for apagado.

![IySya6Ngul](https://user-images.githubusercontent.com/17462759/80770338-66ec4600-8b26-11ea-8476-d2b87d835ba7.gif)

**Comment by maykon** [comment]
@nasouza2 realizado a correção.

**Comment by CristianeBorges05** [comment]
**BUG ### Persiste** @nasouza2  e @maykon 
Testei no chrome e no mozilla
![bug profissão](https://user-images.githubusercontent.com/63747448/81127398-74357600-8f14-11ea-945e-7618fc0541d2.gif)

**Comment by nasouza2** [comment]
@maykon situação ainda ocorre; vou retornar o card para "Todo dev".

**Comment by maykon** [comment]
@nasouza2 Corrigido

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 09/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![TSMAgx7NY0](https://user-images.githubusercontent.com/15328510/81482450-8150ae80-920d-11ea-8327-055b3018f1a0.gif)
