### ISSUE TITLE
Campo "Data da coleta" não tem o ícone do calendário.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#408]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de cadastrar notificação
Então o campo "Data da coleta" não tem o ícone do calendário.

Problema
- Campo "Data da coleta" não tem o ícone do calendário.
- Também não tem o asterisco, indicando que ele é obrigatório.

Resultado esperado
Inserir o ícone de calendário para o campo "Data da coleta" e o asterisco, assim é mantido o padrão dos outros campos de data.

![img1](https://user-images.githubusercontent.com/17462759/80771247-2d690a00-8b29-11ea-9d11-e58a1b3beb32.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 10/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/81520087-a3cfee00-9319-11ea-8953-6bc973ece25e.png)
