### ISSUE TITLE
Está sendo obrigatório campo numero documento no back.

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#409]
## Bug Report

**Ambiente**
QA

**Reprodução**
Está obrigando campo tipo documento no back
E não mais deveria.

**Comment by ftathiago** [comment]
O número do documento está sendo utilizado para garantir que não há outra pessoa cadastrada.
Em vista disso estar divergindo do requisito, o que faria do campo documento obrigatório, estou também alterando a pesquisa de pessoas

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/80777408-8772cb00-8b3b-11ea-8903-b20b59e7521e.png)

**Comment by bobycachoeira** [comment]
Testes concluídos com sucesso.
