### ISSUE TITLE
Permitindo data final menor do que data inicial - Exportar

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#422]
Ambiente:

https://qa-app.notificasaude.com.br/notificacoes/exportar

Está permitindo clicar no botão exportar com uma data final menor que a inicial:

![image](https://user-images.githubusercontent.com/16705663/80833881-ed0b9980-8bc5-11ea-8975-44484cffbe4b.png)

**Comportamento/código esperado**
Colocar uma critica para colocar a data final maior que a inicial

**Comment by monitorcosta** [comment]
![image](https://user-images.githubusercontent.com/22552329/81029583-f1e97b00-8e5b-11ea-9668-f7f494765cc4.png)

**Comment by CristianeBorges05** [comment]
Validado QA - OK
![resolvido_data exportar](https://user-images.githubusercontent.com/63747448/81131501-bc0eca00-8f21-11ea-8f3b-52d758ec895e.gif)
