### ISSUE TITLE
Não está trazendo o nome correto do notificador na planilha - Exportar

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#423]
Ambiente: https://qa-app.notificasaude.com.br/notificacoes/exportar

**Comportamento atual**
Não está trazendo o nome correto do notificador:

![image](https://user-images.githubusercontent.com/16705663/80834912-1299a280-8bc8-11ea-9df5-c6fae3bb7c66.png)

**Comment by CristianeBorges05** [comment]
Está exibindo o nome do Notificador mas as outras informações não estão batendo. Vamos ter que olhar juntos antes de liberar.
 @jgracino  @ftathiago  **Talvez seja o caso de abrir outro bug.** 
Mas gravei um exemplo, quando filtro para exportar para 05/05/2020 a 05/05/2020
Veja que não traz a minha notificação que foi cadastrada no dia 05/05/2020 21:16

![Exportar dados](https://user-images.githubusercontent.com/63747448/81129866-258bda00-8f1c-11ea-9ea1-a9531f229e98.gif)

**Comment by monitorcosta** [comment]
Estou verificando @CristianeBorges05 @jgracino

**Comment by monitorcosta** [comment]
Corrigido na execução da Issue #441

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 07/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/exportar

![image](https://user-images.githubusercontent.com/15328510/81358044-c1981b80-90ab-11ea-9d7f-be5dac3fce5e.png)
[_app_excel_12d059c0-ce30-4ef2-869e-08b327f2d2c4.xlsx](https://github.com/db1group/contra-covid19/files/4596450/_app_excel_12d059c0-ce30-4ef2-869e-08b327f2d2c4.xlsx)


> Está exibindo o nome do Notificador mas as outras informações não estão batendo. Vamos ter que olhar juntos antes de liberar.
> @jgracino @ftathiago **Talvez seja o caso de abrir outro bug.**
> Mas gravei um exemplo, quando filtro para exportar para 05/05/2020 a 05/05/2020
> Veja que não traz a minha notificação que foi cadastrada no dia 05/05/2020 21:16
> 
> ![Exportar dados](https://user-images.githubusercontent.com/63747448/81129866-258bda00-8f1c-11ea-9ea1-a9531f229e98.gif)

Sobre essa situação que a Cris havia comentado, foi aberto uma outra issue para isso https://github.com/db1group/contra-covid19/issues/453
