### ISSUE TITLE
No front-end de produção, valor do NODE_ENV está como development

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#425]
## Bug Report

**Comportamento atual**
Ao logar em produção, quando fazemos a verificação do ambiente para carregar ou não o hotjar, nos logs podemos observar que o NODE_ENV está com valor development.
Isso ocorre no arquivo hotjar.js no front.

**Comportamento/código esperado**
No ambiente de produção, a variável de ambiente deve estar com o valor 'prod'.

**Contexto adicional/Screenshots**

![image](https://user-images.githubusercontent.com/5889381/80841920-c86bed80-8bd6-11ea-9929-139b6a54cfa2.png)

**Comment by AndressaKarla** [comment]
@bobycachoeira Quando for publicar em produção lembrar de testar essa issue :)

**Comment by rgsouzabr** [comment]
![NODE_ENV](https://user-images.githubusercontent.com/64052760/81629452-882c1c80-93d9-11ea-8f63-68ca5eee6ec6.PNG)
