### ISSUE TITLE
PERMITIR EDITAR A NOTIFICAÇÃO

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#431]
### **Depende da issue #230** 

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Alguns usuários, com determinada permissão, devem poder editar a notificação.

**Descreva a solução que você gostaria**
Através do token, definir se o usuário pode - ou não - alterar a notificação

**Comment by jgracino** [comment]
Revisado! Criei um novo cadastro, conferi os dados na base, depois editei e conferi novamente na base. Teste OK.
