### ISSUE TITLE
Retirar campo notificacao.bairroId

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#434]
#### Com o passar do tempo, o processo de retirada pode demorar mais. Neste caso, apesar da gravidade baixa, aconselho que seja retirado esse campo assim que possível e o seu PR aceito **APENAS** fora do expediente

**Comportamento atual**
Em acordo com conversa com o Rogério, dia 04/05, o campo notificacao.bairroId não tem utilidade para o sistema, devendo então, ser retirado.

**Comportamento/código esperado**
* [ ] - Avaliar o impacto da retirada do campo, anotando a semântica dele onde quer que seja utilizado;
* [ ] - Substituir os seus pontos de uso por campos corretos, observada a semântica estimada no passo anterior;
* [ ] - Criar uma migration para retirada do campo;

**Contexto adicional/Screenshots**
Hoje ele está sendo preenchido com os dados do bairro do suspeito, quando entretanto, deveria ser preenchido com o bairro da unidade de saúde notificante.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 06/05/2020 no ambiente https://qa-app.notificasaude.com.br/

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-2 sql 2020-05-06 20 50 23](https://user-images.githubusercontent.com/15328510/81239809-38fe7a00-8fdc-11ea-94a3-583f5b62dae2.png)
![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-2 sql 2020-05-06 20 51 12](https://user-images.githubusercontent.com/15328510/81239815-3d2a9780-8fdc-11ea-9c5e-2527f6b049df.png)
![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-2 sql 2020-05-06 20 51 48](https://user-images.githubusercontent.com/15328510/81239822-40258800-8fdc-11ea-808b-5142ebc3ddd6.png)
