### ISSUE TITLE
Alterar regra de consolidação de suspeito.

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#442]
Alterar validação de se a pessoa ja existe para:
Se tiver documento valida por documento.
Se não tiver
Valida por nome do suspeito mai nome da mão.

Para testar criar notificações e validar na tabela "Pessoa" no banco de dados.

**Comment by ftathiago** [comment]
![image](https://user-images.githubusercontent.com/6723988/81131486-b31df880-8f21-11ea-9063-45d5234737cf.png)

**Comment by ftathiago** [comment]
![4sMCaIM44P](https://user-images.githubusercontent.com/6723988/81132578-502e6080-8f25-11ea-9a4f-0b3289f60fce.gif)

**Comment by AndressaKarla** [comment]
Apesar dessa issue ter sido aberta há vários dias, ela não foi cadastrada inicialmente com Projeto e status, acabou ficando no "limbo". Adicionei essas informações hoje (14/05), testei com sucesso nos dias 13/05 e 14/05/2020 no ambiente https://qa-app.notificasaude.com.br/

- Tipo de pessoa "Outro", mesmo CPF, nome suspeito e nome da mãe: 
![4SUwL2dkdl](https://user-images.githubusercontent.com/15328510/81984741-9e212380-960b-11ea-8936-470435796fcf.gif)

- Tipo de pessoa diferente de "Outro" com CPF vazio, mesmo nome suspeito e nome da mãe:
![RCwq4RNqU5](https://user-images.githubusercontent.com/15328510/81984885-da548400-960b-11ea-9f45-19aa7834d8c6.gif)

- Tipo de pessoa diferente de "Outro" com CPF vazio, mesmo nome suspeito e nome da mãe diferente:
![iNuhasV0S4](https://user-images.githubusercontent.com/15328510/81985188-4c2ccd80-960c-11ea-8dcb-60d01a24105b.gif)

**Comment by nasouza2** [comment]
Ao criar ct dessa funcionalidade, incluir o cenário de edição: editar uma notificação informando um documento com notificação já aberta.
