### ISSUE TITLE
Restrição de operações para unidades diferente da Secretaria de Saúde

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#446]
O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.
Atualmente todas as unidades podem excluir a notificação. Isso pode acarretar alguma interação indevida no sistema por má fé.

Atualmente todas as unidades podem visualizar os dados das notificações (botão visualizar da tela de consulta). Entretanto, existe um sigilo de dados. 

Descreva a solução que você gostaria
Apenas os usuários da secretaria de saúde poderem "Excluir" uma notificação".

Todos os usuários podem visualizar a relação de pacientes na tela de consulta. Isso será últil para que as unidades possam localizar pacientes que foram notificados em outra unidade de saúde. Entretanto, apenas os usuários da secretaria de saúde podem visualizar os dados de todas as notificações (botão visualizar na tela de consulta). Outros usários apenas podem visualizar apenas os dados das notificações de sua unidade (botão visualizar na tela de consulta).

Obs: O privilégio pode ser verificado ao clicar no botão. Emitir mensagem "Seu usuário não possui permissão para ....".

Usuários da Secretaria de saúde:
eduardoribeiro@maringa.pr.gov.br
saude_vigilancia01@maringa.pr.gov.br
saude_vigilancia02@maringa.pr.gov.br
saude_vigilancia03@maringa.pr.gov.br

Usuário da Zona Norte (não é da secretaria de saúde):
upa_znorte@maringa.pr.gov.br

**Comment by nasouza2** [comment]
Segundo o Alexandre, esse card tá com problema de atualização no ambiente. Aguardando retorno para iniciar os testes.

**Comment by nasouza2** [comment]
Usuários:
- Secretaria da saúde: test
- Comuns: test2 (Hospital do Câncer de Maringá) e natalia.souza@db1.com.br (Hospital Paraná)

**Comment by nasouza2** [comment]
Usuário comum:
- Pode visualizar as fichas da sua unidade (botão VISUALIZAR).
- Pode visualizar os pacientes incluídos na outra unidade (apenas a listagem; não deve aparecer o botão VISUALIZAR).
- Não pode excluir as fichas (botão EXCLUIR não deve ser apresentado).

Usuário da secretaria de saúde.
- Pode visualizar a ficha de todas as unidades de saúde (botão VISUALIZAR).
- Pode excluir as fichas (botão EXCLUIR).

**Comment by nasouza2** [comment]
Usuário comum:
- Pode visualizar as fichas da sua unidade (botão VISUALIZAR).
- Pode visualizar as fichas de outras unidades (apenas a listagem; não deve aparecer o botão VISUALIZAR).
- Não pode excluir as fichas (botão EXCLUIR não deve ser apresentado).
- Não pode lançar evolução (botão EVOLUÇÃO não deve ser apresentado).

Usuário da secretaria de saúde.
- Pode visualizar a ficha de todas as unidades de saúde (botão VISUALIZAR).
- Pode excluir as fichas (botão EXCLUIR).
- Pode lançar evolução (botão EVOLUÇÃO).

**Comment by nasouza2** [comment]
Ok, validado.

**Comment by nasouza2** [comment]
Casos de teste criados.
