### ISSUE TITLE
Item 10 - Bloquear campos quando inserido SEM CONTATO

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#448]
**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
No item 10 quando seleciona SEM CONTATO os campos "Local de contato e o Nome da pessoa" ficam em abertos e com isso da para digitar dentro.

**Descreva a solução que você gostaria**
Bloquear essa ação, quando inserir SEM CONTATO impedir a digitação nos campos.

**Comment by AndressaKarla** [comment]
Aparentemente essa issue já havia sido relatada e corrigida na issue https://github.com/db1group/contra-covid19/issues/404. Vou fechar essa e mover para "Done"
