### ISSUE TITLE
Busca de unidade incorreta após apagar a pesquisa.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#452]
Ambiente:
https://app.notificasaude.com.br/

1) Primeiro caso:
Dado que eu esteja na tela de cadastrar notificação
Quando no campo "Unidade notificante" eu selecionar uma unidade e depois apagar a unidade selecionada
Então o filtro não "zera"; continua trazendo apenas as unidades que se encaixem no filtro selecionado anteriormente.

2) Segundo caso:
Dado que eu esteja na tela de cadastrar notificação
Quando no campo "Unidade notificante" eu selecionar uma unidade > sair do campo e depois apagar a unidade selecionada
Então o filtro não "zera"; continua trazendo apenas a unidade selecionada anteriormente.

Problema
Campo "Unidade notificante" não "zera" depois que a pesquisa foi apagada.

Resultado esperado
Trazer todas as unidades sempre que o filtro for apagado.

OBS: O primeiro caso só dá para simular em produção, porque em homologação todas as unidades começam com "H".

![mjxSh6a8Av](https://user-images.githubusercontent.com/17462759/81235016-5cbbc300-8fd0-11ea-98ea-b15582f86319.gif)

**Comment by maykon** [comment]
@nasouza2 Corrigido

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 09/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![oIEU10bKmQ](https://user-images.githubusercontent.com/15328510/81482314-82351080-920c-11ea-96d8-bf975d5b9d77.gif)
