### ISSUE TITLE
Não está trazendo os dados corretamente ao filtrar para exportar a planilha excel

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#453]
Ambiente: https://qa-app.notificasaude.com.br/notificacoes/exportar

**Comportamento atual**
Ao colocar a data de 06/05/2020 a 06/05/2020 o sistema não está retornando os dados corretamente

![image](https://user-images.githubusercontent.com/16705663/81241824-cabcb600-8fe1-11ea-8b37-fb840dcae3bc.png)
 
As duas primeiras notificações foram feitas no dia 05/05

![image](https://user-images.githubusercontent.com/16705663/81241879-f475dd00-8fe1-11ea-8703-b214ddf6253d.png)

Acredito que o problema está na hora da notificação

**Comment by AndressaKarla** [comment]
@monitorcosta Talvez seja problema de de diferença de 3 hs do GMT ou UTC. O @ftathiago e @wildeee já resolveram problemas semelhantes dessa diferença de hora, talvez vc possa trocar uma ideia com eles sobre isso 🙂

**Comment by monitorcosta** [comment]
Estava filtrando a consulta pelo campo Notificacao.createAt, corrigido para filtrar pelo campo NotificacaoCovid19.dataHoraNotificacao que é o que é exibido em tela.
Aproveitei e inseri a exportação do campo Notificacao.status que é exibido na listagem de notificação.

**Comment by AndressaKarla** [comment]
@monitorcosta Aparentemente problema ainda ocorre. Issue retornada para "todo dev"

![unknown0](https://user-images.githubusercontent.com/15328510/81355705-b04c1080-90a5-11ea-8709-0431c9a6c837.png)
![unknown1](https://user-images.githubusercontent.com/15328510/81355709-b3470100-90a5-11ea-8e01-0cb08cd349d7.png)
![unknown2](https://user-images.githubusercontent.com/15328510/81355712-b4782e00-90a5-11ea-881d-29386a6552a1.png)

**Comment by monitorcosta** [comment]
@jgracino @AndressaKarla @rgsouzabr 
O problema da data ainda persiste porque na questão da data ao emitir a geração localmente em dev exporta certo e no de QA dá problema porque neste ambiente adiciona 3 horas nos campos datetime. 
Um ponto que dá impedimento a continuidade desta correção é o problema apontado nesta #471

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 09/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![image](https://user-images.githubusercontent.com/15328510/81488893-977a6100-9245-11ea-8e53-d923a261f0d1.png)

Porém descobriu-se um outro problema nesse contexto e foi criado uma issue para isso: https://github.com/db1group/contra-covid19/issues/498
