### ISSUE TITLE
Ao clicar em abrir orientações em outra janela ser direcionado para outra tela com as orientações 

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#459]
**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**

ITEM 12 - Quando clica na opção ALTA COM DETERMINAÇÃO DE ISOLAMENTO DOMICILIAR na parte que esta em azul ABRIR ORIENTAÇÕES EM OUTRA JANELA, era para a pessoa clicar e ser direcionada para essa ficha TERMO DE CONSENTIMENTO LIVRE E ESCLARECIDO que esta em pdf na pagina da prefeitura.

**Descreva a solução que você gostaria**
Adicionar o link para o direcionamento:

http://www2.maringa.pr.gov.br/sistema/arquivos/8fcc967791a9.pdf

**Comment by maykon** [comment]
@100198  já exoste uma issue pra isso, estavamos aguardando o pdf. https://github.com/db1group/contra-covid19/issues/214
