### ISSUE TITLE
Item 9 - Alterar  obrigatoriedade da data de viagem

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#460]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
A data de viagem não é obrigatório no sistema do estado e muitos pacientes não tem a data que foram viajar. Por isso precisa ser retirada. 

**Descreva a solução que você gostaria**
Data de viagem não ser obrigatória.

**Comment by ftathiago** [comment]
@100198 , boa noite. Se você tiver print do erro ficaria mais fácil de saber se o erro ocorre no back ou no front. Se não tiver, de boa, a gente tenta descobrir.

**Comment by ftathiago** [comment]
Pelo que pude apurar ao fazer no teste em qa, este erro acontece no frontend. Desta forma, vou alterar a triagem para o front.

Verifiquei também o código no backend e não há obrigatoriedade de preenchimento do campo. Peço que, caso a data não seja informada, seja enviado ao back o valor null
