### ISSUE TITLE
Nao foi exportado para o excel o usuário que digitou e a situação da notificacao

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#464]
Faltou o campo de "usuário" que digitou a notificação. 

A notificação possui o atributo "userid". É necessário relacionar e buscar em "User.e-mail".
A situação da notificação notificacao.status

Por favor, dar uma validada geral se todos os campos estão sendo exportados. O que foi combinado é que apenas os "IDs" é que não serão. Nesse caso trazer a descrição da tabela relacionada.

**Comment by monitorcosta** [comment]
Inserido na exportação o campo usuarioDigitador (Notificacao.User.Email)
O campo da situação da notificação já foi feito na issue #453.

**Comment by AndressaKarla** [comment]
Segundo o @monitorcosta, aparentemente essa issue estaria com problema de publicação no ambiente, assim como a issue https://github.com/db1group/contra-covid19/issues/446 Aguardando retorno para continuar os testes.

**Comment by monitorcosta** [comment]
@altitdb poderia dar uma olhada no que aconteceu que não atualizou estas alterações no ambiente dos QA's?

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 09/05/2020 no ambiente qa-app.notificasaude.com.br referente ao usuário:
![image](https://user-images.githubusercontent.com/15328510/81481290-4ea2b800-9205-11ea-8325-59fed7dab4b5.png)
![image](https://user-images.githubusercontent.com/15328510/81481294-54989900-9205-11ea-8093-e78b6233abe0.png)
[notificacoes-1589046401735.xlsx](https://github.com/db1group/contra-covid19/files/4604238/notificacoes-1589046401735.xlsx)

Referente aos outros dados da planilha, estão sendo tratados nessas issues https://github.com/db1group/contra-covid19/issues/231 e https://github.com/db1group/contra-covid19/issues/453
