### ISSUE TITLE
Não está salvando sem enviar CPF

### ISSUE THREAD

**Issue by bobycachoeira** [db1group/contra-covid19#465]
## Bug Report

**AMBIENTE**
https://qa-app.notificasaude.com.br/

**REPRODUÇÃO**
Dado que eu esteja criando uma notificação.
E no suspeito coloque ele como OUTRO(numero do documento não é obrigatório).
E preencha todos os outros dados.
Quando tentar enviar a notificação.

**PROBLEMA**
Está apresentando mensagem de CPF invalido.

**RESULTADO ESPERADO**
O CPF(ou numero de documento), só é obrigatório quando o suspeito for OUTRO.
E deveria salvar normalmente.

**Comment by bobycachoeira** [comment]
segue json envoado pelo front:

`{"dataHoraNotificacao":"2020-05-07T23:36:00.000Z","unidadeSaudeId":"d7616e7d-2d89-4c86-b65e-230a39272614","notificadorId":"ac3227a1-8a09-4b5f-93cd-d6ca43b637a4","sintomatico":false,"realizouExamesImagem":false,"dataInicioDosSintomas":null,"userId":"2e439917-3f2a-45b2-9143-aac3bea760d6","nomeNotificador":"teste do cachoeira","profissaoId":"28da7c76-d068-4d31-9013-358bed063b5d","tipoDeContatoComCaso":"SEM_CONTATO","tipoDeLocalDoCaso":null,"nomeDoCaso":null,"observacoes":"","suspeito":{"pessoaId":null,"tipoDocumento":"CPF","numeroDocumento":"","nome":"teste do cachoeira","dataDeNascimento":"2000-10-10","sexo":"M","cep":"34534534","bairroId":"b3cffa5d-2095-4fa3-89c9-8df3b8a1f9ef","nomeDaMae":"teste do cachoeira","ocupacao":"teste do cachoeira","ocupacaoId":"f478a7d6-b28e-4eb4-92d9-89d55bb63fd0","endereco":"teste do cachoeira","numero":"213","complemento":"","municipioId":"ac3227a1-8a09-4b5f-93cd-d6ca43b637a2","telefoneResidencial":"","telefoneContato":"","telefoneCelular":"","gestante":"NAO_APLICADO","tipoPeriodoGestacional":null,"racaCor":"IGNORADO","tipoClassificacaoPessoa":"INDIGENA","uf":"PR"},"sintomas":{"febreAferidaReferida":false,"temperaturaFebre":null,"adinamiaFraqueza":false,"artralgia":false,"calafrios":false,"conjuntivite":false,"coriza":false,"congestaoNasal":false,"dificuldadeDeglutir":false,"gangliosLinfaticos":false,"irritabilidadeOuConfusao":false,"manchasVermelhas":false,"tosse":false,"dorDeGarganta":false,"mialgia":false,"escarro":false,"sibilo":false,"batimentoAsasNasais":false,"dispneia":false,"taquipneia":false,"saturacaoDeOximetriaDePulso":false,"cianoseCentral":false,"diminuicaoDePulsoPeriferico":false,"hipotensao":false,"diarreia":false,"cefaleia":false,"nauseaVomito":false,"tiragemIntercostal":false,"outros":"","existemOutrosSintomas":false},"comorbidades":{"puerperaAte45DiasDoParto":false,"sindromeDeDown":false,"diabetesMellitus":false,"imunodeficiencia":false,"doencaCardioVascularCronica":false,"doencaHepaticaCronica":false,"doencaNeurologicaCronica":false,"doencaRenalCronica":false,"doencaHematologicaCronica":false,"asma":false,"outraPneumopatiaCronica":false,"obesidade":false,"hipertensao":false,"infeccaoHIV":false,"neoplasia":false,"tabagismo":false,"outros":null,"outrasComorbidades":false},"examesImagem":{"raioNormal":false,"raioInfiltradoIntersticial":false,"raioConsolidacao":false,"raioMisto":false,"raioOutro":"","tomografiaNormal":false,"tomografiaVidroFoscoPredominioPerifericoBasal":false,"tomografiaAusenciaDerramePleural":false,"tomografiaAusenciaLinfonodoMediastenal":false,"tomografiaOutro":""},"informacaoComplementar":{"tamiflu":false,"hidroxicloroquina":false,"nomeMedicamento":"","historicoDeViagem":false,"dataDaViagem":null,"localDaViagem":"","recebeuVacinaDaGripeNosUltimosDozeMeses":"NAO"},"vinculoEpidemiologico":{"situacao1":true,"situacao2":false,"nome":""},"conclusaoAtendimento":{"situacaoNoMomentoDaNotificacao":"ALTA_ISOLAMENTO_DOMICILIAR","coletaMaterialParaDiagnostico":false,"tipoLaboratorio":null,"nomeLaboratorioEnvioMaterial":"","dataDaColeta":null,"metodoDeExame":null}}`

**Comment by 100198** [comment]
![image](https://user-images.githubusercontent.com/64612597/81434288-4d598880-913c-11ea-8cc4-e9e1a3ea05da.png)


Fui realizar o teste e o erro ainda persiste

**Comment by nasouza2** [comment]
A regra é a seguinte:
- Se o tipo de paciente for igual a "OUTRO", então o CPF é obrigatório.
- Se o tipo de paciente for diferente de "OUTRO" então nenhum número de documento é obrigatório, independente do tipo de documento selecionado.

O que acontece nesse card: O tipo de paciente é diferente de "OUTRO" e o tipo de documento é igual a CPF; o sistema está dizendo que o CPF é inválido, quando nem deveria validar isso.

@alexunderline favor priorizar esse card, pois ele é impeditivo para entrega em produção.

**Comment by AndressaKarla** [comment]
Aparentemente problema ainda ocorre

![4W4LIBqULx](https://user-images.githubusercontent.com/15328510/81460272-9fb99a00-917a-11ea-857a-ca8941eeeed6.gif)

> A regra é a seguinte:
> 
> * Se o tipo de paciente for igual a "OUTRO", então o CPF é obrigatório.
> * Se o tipo de paciente for diferente de "OUTRO" então nenhum número de documento é obrigatório, independente do tipo de documento selecionado.
> 
> O que acontece nesse card: O tipo de paciente é diferente de "OUTRO" e o tipo de documento é igual a CPF; o sistema está dizendo que o CPF é inválido, quando nem deveria validar isso.
> 
> @alexunderline favor priorizar esse card, pois ele é impeditivo para entrega em produção.
@alexunderline @ftathiago Corrigir conforme comentário acima da @nasouza2 , retornado card para "todo dev"
