### ISSUE TITLE
Permite incluir paciente "criança até 12 anos" com data de nascimento superior.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#468]
Ambiente:
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu esteja na tela de cadastrar notificação
Quando eu selecionar "Criança até 12 anos"
E informar data de nascimento que gere idade superior a 12 anos
E preencher os outros campos obrigatórios
E clicar em Enviar
Então está sendo permitido.

Problema
Está sendo permitido incluir paciente "Criança até 12 anos" com data de nascimento que resulte numa idade maior que 12 anos.

Resultado esperado
Não permitir incluir paciente "criança até 12 anos" com data de nascimento que resulte em uma idade maior que os 12 anos. OBS: Confirmar com o Rogerio se a validação deve ocorrer para 12 anos completos ou incompletos.

![img1](https://user-images.githubusercontent.com/17462759/81360540-8a793880-90b2-11ea-8549-a9ce2740c6ee.png)

**Comment by AndressaKarla** [comment]
@brendaraylla Com 13 ou mais anos está sendo apresentado mensagem de validação corretamente. 

Porém para data de nascimento com exatamente 12 anos 1 dia e 12 anos e 1 mês em relação a data atual, aparentemente está sendo permitido salvar indevidamente:

- 12 anos e 1 dia -> Ex.: data atual: 15/05/2020 - data de nascimento: 14/05/2008
![image](https://user-images.githubusercontent.com/15328510/82108207-4b2a9780-9703-11ea-8cd2-62f998568f56.png)

![G73E5kiZDp](https://user-images.githubusercontent.com/15328510/82108212-541b6900-9703-11ea-992f-da51cd140dc0.gif)

- 12 anos e 1 mês -> Ex.: data atual: 15/05/2020 - data de nascimento: 15/04/2008
![image](https://user-images.githubusercontent.com/15328510/82108329-2125a500-9704-11ea-825c-3cd9028634fd.png)

![pAtp79jR9t](https://user-images.githubusercontent.com/15328510/82108401-8a0d1d00-9704-11ea-9094-efe5a067dc1f.gif)

**Comment by brendaraylla** [comment]
Conforme combinado com o @rgsouzabr não será tratado agora para casos de 12 anos e dias/meses.

**Comment by AndressaKarla** [comment]
> Conforme combinado com o @rgsouzabr não será tratado agora para casos de 12 anos e dias/meses.

Considerando o que a @brendaraylla comentou anteriormente, testes concluídos com sucesso para para menos ou exatamente 12 anos, e para 13 ou mais anos, no dia 19/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![KHwrEopLmy](https://user-images.githubusercontent.com/15328510/82280721-e15df800-9965-11ea-9699-bcdb9f441d01.gif)
