### ISSUE TITLE
Redirecionamento após incluir notificação ou evolução.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#470]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
1) Primeiro caso:
Dado que eu esteja na tela de Cadastrar Notificação
Quando eu enviar a notificação
Então está ocorrendo redirecionamento para a home, ao invés de permanecer na tela de Cadastrar Notificação.

2) Segundo caso:
Dado que eu esteja na tela de Evolução dos pacientes
Quando eu incluir a evolução
Então está ocorrendo redirecionamento para a home, ao invés de permanecer na tela de Evolução dos pacientes.

Problema
Redirecionamento depois de incluir a notificação ou a evolução.

Resultado esperado
Após incluir a notificação ou a evolução, manter o foco na tela de inclusão ou evolução conforme já ocorria anteriormente.

![cTkqy76BKf](https://user-images.githubusercontent.com/17462759/81361336-7a625880-90b4-11ea-818b-35631bf1a457.gif)

**Comment by wildeee** [comment]
Pelo que vi, o @maykon alterou a tela de evolução pra ter esse comportamento. Isso foi solicitado por alguém? Como deve ficar, no final das contas?

**Comment by maykon** [comment]
@nasouza2 @wildeee Foi alterado na evolução pq algumas evoluções encerram a notificação, logo ela não deve ser mais acessada.
No cadastro de notificação, tinha uma rotina q estava ocasionando o reload da aplicação como um todo, achei estranho por isso mudei a forma achando q a intenção era voltar pra pagina anterior. Podemos repensar na forma de limpar os campos sem dar o reload da aplicação.

**Comment by wildeee** [comment]
Como alinhado com o @bobycachoeira, ambos os cadastros, de evolução e notificação agora redirecionam o usuário para a listagem de notificações

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 10/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![LfOKJ7TjVw](https://user-images.githubusercontent.com/15328510/81519052-41c1b980-9316-11ea-96f6-09c84f9aa656.gif)
