### ISSUE TITLE
Incluir variável de ambiente nos ambientes de QA e PROD

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#472]
VUE_APP_ORIENTATIONS_PDF=http://www2.maringa.pr.gov.br/sistema/arquivos/8fcc967791a9.pdf

**Comment by AndressaKarla** [comment]
Aparentemente essa issue estaria com algum problema de publicação no ambiente de QA, assim como as issues https://github.com/db1group/contra-covid19/issues/465, https://github.com/db1group/contra-covid19/issues/464, https://github.com/db1group/contra-covid19/issues/446. Aguardando retorno para continuar os testes.

**Comment by wildeee** [comment]
@maykon Algum problema ocorreu nessa atividade.
Coloquei um console,log para verificar o valor que está chegando, mas o resultado é esse:

![image](https://user-images.githubusercontent.com/5889381/81482084-d63ef580-920a-11ea-9afa-d0cf770da29b.png)

**Comment by maykon** [comment]
@wildeee @AndressaKarla Eu havia colocado no terraform, mas parece q ele não executa automático. Inclui a variável na mão e rodei um novo build, agora está abrindo o PDF.

**Comment by wildeee** [comment]
@100198 Agora sim, pode testar o PDF que tá funcionando

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 10/02/2020 no ambiente de QA https://qa-app.notificasaude.com.br/notificacoes/cadastro

![cQdLTLRxE6](https://user-images.githubusercontent.com/15328510/81517290-d45f5a00-9310-11ea-816c-e11b914455df.gif)

[8fcc967791a9.pdf](https://github.com/db1group/contra-covid19/files/4607186/8fcc967791a9.pdf)

Ainda permanecerá em "Em teste" e com a tag "ImpedimentoQA" para ser testado em produção também quando for liberado versão para produção
