### ISSUE TITLE
BUGs - Notificação triplicada na exportação e não encontrada no sistema

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#475]
**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**

RECEBI DOIS BUGS QUE ACREDITO TEREM RELAÇÃO POR ISSO CADASTREI JUNTOS:

1 -  Ao exportar percebi que uma notificação estava triplicada e mesmo assim não aparecia na lista de notificações na página "consultar notificações"

2 - Segue a pagina de consulta. Pedi para o notificador inserir a ficha as 20:30. Depois disso a ficha que não aparecia na pagina de consulta apareceu. Mas ao exportar a planilha as 21:20 continua triplicada a notificação. Aparentemente foi tentado incluir 3 vezes a mesma ficha por pessoas diferentes. Mas a inclusão feita as 20:30 não aparecia. Achei que depois disso talvez aparecesse 4 notificações.

**Descreva a solução que você gostaria**

Encontrar o motivo do por que a notificação foi triplicada e por que não está aparecendo para ser consultado no sistema

Imagem da planilha:
![IMG-20200507-WA0063](https://user-images.githubusercontent.com/64612597/81413072-35bdd800-911b-11ea-9114-41697138e11b.jpg)

Imagem da tela de consulta:
![Pagina da consulta](https://user-images.githubusercontent.com/64612597/81419583-dc5aa680-9124-11ea-8ffe-dbdc1d3abde7.jpg)

**Comment by monitorcosta** [comment]
Na Issue #441 foi inserido filtro para não exportar as notificações com status "Excluída" e na Issue  #453 foi inserido a exportação do campo status da notificação.
Seria interessante alguém que tem acesso ao ambiente de produção efetuar um teste para validar se o erro persiste.

@100198 @rgsouzabr

**Comment by AndressaKarla** [comment]
> Na Issue #441 foi inserido filtro para não exportar as notificações com status "Excluída" e na Issue #453 foi inserido a exportação do campo status da notificação.
> Seria interessante alguém que tem acesso ao ambiente de produção efetuar um teste para validar se o erro persiste.
> 
> @100198 @rgsouzabr

@rgsouzabr  Aparentemente após os ajustes que o @monitorcosta mencionou no comentário anterior, e testando no ambiente de produção, no dia 15/05/2020, no excel estaria sendo apresentado apenas 1 registro do "HEITOR URNAU SILVA", o mesmo pesquisado no sistema (07/05/2020 20:33) dos prints que a @100198 havia enviado na descrição do card, segue print evidenciando essa situação:

![image](https://user-images.githubusercontent.com/15328510/82107118-a2c50500-96fb-11ea-9baf-7beb4ee39ca0.png)
