### ISSUE TITLE
Filtro de período da exportação de notificação para excel ainda está adicionando três horas no select/consulta no back

### ISSUE THREAD

**Issue by AndressaKarla** [db1group/contra-covid19#498]
## Bug Report

**Comportamento atual**
A consulta/select que o back faz para montar a planilha ainda está com o problema de adicionar 3 horas

**Comportamento/código esperado**
A consulta/select que o back faz para montar a planilha não deveria adicionar 3 horas

**Comment by monitorcosta** [comment]
- Atualmente o front envia ao back uma data em string simples neste formato “YYYY-MM-DD”. Ex do request: http://localhost:3000/api/notificacao-gera-excel?dataInicial=2020-05-06&dataFinal=2020-05-06;
- O campo para filtrar o período da notificação é NotificacaoCovid19.dataHoraNotificacao, que grava data e hora;
- A data inicial precisa ser na primeira hora do dia (00:00:00.000) e data final na última hora do dia (23:59:59.999);
- Localmente funciona corretamente a consulta;
- No ambiente dos QA’s está adicionando três horas na data inicial e na data final, PROVAVELMENTE ao traduzir os parâmetros do sequelize para a select;
- Nos testes durante o atendimento da Issue #453 não se conseguiu identificar a causa.
