### ISSUE TITLE
Criar tabelas Fatos - BI

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#499]
Requisitos anexo ao email
[Requisitos BI.docx](https://github.com/db1group/contra-covid19/files/4605826/Requisitos.BI.docx)
[SimulacoesBI.xlsx](https://github.com/db1group/contra-covid19/files/4605827/SimulacoesBI.xlsx)

**Comment by maykon** [comment]
Foi criado as tabelas:
* public."AprovacaoDado"
* public."FatoNotificacaoCovid19"
* public."DmPaciente"
* public."DmLocalizacao"

Views:
* public.vwboletim
* public.vwaprovacoes
* public.vwfato
* public.ultimaevolucao

Functions: 
*  public.definirfato
* public.obterboletim
* public.temcomorbidade
* public.faixaetaria
* public.idadeatual
* public.definirdimensaopaciente
* public.definirdimensaolocalizacao

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA
**- Tabelas**

![DBeaver 6 0 0 2020-05-25 22 43 21](https://user-images.githubusercontent.com/15328510/82852885-820a6580-9eda-11ea-83c0-6df3f2ed0e39.png)

![DBeaver 6 0 0 2020-05-25 22 43 54](https://user-images.githubusercontent.com/15328510/82852890-846cbf80-9eda-11ea-93a3-e6f477027b81.png)

![DBeaver 6 0 0 2020-05-25 22 44 38](https://user-images.githubusercontent.com/15328510/82852892-859dec80-9eda-11ea-94c4-ac275e652163.png)

![DBeaver 6 0 0 2020-05-25 22 45 55](https://user-images.githubusercontent.com/15328510/82852893-86368300-9eda-11ea-8500-121ee4e08382.png)

![DBeaver 6 0 0 2020-05-25 22 46 20](https://user-images.githubusercontent.com/15328510/82852895-8767b000-9eda-11ea-973e-6123f130053b.png)

![DBeaver 6 0 0 2020-05-25 22 47 07](https://user-images.githubusercontent.com/15328510/82852897-88004680-9eda-11ea-843e-8bf7cb687694.png)

![DBeaver 6 0 0 2020-05-25 22 49 06](https://user-images.githubusercontent.com/15328510/82852901-89317380-9eda-11ea-9c03-225b0cda0356.png)


**- Functions**

![DBeaver 6 0 0 2020-05-25 22 50 24](https://user-images.githubusercontent.com/15328510/82852969-b67e2180-9eda-11ea-85b8-bba1d4409562.png)

![DBeaver 6 0 0 2020-05-25 22 50 45](https://user-images.githubusercontent.com/15328510/82852972-b8e07b80-9eda-11ea-858f-4a987b14ac79.png)
