### ISSUE TITLE
Criar graficos

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#501]
[Requisitos Graficos.docx](https://github.com/db1group/contra-covid19/files/4609159/Requisitos.Graficos.docx)

**Comment by ftathiago** [comment]
Seria interessante a gente bolar uma estratégia de transmissão desses dados. Se concentrar o processamento na nuvem, ela pode ficar um pouco clara. Talvez uma forma seja enviar os dados e o frontend fazer a transformação deles. Pode ser interessante a gente sentar pra pensar essa solução.
