### ISSUE TITLE
Campo NOME não aceitar inserir números, aceitar somente letras.

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#504]
**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**

O campo nome está aceitando dados numéricos.
Favor se possível limitar para somente letras... pois os usuários estão incluindo o CPF no campo nome.

**Descreva a solução que você gostaria**
No campo nome não aceitar inserir números, e sim, apenas letras.

**Comment by AndressaKarla** [comment]
@100198 esse caso que vc descreveu já havia sido relatado nessa outra issue que está em desenvolvimento: https://github.com/db1group/contra-covid19/issues/389
