### ISSUE TITLE
Processar os fatos diariamente

### ISSUE THREAD

**Issue by maykon** [db1group/contra-covid19#505]
Deve ser criado um mecanismo para diariamente processar os fatos e criar as dimensões, que serão usadas para extrair os dados dos suspeitos, confirmados, etc.

**Comment by maykon** [comment]
Não será mais processado automaticamente, mas foi criado mecanismos pra gerar os fatos, que será chamado na tela de aprovação.

Para criar os fatos baseados na aprovação pode ser rodado a consulta:
-- Vai criar cada fato baseado na evolução dos casos por dia
select definirFato(dtaprovacao) from vwaprovacoes;

Se quiser processar apenas um dia pode ser rodado:
select definirFato('2020-05-16')

Para retornar o boletim:
select * from vwboletim

**Comment by maykon** [comment]
Foi criado uma nova rotina para a geração dos fatos:

-- Pega todas as evoluções por data de criação de um dia anterior a partir das 13h (2020-05-24 13:00:00) até as 12:59:59 do dia (2020-05-25 12:59:59)
select definirfatodia('2020-05-25');
-- Gera os registros na tabela DmPaciente, DmLocalizacao e FatoNotificacaoCovid19.

-- Realiza o fechamento do boletim do dia informado
select realizarfechamento('2020-05-25')
-- Insere um registro na tabela AprovacaoDado baseado no dia definido e atualiza a dtFechamento em todas as evoluções do período informado (2020-05-24 13:00:00 - 2020-05-25 12:59:59).

**Comment by maykon** [comment]
As views abaixo foram criados para mostrar os dados do boletim com base nos fatos e/ou fechamentos.
* vwboletimdia
* vwboletimdiario
* vwboletimresumido
* vwboletimtotal

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA:

> -- Pega todas as evoluções por data de criação de um dia anterior a partir das 13h (2020-05-24 13:00:00) até as 12:59:59 do dia (2020-05-25 12:59:59)
> select definirfatodia('2020-05-25');

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-5 2020-05-25 21 06 42](https://user-images.githubusercontent.com/15328510/82853328-deba5000-9edb-11ea-951c-fbd338bd24b3.png)


> -- Gera os registros na tabela DmPaciente, DmLocalizacao e FatoNotificacaoCovid19.

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-6 2020-05-25 21 07 06](https://user-images.githubusercontent.com/15328510/82853362-f691d400-9edb-11ea-84ed-76a69e5ca1a7.png)

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-7 2020-05-25 21 08 32](https://user-images.githubusercontent.com/15328510/82853413-1628fc80-9edc-11ea-9d6a-65df98adc6ca.png)

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-24 2020-05-25 21 47 59](https://user-images.githubusercontent.com/15328510/82853491-4b354f00-9edc-11ea-8fd0-2ce8fe0c94fd.png)

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-4 2020-05-25 22 19 32](https://user-images.githubusercontent.com/15328510/82853532-67d18700-9edc-11ea-8bde-8767699646c3.png)

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-4 2020-05-25 22 21 17](https://user-images.githubusercontent.com/15328510/82853554-77e96680-9edc-11ea-953e-362a6af33710.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA:
> -- Realiza o fechamento do boletim do dia informado
> select realizarfechamento('2020-05-25')

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-9 2020-05-25 21 13 53](https://user-images.githubusercontent.com/15328510/82853839-255c7a00-9edd-11ea-8e82-d6c1f150a4da.png)

> -- Insere um registro na tabela AprovacaoDado baseado no dia definido e atualiza a dtFechamento em todas as evoluções do período informado (2020-05-24 13:00:00 - 2020-05-25 12:59:59).

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-10 2020-05-25 21 14 38](https://user-images.githubusercontent.com/15328510/82853905-550b8200-9edd-11ea-850e-b8f0961172b2.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA:
> As views abaixo foram criados para mostrar os dados do boletim com base nos fatos e/ou fechamentos.
> 

![Covid-19 Notificações - Google Chrome 2020-05-25 22 29 21](https://user-images.githubusercontent.com/15328510/82854104-d2cf8d80-9edd-11ea-88ab-ef025dd2aa33.png)

![Covid-19 Notificações - Google Chrome 2020-05-25 22 28 08](https://user-images.githubusercontent.com/15328510/82854140-e844b780-9edd-11ea-9266-6be96aa5d278.png)

![Covid-19 Notificações - Google Chrome 2020-05-25 22 27 51](https://user-images.githubusercontent.com/15328510/82854185-15916580-9ede-11ea-9c13-37da852f70c2.png)

![Covid-19 Notificações - Google Chrome 2020-05-25 22 27 36](https://user-images.githubusercontent.com/15328510/82854219-2cd05300-9ede-11ea-8b21-d02cf033d08a.png)


> * vwboletimdia

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-11 2020-05-25 22 09 32](https://user-images.githubusercontent.com/15328510/82854053-b5022880-9edd-11ea-8389-117439429bbf.png)

> * vwboletimdiario

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-12 2020-05-25 22 11 18](https://user-images.githubusercontent.com/15328510/82854312-7456df00-9ede-11ea-989c-024592417b28.png)


> * vwboletimresumido

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-13 2020-05-25 22 13 04](https://user-images.githubusercontent.com/15328510/82854346-8e90bd00-9ede-11ea-8ecd-28524f1def60.png)


> * vwboletimtotal

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-14 2020-05-25 22 13 25](https://user-images.githubusercontent.com/15328510/82854365-9a7c7f00-9ede-11ea-8760-ec1b63ab3641.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA:
- ultimaevolucao

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-22 2020-05-25 21 29 54](https://user-images.githubusercontent.com/15328510/82854488-f47d4480-9ede-11ea-9f0b-9512ab81fb77.png)

- vwaprovacoes

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-23 2020-05-25 21 31 46](https://user-images.githubusercontent.com/15328510/82854503-07901480-9edf-11ea-8722-eaf3a4e683b5.png)

- vwboletimacumulado

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-3 2020-05-25 22 03 12](https://user-images.githubusercontent.com/15328510/82854600-48882900-9edf-11ea-8751-50b9ce37dc47.png)

- vwevolucao

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-15 2020-05-25 21 19 52](https://user-images.githubusercontent.com/15328510/82854710-a583df00-9edf-11ea-8437-e1e3c2cfd3b1.png)

- vwevolucaofechamento

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-3 2020-05-25 22 40 14](https://user-images.githubusercontent.com/15328510/82854831-f5fb3c80-9edf-11ea-8029-aeb122446a03.png)

- vwlocalizacao

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-17 2020-05-25 21 23 24](https://user-images.githubusercontent.com/15328510/82854887-1f1bcd00-9ee0-11ea-8428-aa05f9cc1a06.png)

- vwlocalizacaopaciente

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-18 2020-05-25 21 24 09](https://user-images.githubusercontent.com/15328510/82854914-3490f700-9ee0-11ea-8dba-6a028a25f2eb.png)

- vwnotificalocalizacao

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-19 2020-05-25 21 24 43](https://user-images.githubusercontent.com/15328510/82854987-62763b80-9ee0-11ea-845b-36b914a6ad2e.png)

- vwnotificapaciente

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-20 2020-05-25 21 25 31](https://user-images.githubusercontent.com/15328510/82855006-73bf4800-9ee0-11ea-897a-2d1044100de7.png)

- vwperfilpaciente

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-21 2020-05-25 21 28 04](https://user-images.githubusercontent.com/15328510/82855062-a10bf600-9ee0-11ea-90e5-a166c34b5256.png)

![DBeaver 6 0 0 - _PostgreSQL - postgres_ Script-21 2020-05-25 21 28 42](https://user-images.githubusercontent.com/15328510/82855070-abc68b00-9ee0-11ea-8061-5134e1ef98c9.png)
