### ISSUE TITLE
Ficha errada foi excluída, e a ficha correta que foi cadastrada não aparece para ser consultada.

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#506]
**Comportamento atual**
Após a exclusão de uma ficha notificada com erro e cadastro de outra ficha, a ficha nova não está aparecendo no relatório/lista "consultar notificação".

Exemplo paciente:
Benjamim (com M) de Oliveira Gonçalves - FICHA EXCLUIDA/ERRADA
Benjamin (com N) de Oliveira Gonçalves - FICHA CORRETA

**Comportamento/código esperado**
Encontrar o erro do porque a ficha não está aparecendo no sistema.

**Comment by maykon** [comment]
@100198 O usuário está aparecendo corretamente, acontece q como os dados CPF, mãe dele são iguais ele não cria uma nova pessoa, ele registra com a pessoa antiga.

Se for alterar o nome da pessoa, teria q pensar em uma outra solução, não excluir a ficha e cadastrar novamente. Poderia ser uma feature no visualizar ou editar da ficha.

![image](https://user-images.githubusercontent.com/14884/81563393-95f78880-936c-11ea-8030-fc42121cdd04.png)

**Comment by AndressaKarla** [comment]
@100198 @rgsouzabr Verificar se após a publicação em produção da funcionalidade de edição de notificação, se esse problema seria resolvido apenas editando o nome do paciente
