### ISSUE TITLE
Barra de rolagem na visualização da notificação no meio da página e não no início.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#509]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Consultar Notificação
Quando eu clicar em Visualizar numa notificação para mais baixo na tela 
Então a consulta da notificação também virá mais no meio da tela e não no início.

Problema
Foco da visualização da notificação no meio da página e não no início.

Resultado esperado
Ao visualizar a notificação, trazer a barra de rolagem sempre no início da notificação.

![PpCAugdRXV](https://user-images.githubusercontent.com/17462759/81568123-bbd45b80-9373-11ea-98a3-a59a25009cf6.gif)

**Comment by jgracino** [comment]
Validação ok nos navegadores Chorme e Firefox

**Comment by nasouza2** [comment]
Caso de teste atualizado.
