### ISSUE TITLE
Tela para aprovação de dados para divulgação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#512]
Requisito anexo
[Requisitos Fechamento Indicadores.docx](https://github.com/db1group/contra-covid19/files/4617430/Requisitos.Fechamento.Indicadores.docx)

**Comment by jgracino** [comment]
Aguardando a parte da Brenda e do MK, a pedido do Alexandre

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/05/2020 no ambiente https://qa-app.notificasaude.com.br/fechamento e na base de dados de QA:

select definirfatodia('aaaa-mm-dd');
select definirfatonotificacao();

![3TxTQhDPdM](https://user-images.githubusercontent.com/15328510/82857816-758d0980-9ee8-11ea-9b20-d3e9f9baddfa.gif)

![PUMLkuHcTj](https://user-images.githubusercontent.com/15328510/82857913-bbe26880-9ee8-11ea-979d-c0e487fb30b2.gif)
