### ISSUE TITLE
Permitir remover a evolução

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#513]
Depois da confirmação de fechamamento uma evolução não poderá ser mais alterada.

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Quando uma evolução é informada errada não possível alterá-la.

**Descreva a solução que você gostaria**
Permitir remover uma evolução.

Uma evolução não poderá ser excluida ou incluida com a data de evolução que já tenha sido realizado o fechamento.

Vamos facilitar a entrada de dados da notificação devemos alterar a forma de visualizar a "condição atual do paciente".
1) Retirar "SUSPEITO". Pois, o sistema está lançando automaticamente a condição.
2) Conforme a última condição lançada o sistema deverá mostrar algumas condição. Sendo que quando for:
    SUSPEITO: CONFIRMADO / ENCERRADO / DESCARTADO
    CONFIRMADO : CURADO / OBITO
    

**Descreva qualquer alternativa considerada**
Ao contrário de liberar para editar. Permitir remover e o usuário cadastra novamente.

**Documentação, Adoção, Estratégia de migração**

**Comment by 100198** [comment]
Estou realizando os testes e quero deixar registrado dois cenários: 

Quando informo a data e horário anterior que a notificação criada o sistema não deixa evoluir, com isso está ok.

Quando faço a evolução da notificação para CURADO, ÓBITO, ENCERRADO e DESCARTADO os campos de ATUALIZAÇÃO congelam impossibilitando de incluir mais evolução e  ao excluir a evolução com esses respectivos status ela descongela possibilitando você cadastrar uma evolução novamente.

**Comment by nasouza2** [comment]
Aguardando confirmação da Thaynara sobre qual é o processo correto. Atualmente não posso incluir evolução em notificação já encerrada, porém posso excluir a evolução que encerrou a notificação. Pela descrição do card, isso não deveria ser possível.

**Comment by nasouza2** [comment]
Quando for implementado o fechamento, os casos de teste desse cenário devem ser atualizados.
