### ISSUE TITLE
Ajuste na mensagem do campo Número do documento, quando selecionado CPF.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#515]
Ambiente
https://qa-app.notificasaude.com.br/

Reprodução
Dado que eu esteja na tela de Cadastrar Notificação
Quando eu selecionar o tipo de paciente "Outros"
E iniciar a digitação do CPF
Então será apresentada a mensagem: "O campo deve possuir 14 caracteres".

Problema
Mensagem indicando que o campo CPF deve possuir 14 caracteres, mas o documento possui 11 caracteres.

Resultado esperado
Alterar o número de caracteres de 14 para 11, visto que o sistema está formatando automaticamente a máscara do campo.

![img1](https://user-images.githubusercontent.com/17462759/81614281-31f9b200-93b6-11ea-967f-19a808c8a037.png)

**Comment by jgracino** [comment]
Validação ok nos navegadores Chrome e Firefox
