### ISSUE TITLE
Abrir PDF está com erro

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#523]
## Feature Request

Na tela de notificação no link de "Abrir PDF" está com erro.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 12/05/2020 no ambiente de produção https://app.notificasaude.com.br/notificacoes/cadastro

![LDNkS1ppqi](https://user-images.githubusercontent.com/15328510/81757196-70659e80-9494-11ea-9407-d23fb4cedd46.gif)
