### ISSUE TITLE
Nome ultrapassou o label da unidade notificante no canto superior esquerdo

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#524]
Loguei com o usuário que possui vinculo com unidade de saúde grande.

Exemplo de unidade : UNIDADE DE PRONTO ATENDIMENTO UPA ZONA NORTE

O label não foi apresentando corretamente gerando um layout "bagunçado".

![image](https://user-images.githubusercontent.com/15328510/81630606-74ce8080-93dc-11ea-909d-996fb22a9076.png)

**Comment by wildeee** [comment]
A estrutura do header foi alterada em vários pontos. Ainda não está 100% mobile, mas agora o usuário consegue "se virar", se precisar do mobile.

**Comment by AndressaKarla** [comment]
@wildeee No Chrome aparentemente problema foi resolvido, porém no Firefox problema ainda ocorre. Retornado issue para "todo dev"

![image](https://user-images.githubusercontent.com/15328510/81756658-bae61b80-9492-11ea-94b2-231ce19692e5.png)

**Comment by wildeee** [comment]
Corrigindo isso junto com a issue #541

**Comment by wildeee** [comment]
Não cheguei a testar no firefox, mas como boa parte do header foi refatorado, eu acredito que funcione dessa vez. Se não funcionar, me avisa que eu baixo o firefox aqui.

**Comment by jgracino** [comment]
Validado nos dois navegadores: Chrome e Firefox, nos dois está ok

**Comment by nasouza2** [comment]
Criar caso de teste desse caso, quando tivermos o processo de incluir unidade de saúde.
