### ISSUE TITLE
Remover termo técnico da mensagem e incluir ponto final.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#528]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha incluído uma notificação com descrição da ocupação extensa
Quando eu clicar em Enviar
Então é apresentada a mensagem: ""suspeito.ocupacao" deve constar no máximo 60 caracteres".

Problemas
a) Remover "suspeito.ocupação" da mensagem.
b) Inserir ponto final na mensagem.

Resultado esperado
Descritos junto com os problemas. Sugestão da mensagem: "Descrição da ocupação deve conter no máximo 60 caracteres".

![img1](https://user-images.githubusercontent.com/17462759/81698857-f229dd80-943c-11ea-9fd8-568cb4f74e10.png)

**Comment by brendaraylla** [comment]
![image](https://user-images.githubusercontent.com/31936432/81728154-64f88000-9460-11ea-9b4d-1d79109ae303.png)

Tratado no front p nao ser possível mandar a requisição de salvar caso o campo tenha mais caracteres que o permitido

**Comment by brendaraylla** [comment]
Verificar se atende ou é necessário correção no backend

**Comment by jgracino** [comment]
Validado no Chrome e Firefox

**Comment by nasouza2** [comment]
Caso de teste atualizado.
