### ISSUE TITLE
Não limpa mensagem de campo obrigatório quando desmarcado.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#529]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha incluído uma notificação com o campo "Sintomático" marcado
E não tenha informado a data de início dos sintomas
E tenha clicado em Enviar
E no campo "Data inicio dos sintomas" tenha sido apresentada a mensagem "O campo é obrigatório para caos sintomáticos"
Quando eu desmarcar o campo "Sintomático" 
Então a mensagem continuará sendo exibida indevidamente.

Problemas
Mensagem de obrigatoriedade continua sendo apresentada, mesmo campo "Sintomático" estando desmarcado.

Resultado esperado
Se o campo "Sintomático" for desmarcado, não apresentar a mensagem: "O campo é obrigatório para casos sintomáticos.".

![Zg97GY3Dvj](https://user-images.githubusercontent.com/17462759/81700916-b0e6fd00-943f-11ea-9cba-eec1f3c9bc7a.gif)

**Comment by jgracino** [comment]
Validação OK no Chrome e Firefox
