### ISSUE TITLE
Não permitir data de nascimento igual a hoje.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#533]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
1) Primeiro caso:
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu informar uma data de nascimento igual a hoje 
Então será permitido.

2) Segundo caso:
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu informar uma data de nascimento superior a hoje 
Então no campo será apresentado: "Informe uma data igual ou anterior ao dia de hoje.".

Problema
Campo data de nascimento permite informar data superior a hoje. 

Resultados esperados
- Ajustar o campo data de nascimento, para não permitir informar data de nascimento igual a hoje. Isso porque mesmo que o campo esteja permitindo, não é possível concluir a inclusão da notificação se a data de nascimento for igual a hoje.
- Ajustar também a mensagem do campo, removendo a parte de "igual".

![img1](https://user-images.githubusercontent.com/17462759/81726409-b18e8c00-945d-11ea-9140-eddcc59e88b0.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 15/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![KASKuJ0biS](https://user-images.githubusercontent.com/15328510/82107802-baeb5300-9700-11ea-8a94-c0d6ffd75e82.gif)
