### ISSUE TITLE
Obrigatoriedade do campo "Descrição da ocupação".

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#534]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando no campo "Ocupação" eu selecionar "Outro"
Então o campo "Descrição da ocupação" não é obrigatório.

Problemas
Descrição da ocupação não é obrigatória, quando a ocupação é "Outro"

Resultado esperado
Ajustar o campo "Descrição da ocupação" para ser obrigatório quando no campo "Ocupação" for selecionado "Outro".

![img2](https://user-images.githubusercontent.com/17462759/81727189-f4049880-945e-11ea-9b81-6c138bc32ffd.png)

![img1](https://user-images.githubusercontent.com/17462759/81727187-f36c0200-945e-11ea-8f30-b9002d39fbee.png)

**Comment by jgracino** [comment]
Agora, se eu coloco a opção "Outro", ele obrigada o campo "Descrição da ocupação", porém, se volto a escolher outra opção, na qual o campo "Descrição da ocupação" não deveria ser obrigatório, está obrigando: 
![image](https://user-images.githubusercontent.com/16705663/81942632-bcb5f900-95d0-11ea-9316-b6472bdf9ebc.png)

**Comment by brendaraylla** [comment]
@jgracino nao consegui reproduzir. Pode verificar novamente se isso realmente ocorre, por gentileza?!

**Comment by jgracino** [comment]
O Erro ocorre quando digita "Outro" no campo "ocupação":

![yMSkBxnFeu](https://user-images.githubusercontent.com/16705663/82099251-45ba5680-96dd-11ea-88a1-4b7091544d1c.gif)

**Comment by AndressaKarla** [comment]
> Ambiente
> https://qa-app.notificasaude.com.br
> 
> Reprodução
> Dado que eu esteja na tela de Cadastro de Notificação
> Quando no campo "Ocupação" eu selecionar "Outro"
> Então o campo "Descrição da ocupação" não é obrigatório.
> 
> Problemas
> Descrição da ocupação não é obrigatória, quando a ocupação é "Outro"
> 
> Resultado esperado
> Ajustar o campo "Descrição da ocupação" para ser obrigatório quando no campo "Ocupação" for selecionado "Outro".
> 
> ![img2](https://user-images.githubusercontent.com/17462759/81727189-f4049880-945e-11ea-9b81-6c138bc32ffd.png)
> 
> ![img1](https://user-images.githubusercontent.com/17462759/81727187-f36c0200-945e-11ea-8f30-b9002d39fbee.png)

Testes dessa regra concluídos com sucesso no dia 15/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

**Comment by AndressaKarla** [comment]
> O Erro ocorre quando digita "Outro" no campo "ocupação":
> 
> ![yMSkBxnFeu](https://user-images.githubusercontent.com/16705663/82099251-45ba5680-96dd-11ea-88a1-4b7091544d1c.gif)

Testes dessa situação também concluídos com sucesso no dia 15/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![GmntGyd9Ui](https://user-images.githubusercontent.com/15328510/82106495-c1c19800-96f7-11ea-9f0c-2b246f080fa4.gif)

**Comment by nasouza2** [comment]
Casos de testes criados e atualizados.
