### ISSUE TITLE
Obrigatoriedade da seção 8 - REALIZADO COLETA DE MATERIAL PARA DIAGNÓSTICO.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#539]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu esteja na tela de Cadastro de Notificação
Quando eu selecionar Sim na seção 8.REALIZADO COLETA DE MATERIAL PARA DIAGNÓSTICO
E não preencher os demais campos
E clicar em Enviar
Então está sendo permitido.

Problemas
Está sendo permitido incluir notificação com coleta de exame, sem informar os dados da coleta.

Resultado esperado
Ajustar obrigatoriedade dos campos da seção 8:
- Se marcado "Sim", então os campos Data da coleta, tipo do laboratório e método do exame devem ser obrigatórios.
- Quando o tipo de laboratório for "Laboratório de rede PRIVADA", então o campo "Nome do laboratório" também deve ser obrigatório.

![img1](https://user-images.githubusercontent.com/17462759/81746734-5bc9dc00-947d-11ea-96bc-8e59505f857b.png)

**Comment by jgracino** [comment]
Validação OK nos navegadores Chrome e Firefox
