### ISSUE TITLE
Campo Data de Nascimento com informação errada ao exportar excel

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#543]
Ambiente: https://qa-app.notificasaude.com.br/notificacoes/exportar

**Comportamento atual**
No formulário e na base, a data de nascimento correta seria 30/12/1988, mas na planilha está vindo 29/12/1988

Na base:
![image](https://user-images.githubusercontent.com/16705663/81814511-43020a80-94ff-11ea-8975-40c7aac7790b.png)

No Excel:

![image](https://user-images.githubusercontent.com/16705663/81814730-7f356b00-94ff-11ea-954a-25a7d0862ce4.png)

**Comment by monitorcosta** [comment]
Para quem efetuar o teste por favor observar se estão indo corretamente também os campos  dataDeInicioDosSintomas, dataDaColeta e dataDaViagem que estão no mesmo cenário do campo de data de nascimento.

@jgracino @AndressaKarla @nasouza2 @100198 @rgsouzabr

**Comment by nasouza2** [comment]
Ok, validado. Conferidos os dados de todas as datas (data de nascimento, data de início dos sintomas data de coleta e data de viagem). Foram identificados outros pontos para ajustes na planilha, que serão tratados por outro card.

![img1](https://user-images.githubusercontent.com/17462759/81845902-a2741080-9527-11ea-99d2-07cbc168c56c.png)
