### ISSUE TITLE
Evolução sendo duplicada

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#545]
**Comportamento atual**
Encontramos esse problema em produção, quando evoluímos uma notificação ela está sendo salva duas vezes 

**Comportamento/código esperado**
Identificar o motivo disso estar ocorrendo e fazer a correção.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/64612597/81820195-ae9ba600-9506-11ea-9d2d-af15da769e71.png)

**Comment by AndressaKarla** [comment]
@rgsouzabr Verificar se esse caso ainda estaria ocorrendo em produção
