### ISSUE TITLE
Permitindo salvar data da viagem com data posterior a hoje

### ISSUE THREAD

**Issue by jgracino** [db1group/contra-covid19#547]
Ambiente: https://qa-app.notificasaude.com.br/notificacoes/cadastro

**Comportamento atual**
Está permitindo gravar data posterior no campo data da viagem

![image](https://user-images.githubusercontent.com/16705663/81824644-17d1e800-950c-11ea-9119-f959c44bf485.png)

Na tela de visualização pode confirmar que salvou com a data posterior a hoje:

https://qa-app.notificasaude.com.br/notificacoes/33583a0c-96fb-49d7-8fb1-8cf34e7e939b/view

**Comment by nasouza2** [comment]
@alexunderline  Não permite data de viagem igual a hoje. Favor ajustar

![1MejjaPAm3](https://user-images.githubusercontent.com/17462759/82047686-a15af480-9689-11ea-918a-bd6cdcc05d12.gif)

**Comment by nasouza2** [comment]
OK, homologado. Validado a inclusão e a edição.

![cAxpQ8QSJX](https://user-images.githubusercontent.com/17462759/82094888-50bcb900-96d4-11ea-977b-4d58b35c8a70.gif)
