### ISSUE TITLE
Ao cadastrar uma nova notificação de um paciente que esteja encerrado não está sendo atualizado os dados do paciente caso precise

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#549]
## Bug Report

**Comportamento atual**
Caso exista uma notificação encerrada e eu for cadastrar uma nova utilizando o mesmo documento, o sistema reaproveita as informações de identificação do paciente.

Erro: ao cadastrar uma nova ficha com o mesmo documento e na hora de informar esses dados e precisar atualizar algum dado que esteja desatualizado, como por exemplo, atualizar o endereço, ao salvar a notificação ela está sendo salva com os dados antigos já salvos no sistema anteriormente e não está fazendo a atualização dessas informações que eu alterei.

**Comportamento/código esperado**

Caso eu esteja cadastrando uma notificação que as informações do paciente já esteja salva no sistema, verificar se eu fiz alguma alteração nesses dados e salvar corretamente.

**Comment by AndressaKarla** [comment]
@rgsouzabr Verificar se o que a @100198 descreveu no card deveria ser mesmo dessa maneira ou se não estaria sendo alterado os dados deviso as regras dessa outra issue #442
