### ISSUE TITLE
Campo Febre sem separação decimal.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#551]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha inclua uma notificação de paciente com febre
Quando eu consultar a notificação
Então o campo febre estará sem a separação decimal.

Problemas
Campo "Febre" sem separação decimal. Na inclusão fica correto, porém na consulta não. 

Resultado esperado
Ajustar o campo Febre para apresentar o decimal.

![img1 - como foi incluído](https://user-images.githubusercontent.com/17462759/81847186-a30da680-9529-11ea-853b-68f3f620421e.png)
![img2 - como ficou](https://user-images.githubusercontent.com/17462759/81847190-a43ed380-9529-11ea-92ca-d36af7ff0320.png)

**Comment by wildeee** [comment]
Corrigido no front.
Entretanto, o erro era que no cadastro/edição o front mandava o valor pro back-end salvar sem o separador decimal.
Em outras palavras, para novos registros ou edição de registros, vai funcionar, mas para registros antigos que não foram editados, isso ainda vai estar bugado.

Por conta disso, abri a issue #574 com a mesma gravidade desse, para que possíveis erros desse campo sejam verificados no banco de produção.

**Comment by nasouza2** [comment]
Ok, validado.

[Evidência.zip](https://github.com/db1group/contra-covid19/files/4634312/Evidencia.zip)

**Comment by rgsouzabr** [comment]
Apliquei o script em produção.
update "NotificacaoCovid19" set "temperaturaFebre" = substring("temperaturaFebre",1,2) || ',' || substring("temperaturaFebre",3,1)
where length("temperaturaFebre") = 3

Consultei todas as temperaturas e estão corretas agora.
