### ISSUE TITLE
Ajustes na planilha exportada para o excel.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#553]
Ambiente
https://qa-app.notificasaude.com.br

Problemas
- Ajustar coluna "tomografiaVitro" para "tomografiaVidro" visto que o nome do exame é VIDRO FOSCO DE PREDOMÍNIO PERIFÉRICO E BASAL.
- Coluna "imunodeficiencia" não mostra que também se trata de "imunodepressão". Favor verificar se é necessário alterar o nome da coluna. Nas comorbidades, a doença é "Imunodecifência/imunodepressão".
- Confirmar se a coluna "localDoContatoComSuspeitoOutro" está sendo utilizada em tela. Se não estiver, favor remover. O local de contato é apresentado na coluna "localDoContatoComSuspeito".

Em anexo, as colunas citadas estão em amarelo.

[exemplo planilha.xlsx](https://github.com/db1group/contra-covid19/files/4624005/exemplo.planilha.xlsx)

**Comment by monitorcosta** [comment]
- Alterado o nome das colunas de "tomografiaVitro" para "tomografiaVidro" e "imunodeficiencia" para "Imunodecifência/imunodepressão";
- No banco a coluna está com o nome de NotificacaoCovid19.tomografiaVitro, talvez seja bom avaliar mudar o nome no banco para o nome certo e os respectivos campos nos processos internos do front e do back;
- Quanto a coluna "localDoContatoComSuspeitoOutro" mantive devido no item 10 da ficha em anexo (da Secretaria de Saúde de Maringá) ter opção de digitar local de contato quando marcado como "Outro". Sugiro avaliar necessidade de incluir este campo na tela e no item 10, campo "Local do contato", incluir a opção "Outro". Caso o usuário escolha "Local do contato" como "Outro" seja obrigatório digitar este campo. 

![imagem_evidencia_contato_local_outro](https://user-images.githubusercontent.com/22552329/81874791-137ded00-9555-11ea-8990-1085ae86a672.jpg)


@nasouza2 @rgsouzabr

**Comment by rgsouzabr** [comment]
Quanto a coluna "localDoContatoComSuspeitoOutro" mantive devido no item 10 da ficha em anexo (da Secretaria de Saúde de Maringá) ter opção de digitar local de contato quando marcado como "Outro". Sugiro avaliar necessidade de incluir este campo na tela e no item 10, campo "Local do contato", incluir a opção "Outro". Caso o usuário escolha "Local do contato" como "Outro" seja obrigatório digitar este campo.
___________________________________________________________________________
A avaliação está correta.

**Comment by AndressaKarla** [comment]
> Quanto a coluna "localDoContatoComSuspeitoOutro" mantive devido no item 10 da ficha em anexo (da Secretaria de Saúde de Maringá) ter opção de digitar local de contato quando marcado como "Outro". Sugiro avaliar necessidade de incluir este campo na tela e no item 10, campo "Local do contato", incluir a opção "Outro". Caso o usuário escolha "Local do contato" como "Outro" seja obrigatório digitar este campo.
> 
> A avaliação está correta.

@nasouza2 vc poderia verificar depois o comentário do @rgsouzabr ?

**Comment by nasouza2** [comment]
@monitorcosta Ricardo, expliquei melhor pro Rogerio sobre o item do local e alinhamos que a coluna "localDoContatoComSuspeitoOutro" pode ser removida do relatório.

**Comment by monitorcosta** [comment]
Coluna localDoContatoComSuspeitoOutro retirada da exportação para excel

@nasouza2 @rgsouzabr

**Comment by nasouza2** [comment]
Ok, homologado.

[evidência.xlsx](https://github.com/db1group/contra-covid19/files/4634504/evidencia.xlsx)
