### ISSUE TITLE
Tela para aprovação de dados para divulgação

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#556]
Requisito anexo
[Requisitos Fechamento Indicadores.docx](https://github.com/db1group/contra-covid19/files/4624455/Requisitos.Fechamento.Indicadores.docx)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/05/2020 no ambiente https://qa-app.notificasaude.com.br/fechamento e na base de dados de QA:

select definirfatodia('aaaa-mm-dd');
select definirfatonotificacao();

![3TxTQhDPdM](https://user-images.githubusercontent.com/15328510/82857808-6f972880-9ee8-11ea-8fc0-697177b1ee6b.gif)

![PUMLkuHcTj](https://user-images.githubusercontent.com/15328510/82857929-c7ce2a80-9ee8-11ea-874e-3f9f02ca601b.gif)

![3Jp4mEGEgW](https://user-images.githubusercontent.com/15328510/82858087-41661880-9ee9-11ea-9d31-c95218fcc6c4.gif)
