### ISSUE TITLE
Estão conseguindo digitar notificacoes com o mesmo número de documento em produção

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#557]
O número de documento "03462558994" possui dois cadastros em produção. O cadastro foi feito em 13/05/2020. São notificações digitadas em horários diferentes.

Entretanto, também existem notificações "identificas". O usuário comentou que quando demora para salvar o pessoal está pressionando mais vezes no botão salvar. Percebi que a maioria está ocorrendo no zona norte.
![Erro Duplicidade](https://user-images.githubusercontent.com/64052760/81873372-09a6ba80-9552-11ea-86b1-f36338aa3d25.PNG)

**Comment by AndressaKarla** [comment]
@rgsouzabr Verificar se esse caso ainda estaria ocorrendo em produção
