### ISSUE TITLE
Permitindo editar notificação encerrada.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#559]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha lançado uma evolução que encerre a notificação
Quando eu acessar a tela de Consulta de notificação
E localizar o paciente utilizado
Então o botão Editar estará habilitado
E estará permitindo alterar a notificação.

Problema
Opção Editar habilitada para notificação encerrada, permitindo assim, edição de notificação encerrada.

Resultado esperado
Desabilitar o botão EDITAR caso a notificação esteja encerrada.

![CYa0pPVrI1](https://user-images.githubusercontent.com/17462759/81939785-29c78f80-95cd-11ea-8b7c-ebfdc7874690.gif)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 14/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![9sjFnPivOp](https://user-images.githubusercontent.com/15328510/82002316-e0f6f180-9633-11ea-9077-e0d9f04fad15.gif)

**Comment by nasouza2** [comment]
Criado caso de teste para esse caso.
