### ISSUE TITLE
Opção EXPORTAR liberada para usuários que não são da secretaria da saúde.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#561]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha acessado o sistema com um usuário "comum"
Quando eu acessar a tela de Consulta de notificação
Então o botão Exportar está disponível.

Problema
Opção EXPORTAR disponível para usuários que não são da secretaria da saúde.

Resultado esperado
Bloquear acesso a opção EXPORTAR, caso o usuário logado não seja um usuário da secretaria da saúde.

![img1](https://user-images.githubusercontent.com/17462759/81948708-6baa0300-95d8-11ea-994c-1bc6f4d38f99.png)
![img2](https://user-images.githubusercontent.com/17462759/81948712-6c429980-95d8-11ea-8ebd-2b1839e48cfb.png)

**Comment by wildeee** [comment]
Corrigido no front. Seria desejável que fosse implementado também o controle de acesso no back-end.

Implementei nesse card também a sugestão que tinha me passado no privado mais cedo, de jogar o exportar no menu, mas também mantive na listagem.
(inclusive, não encontrei issue aberta pra isso, mas se tiver aberto, pode testar junto, por favor)

**Comment by nasouza2** [comment]
@wildeee Ainda posso acessar a opção se eu informar a rota direto na barra de endereço. Favor bloquear.

![PXUPr18n4i](https://user-images.githubusercontent.com/17462759/82048444-14b13600-968b-11ea-80ac-432e3671efe4.gif)

**Comment by nasouza2** [comment]
@wildeee Identifiquei que essa situação de acessar URL indevidamente, está acontecendo com outras opções do sistema, então vou abrir um card especifico para isso. Não precisa tratar o EXPORTAR por esse card; vou colocar essa opção junto com o card novo. 

Obrigada.

**Comment by nasouza2** [comment]
OK, validado.

![FVooVMo3PA](https://user-images.githubusercontent.com/17462759/82082561-9c646800-96be-11ea-95b3-205512e208b0.gif)
