### ISSUE TITLE
Remover label "Cadastros" da tela de Notificações.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#562]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha acessado a tela de Consultar Notificações
Então do lado esquerdo está sobrando a label "Cadastros".

Problema
Remover label "Cadastros" da tela de Notificações, pois ele não está sendo utilizado.

![img1](https://user-images.githubusercontent.com/17462759/81949532-57b2d100-95d9-11ea-86e8-ad5294209df2.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 15/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![image](https://user-images.githubusercontent.com/15328510/82107461-43b4bf80-96fe-11ea-9f7a-e0155426a4fb.png)
