### ISSUE TITLE
BUG - Desabilitar o botão 'CADASTRAR', enquanto a requisição estiver pendente

### ISSUE THREAD

**Issue by alexunderline** [db1group/contra-covid19#564]
Solução alternativa para evitar requests simultâneas, que estão causando notificações e evoluções duplicadas.

- O usuário não aguarda a request finalizar, e acaba clicando novamente no botão 'cadastrar', consequentemente, enviando mais de uma request e assim, duplicando informações.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 14/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes

![lsbUeD3Pl2](https://user-images.githubusercontent.com/15328510/82001418-907e9480-9631-11ea-83b2-3898b38cd723.gif)

**Comment by nasouza2** [comment]
Caso de teste criado.
