### ISSUE TITLE
Campo "Informar temperatura" não obrigatório.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#569]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha esteja incluindo uma notificação
Quando eu marcar a opção Febre (aferida/referida)
E não preencher o campo "Informar temperatura" 
E clicar em ENVIAR
Então está sendo permitido.

Problema
Está permitindo incluir notificação de paciente com febre, sem informar a febre.

Resultado esperado
Tornar o campo "Informar temperatura" obrigatório, quando a opção Febre (aferida/referida) for estiver marcada.
![img1](https://user-images.githubusercontent.com/17462759/81987040-500e1f00-960f-11ea-835d-6b5e06dd0f01.png)

![img1](https://user-images.githubusercontent.com/17462759/81987029-4ab0d480-960f-11ea-8c55-ac77ff03430b.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 15/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![qp9hq6FJ1s](https://user-images.githubusercontent.com/15328510/82106012-dc464200-96f4-11ea-9c7d-3d15419a569e.gif)
