### ISSUE TITLE
Permitindo acessar indevidamente funcionalidade e dados de outra unidade, direto pela URL.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#580]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
1) Primeiro cenário: Visualizar
Dado que eu tenha esteja incluindo uma notificação
Quando eu me logar em outra unidade
E na barra de endereço colocar o ID da notificação da outra unidade
Então está sendo permitido visualizar os dados da notificação da outra unidade.

2) Segundo cenário: Editar.
Dado que eu tenha esteja incluindo uma notificação numa unidade
Quando eu me logar em outra unidade
E na barra de endereço colocar o ID da notificação da outra unidade
Então está sendo permitido visualizar os dados da notificação da outra unidade.

3) Terceiro cenário: Exportar.
Dado que eu esteja logado com um usuário comum
Quando eu acessar a opção de exportar direto pela URL
Então a tela de exportar será aberta.

Problema
1) Permitindo acessar dados de outras unidades.
2) Permitindo acessar o exportar mesmo não sendo usuário da secretaria da saúde.

Resultado esperado
- Não permitir acesso a dados de outra unidade direto pela URL
- Não permitir acesso ao exportar, caso o usuário não seja da secretaria da saúde (o menu já está correto, falta tratamento para a URL).

OBS: Usuários da secretaria da saúde podem visualizar dados de outras unidades. O bloqueio portanto deve ser somente entre usuários comuns.

![4o2qbrFYXg](https://user-images.githubusercontent.com/17462759/82069007-21dd1d80-96a9-11ea-86b3-a64a3683d8b2.gif)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 18/05/2020 no ambiente https://qa-app.notificasaude.com.br/

![Rdq2YhLtuK](https://user-images.githubusercontent.com/15328510/82276565-03eb1380-995c-11ea-9647-c372b7076a54.gif)
