### ISSUE TITLE
Campo temperaturaFebre está sendo exportando para o excel com ponto ao invés de vírgula

### ISSUE THREAD

**Issue by monitorcosta** [db1group/contra-covid19#588]
## Bug Report

**Comportamento atual**
Campo NotificacaoCovid19.temperaturaFebre está exportando número decimal com ponto para o excel.

**Comportamento/código esperado**
Campo NotificacaoCovid19.temperaturaFebre deveria exportar número decimal com vírgula para o excel.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 18/05/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/exportar

![VBF2IXwniM](https://user-images.githubusercontent.com/15328510/82275046-224f1000-9958-11ea-9fac-9bd1e081b249.gif)
