### ISSUE TITLE
Botão EXPORTAR não está funcionando para datas anterior ao mês 05

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#591]
**Comportamento atual**

SECRETARIA DA SAUDE: Percebi que ainda não consigo realizar a exportação em alguns casos. Quando solicito a exportação do dia 01/05/2020 até a data atual consigo fazer a exportação. Mas quando coloco qualquer da de inicio anterior a exportação não ocorre. Aguardei vários minutos achando que poderia levar um tempo até baixar todo o arquivo mas mesmo assim não ocorreu a exportação.

Exemplo se colocar qualquer dia do mês 04 até a data de hoje 18-05 não ocorre a exportação.

**Comportamento/código esperado**

Exportar dados de qualquer data inserida no sistema.

**Comment by monitorcosta** [comment]
Para o dev que for atender esta Issue será necessário acesso ao banco de dados de produção.

@rgsouzabr  @100198

**Comment by monitorcosta** [comment]
Criado localmente uma base de dados com 8000 (oito mil) notificações fakes e uma nova classe para exportar notificação de excel. Adicionados logs na classe atual e na nova. 
Efetuados testes tanto na classe atual como na classe nova. Anotados o tempo cronometrado entre a requisição no front e o download e registrado em arquivo txt anexado a este comentário.
Como evidência segue as planilhas de excel geradas nos dois processos.
Seguindo as evidências acredito que a demora ocorre na montagem da resposta pelo servidor e o download pelo front.

[processo_atual.xlsx](https://github.com/db1group/contra-covid19/files/4674297/processo_atual.xlsx)
[processo_novo.xlsx](https://github.com/db1group/contra-covid19/files/4674300/processo_novo.xlsx)
[Logs processamento excel.txt](https://github.com/db1group/contra-covid19/files/4674301/Logs.processamento.excel.txt)

**Comment by maykon** [comment]
@monitorcosta Remova o código antigo e pode subir o novo. Mude console.error para console.info.

**Comment by monitorcosta** [comment]
> @monitorcosta Remova o código antigo e pode subir o novo. Mude console.error para console.info.

Feito
