### ISSUE TITLE
Ícone de mostrar/ocultar senha não funciona.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#593]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha esteja na tela de login
Quando eu informar a senha
E clicar no ícone para mostrar a senha
Então a senha não é apresentada.

Problema
Não mostra a senha quando clicado no ícone de mostrar/ocultar senha.

Resultado esperado
Ajustar funcionalidade desse ícone.

![AnneLJ8H7j](https://user-images.githubusercontent.com/17462759/82241551-bc8c6500-9912-11ea-8990-8cd65950b3d0.gif)

**Comment by maykon** [comment]
@nasouza2 não tem esse recurso, esse ícone é apenas um recurso visual.

**Comment by nasouza2** [comment]
@maykon Um recurso visual que leva o usuário a clicar e não tem ação nenhuma. Já que não tá implementado, o melhor não é retirar esse ícone?

**Comment by maykon** [comment]
@nasouza2 Isso é recurso do Firefox, não tem implementação :)

![image](https://user-images.githubusercontent.com/14884/82380518-f8045d80-99fe-11ea-9e4f-c65db9265a4e.png)

**Comment by maykon** [comment]
Ignorar comentário anterior, já estou removendo o ícone.

**Comment by nasouza2** [comment]
Ok, validado.
- Chrome:

![Chrome](https://user-images.githubusercontent.com/17462759/82572959-855cc480-9b5b-11ea-80f5-b2e08a7478b9.png)

- Firefox:

![Firefox](https://user-images.githubusercontent.com/17462759/82572983-8d1c6900-9b5b-11ea-8255-3268848658c0.png)
