### ISSUE TITLE
Opção "Esqueceu sua senha?" não valida usuários não cadastrados.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#594]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu tenha esteja na tela de login
Quando eu clicar em Esqueceu sua senha?
E informar um email ou usuário não cadastrado
E clicar no ícone para mostrar a senha
Então será apresentada a mensagem: "Você deverá receber um e-mail em breve com mais instruções.", mesmo e email/usuário não estando cadastrado.

Problema
Opção "Esqueceu sua senha?" não valida email/usuário não cadastrados.

Resultado esperado
Validar o email ou usuário informado na opção "Esqueceu sua senha?"; caso ele não esteja cadastrado, apresentar uma mensagem. Sugestão: "Não localizamos sua conta. Verifique as informações e tente novamente.".

![9vPwvIHYqe](https://user-images.githubusercontent.com/17462759/82242318-03c72580-9914-11ea-92be-96f1826f0010.gif)

**Comment by nasouza2** [comment]
O card foi aberto fazendo comparação com o login do Facebook e do LinkedIn; ambos indicam que não foi localizada conta para o email informado pelo usuário.

Porém em conversa com a @AndressaKarla, foi-me passado que indicar que o usuário não  está cadastrado pode dar margem para vulnerabilidade de segurança. 

Uma sugestão dela, é alterar a mensagem incluindo o "Se": "Se você tiver conta cadastrada, deverá receber um e-mail em breve com mais instruções.". Dessa forma, como não fica claro se o usuário tem ou não conta, isso pode não ser explorado explicitamente como uma vulnerabilidade.

A Andressa vai verificar modelos de sistemas que apresentam esse tipo de mensagem. Aguardar.

**Comment by AndressaKarla** [comment]
> O card foi aberto fazendo comparação com o login do Facebook e do LinkedIn; ambos indicam que não foi localizada conta para o email informado pelo usuário.
> 
> Porém em conversa com a @AndressaKarla, foi-me passado que indicar que o usuário não está cadastrado pode dar margem para vulnerabilidade de segurança.
> 
> Uma sugestão dela, é alterar a mensagem incluindo o "Se": "Se você tiver conta cadastrada, deverá receber um e-mail em breve com mais instruções.". Dessa forma, como não fica claro se o usuário tem ou não conta, isso pode não ser explorado explicitamente como uma vulnerabilidade.
> 
> A Andressa vai verificar modelos de sistemas que apresentam esse tipo de mensagem. Aguardar.

Como a @nasouza2 comentou anteriormente segue um print sobre sugestão de msg de recuperação de senha do outlook da Microsoft:

![image](https://user-images.githubusercontent.com/15328510/82248894-48a48980-991f-11ea-96af-b1e7df3f6e5f.png)

**Comment by nasouza2** [comment]
Depois da explicação da Andressa, opto por fechar a issue, visto que a mensagem está adequada ao cenário citado.
