### ISSUE TITLE
Redirecionamento após recuperação de senha.

### ISSUE THREAD

**Issue by nasouza2** [db1group/contra-covid19#595]
Ambiente
https://qa-app.notificasaude.com.br

Reprodução
Dado que eu esteja na tela de Atualização de senha
Quando eu informar a nova senha
E clicar em OK
E a senha ser atualizada
Então não uma opção para retomar para o login; se atualizar a página, será apresentada mensagem de que a sessão foi expirada.

Problema
Não há redirecionamento para a tela de Login, depois que há recuperação de senha.

Resultado esperado
Após a senha ser alterada, redirecionar para a tela de Login ou ter uma opção para o usuário ir para essa a tela de Login, para que ele não tenha que digitar novamente a URL do sistema.

![4vOF2Ayh3l](https://user-images.githubusercontent.com/17462759/82250641-36781a80-9922-11ea-90ae-8d5dcd52ad50.gif)

**Comment by maykon** [comment]
@nasouza2 vou colocar um link para voltar para o login. Vai ficar mais ou menos assim.

![image](https://user-images.githubusercontent.com/14884/82382555-8e864e00-9a02-11ea-930a-52fe3d46dbca.png)

Pode ser?

**Comment by maykon** [comment]
@nasouza2 Eu consegui alterar configuração no keycloak para redirecionar para a aplicação, tenta agora.

**Comment by AndressaKarla** [comment]
> @nasouza2 vou colocar um link para voltar para o login. Vai ficar mais ou menos assim.
> 
> ![image](https://user-images.githubusercontent.com/14884/82382555-8e864e00-9a02-11ea-930a-52fe3d46dbca.png)
> 
> Pode ser?

@maykon Eu conversei com a @nasouza2 e segundo ela poderia ser da maneira como vc propôs

**Comment by nasouza2** [comment]
Ok, validado. Depois que informar a nova senha, o login será automático,

![ny8sk6BjRI](https://user-images.githubusercontent.com/17462759/82571451-5ba29e00-9b59-11ea-9f83-d19f84333d0f.gif)
