### ISSUE TITLE
BUG CRITICO - Fichas na evolução esta aparecendo o confirmado antes do caso suspeito

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#603]
**Comportamento atual**

Recebido pela secretaria:
Estamos com problemas, algumas fichas na evolução esta aparecendo o confirmado antes do caso suspeito. Dai eu não consigo inserir que o paciente foi curado.

**Comportamento/código esperado**

Fazer a correção e esse erro não persistir, com isso possibilitando conseguir informar que o paciente foi curado.

![2](https://user-images.githubusercontent.com/64612597/82461718-1d41ac00-9a91-11ea-887d-9357e168702b.png)

![1](https://user-images.githubusercontent.com/64612597/82461723-1f0b6f80-9a91-11ea-87a8-7b52bcf5b356.png)

**Comment by nasouza2** [comment]
@100198 Conforme identicado pela Andressa, é provável que seja o mesmo caso da issue #583 

@alexunderline  Favor verificar e se for o mesmo caso, podemos liberar a versão em produção.
