### ISSUE TITLE
Remoção da coluna 'qtdInternado' na consulta dos dados de fechamento

### ISSUE THREAD

**Issue by alexunderline** [db1group/contra-covid19#605]
Na versão anterior da vwboletim, a mesma retornava a quantidade de usuários internados, porém, esta informação não será mais utilizada, assim, a consulta que dados de fechamento, ainda estava utilizando esta informação, usando o valor 'null', causando bug no momento da inserção das informações.

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/05/2020 na base de dados de QA

![image](https://user-images.githubusercontent.com/15328510/82846447-4b732180-9ebf-11ea-8b6c-0440fa42f731.png)
