### ISSUE TITLE
Mudar a forma de alimentar o local da evolução

### ISSUE THREAD

**Issue by rgsouzabr** [db1group/contra-covid19#626]
Uma descrição clara e concisa de qual problema é: Ex.: Eu tenho um problema quando [...]
O sistema deverá "contabilizar" o local que os pacientes estão.

**Descreva a solução que você gostaria**
Retirar o local da evolução. O campo deverá ser alterado diretamente da notificação. Entretanto, deve-se gerar um histórico de mudança.

Essa informação deverá ser "contabilizada" para que seja possível recuperar no fechamento. Atualmente é alimentado no fato. Atualizar no fechamento todos que estão em "andamento".

![Evolucao Local](https://user-images.githubusercontent.com/64052760/83153120-f6a8f400-a0d4-11ea-8e91-0b3b77424d4e.png)

**Comment by maykon** [comment]
Remover Local Isolamento
