### ISSUE TITLE
Possibilitar fazer IMPRESSÃO de notificações

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#646]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Solicitação da SMS: Criar um botão em que eles consigam fazer a impressão da notificação com todos os dados do paciente, e se puder, colocar algo que indique que aquele notificação já foi impressa.

**Descreva a solução que você gostaria**
Possibilitar fazer a impressão de notificações dentro do sistema.

**Comment by maykon** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/14884/87149433-95a13e00-c286-11ea-887f-26fe8dc4edb3.png)
