### ISSUE TITLE
notificacao/cadastro Pesquisar tabela de profissões

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#72]
## Feature Request

**Descreva a solução que você gostaria**
O campo Profissão deve ser alimentado com dados do backend.

**Documentação, Adoção, Estratégia de migração**
[Requisitos, página 4](https://db1global-my.sharepoint.com/:w:/r/personal/andressa_pilar_db1_com_br/_layouts/15/Doc.aspx?sourcedoc=%7B5F7EF694-D48F-4DB7-9761-C665136C9085%7D&file=Requisitos%20Notificacao%20Covid19.docx&action=default&mobileredirect=true)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020:

GET: https://qa-api.notificasaude.com.br/api/profissoes
Cadastro de Notificação: https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80288239-197a6e00-870d-11ea-96ba-1d8b56bcca8f.png)
