### ISSUE TITLE
/evolucao Erro no label de situação da evolução

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#73]
## Bug Report

**Comportamento atual**
O label para situação da evolução está com o texto errado
![image](https://user-images.githubusercontent.com/6723988/79696531-a0ce6a00-8253-11ea-8913-2d15d9ca5d97.png)

**Comportamento/código esperado**
O texto deveria ser Situação

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 23/04/2020 no ambiente https://app.notificasaude.com.br/

![image](https://user-images.githubusercontent.com/15328510/80161719-a3102b80-85a7-11ea-8adf-fce990f68ce9.png)
