### ISSUE TITLE
/evolucao - Carregar dados da listagem da evolução da notificação

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#74]
## Feature Request

**Descreva a solução que você gostaria**
Deve mostrar os dados do histórico de evoluções da notificação

**Documentação, Adoção, Estratégia de migração**
API: **/notificacoes/**_{notificacaoId}_**/evolucoes**

![image](https://user-images.githubusercontent.com/6723988/79696636-5e595d00-8254-11ea-95a7-b17082312e7b.png)

Json de retorno
```js
{
  "data": {
    "count": 1,
    "rows": [
      {
        "status": "ABERTA",
        "id": "6d26924b-1540-4795-952f-a8f701666d71",
        "Pessoa": {
          "nome": "Maykon Capellari",
          "numeroDocumento": "16857253501",
          "telefoneContato": "44991051563"
        },
        "NotificacaoEvolucaos": [
          {
            "id": "6d26924b-1540-4795-952f-a8f701666d71",
            "notificacaoId": "6d26924b-1540-4795-952f-a8f701666d71",
            "observacao": "asdf",
            "dtEvolucao": null,
            "tpEvolucao": "SUSPEITO",
            "tpLocal": "local",
            "createdAt": null,
            "updatedAt": null
          }
        ]
      }
    ]
  }
}
```

**Comment by CristianeBorges05** [comment]
@maykon  @FabioBezerra  @ftathiago 
Pessoal, não está exibindo conforme a máscara solicitada no padrão do mockup.
Foi alinhado algo sobre isso?

![image](https://user-images.githubusercontent.com/63747448/80283114-cb08a780-86eb-11ea-9017-8d6a478eeb65.png)

**Comment by AndressaKarla** [comment]
> @maykon @FabioBezerra @ftathiago
> Pessoal, não está exibindo conforme a máscara solicitada no padrão do mockup.
> Foi alinhado algo sobre isso?
> 
> ![image](https://user-images.githubusercontent.com/63747448/80283114-cb08a780-86eb-11ea-9017-8d6a478eeb65.png)

Seguindo comentário da @CristianeBorges05 , irei retornar essa issue para "To Do"

**Comment by maykon** [comment]
@AndressaKarla Foi criado máscara para documento tipo CPF, outros documentos não terão máscara. Adicionado máscara de telefone e celular.
![image](https://user-images.githubusercontent.com/14884/80819813-191a2100-8bac-11ea-9f91-2b0f0136882e.png)
![image](https://user-images.githubusercontent.com/14884/80819819-1c151180-8bac-11ea-84e4-08353ec5d5b7.png)

Disponível na PR https://github.com/db1group/contra-covid19/pull/421

**Comment by CristianeBorges05** [comment]
Topzeira
Validado QA
![image](https://user-images.githubusercontent.com/63747448/81130144-0e012100-8f1d-11ea-906e-4c545ead51c8.png)
