### ISSUE TITLE
Melhoria: Disponibilizar relatório dos confirmados após o fechamento

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#777]
Enviado pela secretaria:
-As 15:00 após o fechamento automático ser disponibilizado um relatório dos confirmados, RESIDENTES EM MARINGÁ, com nome, sexo, idade, comorbidades que foram confirmados nas últimas 24 horas para conferência do boletim

**Comment by maykon** [comment]
Durante o fechamento, pode ser filtrado todos os confirmados. Caso queira exportar estes dados, pode selecionar tudo (CTRL + A + CTRL + C) e colar numa planilha do Excel. Após o fechamento pode ser consultado via exportação das notificações.
