### ISSUE TITLE
Não permitir que a notificação receba evolução quando estiver no status encerrada/alterada

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#78]
## Feature Request

**Descreva a solução que você gostaria**
Quando a notificação estiver encerrada/excluída, impedir que novas evoluções sejam lançadas. 
Creio que isso possa ser feito no botão da tela de consulta e validando ao carregar a tela de evolução (para o caso de acesso direto).

**Documentação, Adoção, Estratégia de migração**
Desabilitar
![image](https://user-images.githubusercontent.com/6723988/79697627-045b9600-825a-11ea-838e-9571bff23319.png)

Impedir entrada em /evolucao
![image](https://user-images.githubusercontent.com/6723988/79697652-13424880-825a-11ea-8238-0965a9d174b9.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020:

Consulta de Notificações: https://qa-app.notificasaude.com.br/notificacoes
GET: https://qa-api.notificasaude.com.br/api/consulta?page=1&itemsPerPage=10%20%20%20%20%20%20%20%20&sortBy=&sortDesc=&status=ENCERRADA&search=
GET: https://qa-api.notificasaude.com.br/api/9dbada7d-a7ad-4fcb-bad3-964249d89c0a/evolucoes

![image](https://user-images.githubusercontent.com/15328510/80290295-d4f5cf00-871a-11ea-9444-880801f89df2.png)

Cadastro de Evolução dos pacientes: https://qa-api.notificasaude.com.br/api/9dbada7d-a7ad-4fcb-bad3-964249d89c0a/evolucoes
![REHQS8tQAp](https://user-images.githubusercontent.com/15328510/80290322-fd7dc900-871a-11ea-9b2a-922bc0597fa1.gif)
