### ISSUE TITLE
Exportar dados em formato CSV

### ISSUE THREAD

**Issue by BrunoMioto** [db1group/contra-covid19#795]
## Feature Request

**Descreva a solução que você gostaria**
Exportar os dados em .csv

**Descreva qualquer alternativa considerada**
Permitir que os dados sejam exportados para um mesmo endereço .csv, dessa forma plataformas que utilizem este banco de dados podem ser atualizados automaticamente.

**Documentação, Adoção, Estratégia de migração**
Utilização em análises estatísticas mais robustas e mais ágeis (por causa da atualização automática, e não manual).
Formas de trabalho: Raspadores de dados (como é utilizado hoje em Maringá); Baixar arquivo .csv atualizado (como no site do Ministério da Saúde); Atualização dos dados .csv em um endereço fixo (Atualização de análises externas de forma automática)

**Comment by maykon** [comment]
Boa tarde Bruno,

Hoje já é possível realizar a exportação das notificações para CSV. Sendo assim, estou fechando essa issue.

Qualquer dúvida pode entrar em contato.

**Comment by BrunoMioto** [comment]
Onde consigo exportar em CSV? E no caso seriam todos os dados do boletim mesmo...

**Comment by maykon** [comment]
A exportação você está comentando no portal https://notificasaude.com.br/? Se for vou reabrir e avaliar a possibilidade de criar essa issue.

**Comment by BrunoMioto** [comment]
Isso, do portal https://notificasaude.com.br/ mesmo. Sou externo à Secretaria de Saúde.
