### ISSUE TITLE
Exportar dados para o Excel

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#81]
## Feature Request

Peço que o dev, por favor, que inclua os detalhes da implementação já em curso.

**Comment by monitorcosta** [comment]
Criada exportação da notificação para Excel.
Foram criadas duas classes para efetuar o processamento.
Foi feita uma classe para pesquisar os campos necessários da notificação para exportação e o mapeamento destes campos com a coluna no Excel que levará seu nome.
A outra classe, que convém documentação exige três parâmetro:
- colunas: uma lista onde deve ser informado uma lista de objetos com as propriedade: nomeColuna e nomeCampo. A propriedade nomeColuna é informada a descrição da coluna no Excel, pode ser nome composto como exemplo “Data da Notificação”. Já a propriedade nomeCampo indica a respectiva propriedade, constante nos objetos do parâmetro lista, que contém a informação a ser incluída no excel. Caso não informado ;
- lista: uma lista contendo os objetos com os valores para inserir na planilha. A propriedade do objeto deve ser mapeada no parâmetro colunas;
- res: do tipo ServerResponse;

**Comment by AndressaKarla** [comment]
@monitorcosta Vc poderia me enviar mais detalhes dessa issue? Para eu saber como testá-la :)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-api.notificasaude.com.br/api/notificacao-gera-excel?dataInicial=2020-04-25&dataFinal=2020-04-26

![ezgif-7-574f93c330ae](https://user-images.githubusercontent.com/15328510/80321292-448abd80-87f2-11ea-89fc-ac9c0238212f.gif)

Excel "[_app_excel_675a0297-e106-481e-b2af-1c9000c3e1aa.xlsx](https://github.com/db1group/contra-covid19/files/4536571/_app_excel_675a0297-e106-481e-b2af-1c9000c3e1aa.xlsx)" em anexo
