### ISSUE TITLE
ERRO AO FAZER O ENVIO PARA A SECRETARIA

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#826]
Recebido da secretaria:

essa noite o zona norte precisou fazer envio para secretaria, mas não esta dando certo

eu também tentei e nao da certo. acabei tendo que fazer de casa essa transferencia, mas ja era quase meia noite, precisava ver se consegue liberar isso hoje ainda pois senao vamos ter problemas se eles não conseguirem transferir

e tentei em casa também ver sobre o campo das permissões e também nao aparece, atualizei a pagina, e nada aconteceu. e aqui também tentei em outras maquinas e outros computadores e não deu certo

outra coisa também, estamos com mais de 200 fichas, algumas até antigas que não estamos conseguindo enviar

por que hoje eu ja preciso fazer um comunicado pra todos eles que essa função está disponivel pra eles enviarem

outra coisa, a Farmacia droga raia também não esta exportando da mensagem de cnes invalido

**Comment by maykon** [comment]
@100198 Já foi realizado a correção deste problema, e o Christiano já cadastrou a farmácia.
