### ISSUE TITLE
Criar o campo municipioId no modelo de Notificacao

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#83]
## Feature Request

**O seu pedido de nova implementação está ligado a algum problema? Por favor, descreva.**
Uma descrição clara e concisa de qual problema é: Ex.: Eu tenho um problema quando [...]

**Descreva a solução que você gostaria**
Segundo o modelo, deve haver um campo municipioId na tabela de notificação
* [ ] - Alterar o modelo
* [ ] - Criar um novo migration
* [ ] - Alterar o arquivo seed para considerar o novo campo
* [ ] - Testar as operações de do e undo das migrations e dos seeds

**Documentação, Adoção, Estratégia de migração**
![image](https://user-images.githubusercontent.com/6723988/79698196-b3e63780-825d-11ea-9003-3718bd96221e.png)

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020:
- POST: https://qa-api.notificasaude.com.br/api/notificacoes 
- Cadastro de Notificação: https://qa-app.notificasaude.com.br/notificacoes/cadastro

![image](https://user-images.githubusercontent.com/15328510/80287647-eb932a80-8708-11ea-9637-ec6cbca2190c.png)
