### ISSUE TITLE
Data do fechamento está invertido

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#835]
Recebido pela secretaria:

Boa tarde!
Foi visualizada que a data do fechamento esta invertido, desde o dia 2 de outubro. Por favor, corrigir o erro.
No sistema DB1 esta 10-02-2020 ao invés de 02-10-2020 e 10-03-2020 ao invés 03-10-2020.
Encaminhado anexo para melhor visualização.
Att: Juliana Guilherme
![print](https://user-images.githubusercontent.com/64612597/95129207-101c1580-0731-11eb-82ee-784528ef64be.jpg)

**Comment by 100198** [comment]
@maykon

**Comment by maykon** [comment]
@100198 Testado no chrome e no firefox as datas estão corretas.
