### ISSUE TITLE
Alteração de endereço da paciente

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#836]
Recebido da secretaria:

Solicito que seja feita alteração do endereço de residencia de EUCRESIO DUTRA DE SOUZA, esse paciente entrou como positivo no fechamento do dia 14/07, e foi evoluído óbito no fechamento de 03/09 , precisamos tirar do boletim do dia 14/07 o positivo, e o obito do dia 03/09.Anexo copia da evolução

![WhatsApp Image 2020-10-02 at 14 35 03](https://user-images.githubusercontent.com/64612597/95129451-6426fa00-0731-11eb-9c91-418b48deb6d4.jpeg)

**Comment by 100198** [comment]
@maykon

**Comment by maykon** [comment]
@100198 Não encontrei esta notificação, deve ter sida excluída no sistema.
