### ISSUE TITLE
Alterar dados de duas fichas

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#838]
Recebido da secretaria:

Tem como você alterar alguns dados, fazendo favor
Essas duas fichas que foram encerradas,

- Maria da Silva Felix, cpf 012.885.008-66
é paciente institucionalizado,

o tipo institucionalizado é coabitante da instituição e não trabalhador da instituição,
e na ocupação colocar outros, e na descrição colocar ILPI

nas duas fichas dessa paciente.

- Aparecida Rines, cpf 308.583.059-68
é a mesma situação.
a paciente institucionalizado,

o tipo institucionalizado é coabitante da instituição e não trabalhador da instituição,
e na ocupação colocar outros, e na descrição colocar ILPI

nas duas fichas dessa paciente.

e tem uma terceira situação
tem como abrir a ficha da paciente Conceicao Aparecida Graciano, do dia 11/09/2020 13:09, notificado pela UNIDADE BASICA DE SAUDE VARDELINA
a ficha dela esta encerrada, no entanto esta sem evolução

**Comment by 100198** [comment]
@maykon

**Comment by maykon** [comment]
@100198 Feito
