### ISSUE TITLE
Alteração de Endereço para inserir o óbto

### ISSUE THREAD

**Issue by 100198** [db1group/contra-covid19#840]
RECEBIDO DA SECRETARIA:

Bom dia, preciso que seja alterado um endereço do sistema para que possamos inserir o óbito do paciente, está como Maringá, mas pertence ao municipio de Paiçandu, o confirmado foi inserido em 25/08/2020, por estar muito longe preciso que seja feito por ai, pra atualizar o fechamento do dia 25/08. Assim que conseguir alterar peço que me avise pra que possamos fazer a errata no boletim.

Paciente

Dionysio Benedetti cpf 023.424.569-72
Endereço Rua Angelo Bertazo, 739 Jardim Santa Luzia, Paiçandu.

**Comment by maykon** [comment]
@100198 Não encontrei este paciente, consegue ver com a secretaria qual o nome e cpf corretos?

**Comment by 100198** [comment]
Mandei um e-mail, assim que me enviarem eu lhe informo.

**Comment by maykon** [comment]
Acho que foi excluído a notificação, estou encerrando.
