### ISSUE TITLE
[Front] Criar comportamento dos campos da seção CONTATO COM SUSPEITO

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#85]
Descobrir como encaixar os campos desse componente na entidade Notificacao, popular o objeto.
Desabilitar campos quando a opção SIM não estiver marcada

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![nBCjnTAEtL](https://user-images.githubusercontent.com/15328510/80318014-8cebb080-87dd-11ea-9a9e-4f3ef160bb36.gif)
