### ISSUE TITLE
[Front] Criar comportamento dos campos da seção CONTATO COM CASO CONFIRMADO LABORATORIALMENTE PARA SARS-CoV2

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#86]
Descobrir como encaixar os campos desse componente na entidade Notificacao, popular o objeto.
Desabilitar campos quando a opção SIM não estiver marcada

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 25/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![tiehRr04CN](https://user-images.githubusercontent.com/15328510/80288917-9a3b6900-8711-11ea-8014-c68f45cd989a.png)
