### ISSUE TITLE
Remover filtro do endpoint de profissões

### ISSUE THREAD

**Issue by wildeee** [db1group/contra-covid19#88]
## Feature Request

Hoje as profissões são filtradas por nome, são necessárias pelo menos 3 letras.

**Descreva a solução que você gostaria**
Como a profissão é do profissional da saúde que faz a notificação, o filtro não será mais necessário

**Comment by AndressaKarla** [comment]
Testes concluídos com sucesso no dia 26/04/2020 no ambiente https://qa-app.notificasaude.com.br/notificacoes/cadastro

![6klsUc1wSc](https://user-images.githubusercontent.com/15328510/80319400-4b133800-87e6-11ea-8ef3-0b2a978e5a2f.gif)
