### ISSUE TITLE
Atualizar o model de NotificacaoCovid19

### ISSUE THREAD

**Issue by ftathiago** [db1group/contra-covid19#89]
Confrontando o MER com o modelo no sistema, aferi as seguintes diferenças:
Modelo tem, model não
-- tpVinculoEpidemiologico
-- gestante
-- febre
-- imc
-- nomelabenviomaterial
-- bo_gestante
-- bo_raioxNormal
-- tpNotificacao

Tem no model, mas não tem no Modelo
-- isolamentoDomiciliar
-- leitoComum
-- leitoUti
-- prontoSocorroOuAtendimento
-- laboratorioOficial
-- laboratorioRedePrivada
-- situacaoNoMomentoDaNotificacao
-- febreAferidaReferida
-- temperaturaFebre

Aparentemente repetidos no Modelo
-- Nome_Suspeito x nomesuspeitocontato
-- bo_raioX_normal x bo_raioX_normal

Aparentemente repetidos no Model
-- nomeTeveContato x nomeSuspeito

Por favor, consulte o @altitdb e o Rogério para saber como proceder com as discrepâncias.

Segue o MER para auxiliar análise
[Notificacao.pdf](https://github.com/db1group/contra-covid19/files/4500380/Notificacao.pdf)

**Comment by AndressaKarla** [comment]
@rgsouzabr @ftathiago Pelo histórico essa issue foi movida para a coluna "Produção", porém não há nenum pullrequest associado e nem foi homologado. Ainda vai ser implementada?
